### ISSUE TITLE
Images and CSS not displaying - suggestion for fix

### ISSUE THREAD

**Issue by beerlington** [mileszs/wicked_pdf#1]
I was trying to render a page within my application as a PDF and the images weren't loading and CSS styles weren't being applied. The reason is because wkhtmltopdf doesn't know which server to load them from. The fork at http://github.com/lleirborras/wicked_pdf suggests creating a custom layout for the PDF and specify the request host/port. This works, but is an unnecessary step if you just want to render your standard templates as is. My suggestion is to replace all the paths for things like /stylesheets and  /images after render_to_string:

```
# In make_pdf function of pdf_helper.rb

html_string = externals_to_absolute_path(render_to_string(:template => options[:template], :layout => options[:layout]))

# New function defined in pdf_helper.rb

def externals_to_absolute_path(html) 
  html.gsub(/\/(stylesheets|images|system)\//) {|s| "http://#{request.host_with_port}/#{$1}/" } 
end
```

I have hardcoded a few different paths that I am using (/system is where paperclip stores uploaded images), but these could easily be added to the options hash. You can do this with javascript files too, but one of the systems I tested on (Centos 5 w/ Ruby 1.8.5) was hanging with that included so I pulled it out.

**Comment by Suneel-NXVT** [comment]
This helper code works for me. 
 ```
def absolute_path_for_src(body)
    body.gsub(/(src|href)=('|")\//) { |s| "#{$1}=#{$2}#{request.protocol}#{request.host_with_port}/" }
  end
```
