### ISSUE TITLE
How to use --page-orientation P/L in wicked_pdf.pdf_from_string

### ISSUE THREAD

**Issue by serberman** [mileszs/wicked_pdf#1001]
In wkhtmltopdf, the ability to form several pages with mixed pages orientations has been added. How can this be done with wicked_pdf.pdf_from_string?
[https://github.com/wkhtmltopdf/wkhtmltopdf/pull/4439](url)
`wkhtmltopdf.exe part_1.htm --page-orientation L part_2.htm --page-orientation P part_3.htm --page-orientation L Output.pdf`

**Comment by marcosfelipe** [comment]
Hi, @serberman.
All you have to do is use a gem like 'combine_pdf' to combine different pdf specs.
Eg:
```
pdf_chunks = CombinePDF.new
pdf_chunks << CombinePDF.parse(WickedPdf.new.pdf_from_string(STRING, { orientation.. })
pdf_chunks << CombinePDF.parse(WickedPdf.new.pdf_from_string(STRING, { orientation.. })
pdf_chunks.to_pdf 
```
