### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by mathieujobin** [mileszs/wicked_pdf#1004]
## Issue description
no official release was made in 18 months+

creating an issue to continue discussion started in 
https://github.com/mileszs/wicked_pdf/pull/992

## Expected or desired behavior
We should have one or more release.

**Comment by mathieujobin** [comment]
@mileszs Do you need help making a release?

**Comment by unixmonkey** [comment]
@mathieujobin You can help by updating the CHANGELOG with summaries of the changes that have been merged. I'm happy to put out a release, but I haven't paid enough attention to the big picture in awhile to see if it needs to be a SEMVER breaking change version or not. What I don't want is to release a new patch or feature version that breaks apps.

**Comment by mathieujobin** [comment]
@unixmonkey have you had a chance to look at @1013 ?

Thanks

**Comment by mathieujobin** [comment]
Let me know if you need anything else

**Comment by unixmonkey** [comment]
Released as 2.6.0. Thanks for your help!
