### ISSUE TITLE
Where to find the latest releases?

### ISSUE THREAD

**Issue by tmaier** [mileszs/wicked_pdf#1017]
According to the [CHANGELOG](https://github.com/mileszs/wicked_pdf/blob/master/CHANGELOG.md), this gem is already at version 2.6.0. This is great to see.

But the last official release at https://rubygems.org/gems/wicked_pdf is version 2.1.0 from 2020
Also the releases/tags at https://github.com/mileszs/wicked_pdf/releases seem to be out of sync.

Are there any plans to release further versions at rubygems.org or alternatively, to release them via the [Github Package Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry)?

**Comment by unixmonkey** [comment]
The CHANGELOG only recently got updated to include all the merges until now. I've released the latest as version 2.6.0.

I'm not currently planning to release the intermediate versions unless there's an issue.

Please let me know if you have any issues with it.

**Comment by tmaier** [comment]
haha... that I created this issue is then a race condition. It seems like I wrote it exactly in the moment when you released it. Thanks mate!

I am happy with 2.6.0. I don't need any older version.
