### ISSUE TITLE
[Enable Forms] Radio button options do not react

### ISSUE THREAD

**Issue by mosinski** [mileszs/wicked_pdf#1023]
## Issue description
Hi folks,
I noticed some issue with radio buttons on pdf generated with option `extra: "--enable-forms"`
There is no reaction when trying to choose any of radio button options
Is any of You had similar issue or knows way to solve It I would be appreciated 🤜🤛

FYI On [docs](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt) I found options:
>      --radiobutton-checked-svg <path> Use this SVG file when rendering checked radiobuttons
>      --radiobutton-svg <path>        Use this SVG file when rendering unchecked radiobuttons

But I'm not sure if they are useful in my case 😅

## Expected or desired behavior
Be able to select one of radio button options on generated pdf document

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
>2.6.2

wkhtmltopdf version (output of `wkhtmltopdf --version`):
>wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:
[wkhtmltopdf-binary](https://rubygems.org/gems/wkhtmltopdf-binary)
[wkhtmltopdf-heroku](https://rubygems.org/gems/wkhtmltopdf-heroku)

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
>heroku-20

>macOS Big Sur 11.6.5

## Example

Repo https://github.com/mosinski/wicked_pdf_radio
Demo: https://wicked-pdf-radio.herokuapp.com

**Comment by mosinski** [comment]
Looks like interaction for radio buttons / select fields is not supported, at least what is said at [Issue#1583](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1583)

**Comment by unixmonkey** [comment]
That is correct. Those options are for rendering of the PDF, not interactivity.
