### ISSUE TITLE
How to avoid content cutting when textarea height is greater than PDF Page size

### ISSUE THREAD

**Issue by PriyankaRPathak** [mileszs/wicked_pdf#1026]
Hi,

I'm using wicked_pdf to generate PDF. I've footer on each page of PDF, when content of textbox is larger then PDF default page size than content splits into more than one page and all pages has footer which looks odd. 

I would like to avoid header / footer when auto page break happen, or i need to combine pages. So all content fits into one page.

Can anyone assist here? 

I've added sample PDF. I tried 
div.nobreak:before { clear:both; }
div.nobreak{ page-break-inside: avoid;
but it doesn't work.
![sample-pdf](https://user-images.githubusercontent.com/55856/171042208-fe183f61-e86f-4c93-b2f5-941d7be8087b.png)

**Comment by unixmonkey** [comment]
I'm hoping this worked for you, or at least pointed you in a workable direction.
Please let me know how it went if you can.
