### ISSUE TITLE
Font difference between development and production

### ISSUE THREAD

**Issue by joao-saraiva** [mileszs/wicked_pdf#1033]
First thanks for developing this gem, and im not a native english speaker.
We update our gem wkhtmltopdf-binary-edge', from 0.12.4.0 to 0.12.6.0, we were struggling with a couple of problems and was necessary to update the gem.
After that, the font size between development and production changed a lot. 
I ' m sharing the same pdf at different environments.

Development: https://drive.google.com/file/d/17rMnNqKMOuUhYNvJVt5ByeP0rGf558My/view
Production: https://drive.google.com/file/d/14wjQg3KFz1R6O_U7g0mb7rja4paqYWn_/view

Our config
```ruby
WickedPdf.config = {
  exe_path: ENV['path_wkhtmltopdf'],
  page_size: 'A4',
  layout: 'pdf.html.slim',
  dpi: '810',
  zoom: 1.0,
  margin: { top: 25},
  disable_links: true,
  disable_smart_shrinking: true,
  encoding: 'utf8'
}
```

CSS: 

```css
body {
  font-family: 'Arial';
  font-size: 9px;
}
```

**Comment by unixmonkey** [comment]
Were they the same (or close to it) before you upgraded `wkhtmltopdf-binary-edge`?

When you specify a font by name, like `'Arial'`, it will render the version of Arial it has installed locally. Linux has a different Arial than MacOS and Windows.

Other than that, it isn't unusual for `wkhtmltopdf` upgrades to change the font size. Try experimenting with `zoom: 1.28` or something like that, or lowering your DPI.
