### ISSUE TITLE
How are measurements calculated?

### ISSUE THREAD

**Issue by rdetert** [mileszs/wicked_pdf#1037]
My page size is set to A4. I want to make a div the full height of 11 inches. When I do this though, the div only extends 75% down the page on the pdf.

For example:
```
#cover {
  height: 11in;
}
```

**Comment by unixmonkey** [comment]
You might need to adjust the resolution or zoom options, as well as margins and padding to get your calculations to be more precise. `wkhtmltopdf` uses the screen resolution otherwise, which can vary widely from system to system (even headless).

Let me know how it goes!

**Comment by rdetert** [comment]
Ok thanks. Are there any standard settings you can recommend so that an inch prints out as an inch no matter which system? I've already zeroed out the margins.

**Comment by unixmonkey** [comment]
I do not know of any standards, but theoretically, at 300 DPI (dots per inch), the DPI is linear, so 300 * 11 (inches high) = 3300px of vertical space on a PDF page (using Letter size).

If that doesn't come out right, you might have to tweak the "zoom" setting. I've seen it common to set zoom to 1.25 other issues, and maybe "disable_smart_shrinking" and/or "lowquality" too.

**Comment by rdetert** [comment]
What exactly does the zoom refer to? Would altering the viewport help? I'm still trying to visualize how the default settings are calculated.

My dev environment is on a MacBook Air (2020) with default display settings connected to an external 4k monitor that is set to "Scaled" at 3008x1692 resolution.

**Comment by unixmonkey** [comment]
:shrug: From: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
> --zoom <float>                  Use this zoom factor (default 1)
