### ISSUE TITLE
Wicked_pdf on ubuntu 22.04

### ISSUE THREAD

**Issue by atekelt** [mileszs/wicked_pdf#1038]
I recently updated my OS from ubuntu 20.04 to 22.04 i did not upgraded it from the previous version i had to clean and install a fresh ubuntu 22.04 version, and everything works fine with the os and ruby on rails but from all the gems i need only wicked_pdf has an issue with my OS version.

> nvalid platform, must be running on Ubuntu 16.04/18.04/20.04 CentOS 6/7/8, Debian 9/10, archlinux amd64, or intel-based Cocoa macOS (missing binary:

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):wicked_pdf (2.6.3)

wkhtmltopdf version (output of `wkhtmltopdf --version`):  Shows The same Error 

> Invalid platform 

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu 22.04

**Comment by roostinghawk** [comment]
My error
`Invalid platform, must be running on Ubuntu 16.04/18.04/20.04 CentOS 6/7/8`

**Comment by philsmy** [comment]
Does this mean we need to move away from WickedPDF (or any other `wkhtmltopdf`-backed method) if we are on Ubuntu 22? Seems that the discussion over on the `wkhtmltopdf` GH point that that:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/5189

**Comment by ashkulz** [comment]
You should migrate away either way -- wkhtmltopdf is obsolete (I'm speaking with my hat as maintainer).

**Comment by jjb** [comment]
How are you installing wkhtmltopdf? via apt-get on ubuntu, or another method?

**Comment by pratik-kalathiya** [comment]
Follow my response on Stackoverflow - [https://stackoverflow.com/a/75843094/4018407](https://stackoverflow.com/a/75843094/4018407)

**Comment by unixmonkey** [comment]
Ubuntu 22.04 is supported with `gem 'wkhtmltopdf-binary'`.
https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/bin/wkhtmltopdf#L32
