### ISSUE TITLE
Can't generate PDF in production

### ISSUE THREAD

**Issue by gfsheppard** [mileszs/wicked_pdf#1042]
## Issue description
I think this is a permissions issue, but I can't figure it out.
I am using asdf to load Ruby for a Rails site. I have 4 apps running on the site, and I thought I could combine the asdf site into a common folder at /opt/asdf instead of the default ~/.asdf/ location.
PDF generation broke when I did that.

Now, despite rolling back to a previous version of the program, and using a clean install of all gems in the ~/.asdf/ folder, I still cannot generate a pdf on production.

My development site works locally, with Rails and wkhtmltopdf loaded from the gem file. No problems.

I have tried to adjust the `exe_path` in config/initializers/wicked_pdf.rb, but despite getting correct changes in the path, I still cannot generate a PDF.

Errors in the log/production.log are similar to this, depending on the version of rails, and the configuration in the initializer:

```

F, [2022-11-20T21:50:03.510604 #14087] FATAL -- : [4a8b5c53-08ca-420a-a8d0-a790d1c84c8e] RuntimeError (Failed to execute:
["/home/site/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf", "-q", "--orientation", "Landscape", "--page-size", "letter", "--title", "November 2022", "--margin-top", "5", "--margin-bottom", "5", "file:////tmp/wicked_pdf20221120-14087-1a4z3ct.html", "/tmp/wicked_pdf_generated_file20221120-14087-1ryaixk.pdf"]
 Command Error: /home/site/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize': Could not find racc-1.6.0 in any of the sources (Bundler::GemNotFound)

  
F, [2022-11-20T22:17:47.452960 #669] FATAL -- : [b0cb59f8-8ecc-4394-8b3c-b9fd0d7cb204] RuntimeError (Failed to execute:
["/usr/bin/wkhtmltopdf", "-q", "--orientation", "Landscape", "--page-size", "letter", "--title", "November 2022", "--margin-top", "5", "--margin-bottom", "5", "file:////tmp/wicked_pdf20221120-669-1r0jo9t.html", "/tmp/wicked_pdf_generated_file20221120-669-l4gf2z.pdf"]
Error: PDF could not be generated!



F, [2022-11-20T22:34:36.493624 #2957] FATAL -- : [29f871c1-8828-4be0-9147-e48ac2e9c739] RuntimeError (Failed to execute:
["/home/site/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf", "-q", "--orientation", "Landscape", "--page-size", "letter", "--title", 
November 2022", "--margin-top", "5", "--margin-bottom", "5", "file:////tmp/wicked_pdf20221120-2957-1n0z2ci.html", "/tmp/wicked_pdf_generated_file20221120-2957-1k0bfee.pdf"]
 Command Error: /home/site/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.3.12/lib/bundler/definition.rb:481:in `materialize': Could not find bcrypt-3.1.12, redcarpet-3.5.1, puma-3.9.1, sqlite3-1.3.13, byebug-11.1.3, mysql2-0.5.3, passenger-6.0.8, bindex-0.8.1, nio4r-2.5.7, websocket-driver-0.7.4, sassc-2.4.0, ffi-1.15.0, racc-1.5.2, eventmachine-1.2.7, http_parser.rb-0.6.0 in any of the sources (Bundler::GemNotFound)0:in `specs'


```

All gems are properly installed in the same location as the wicked_pdf gems.

I think this is a permission issue, but I can't think where I have screwed this up, as it is persisting despite reverting back from /opt/asdf to ~/.asdf, and also when reverting to code that was deployed prior to my more recent changes.

Not sure where to go for help.

## Expected or desired behavior
The site should generate the PDF in production.

## System specifications
 I am using asdf to with Ruby 2.7.3 and Rails 5.2.6. I am trying to update an older site to Rails 6 and Ruby 3.

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
 wicked_pdf (1.1.0)
  wicked_pdf (= 1.1.0)

wkhtmltopdf version (output of `wkhtmltopdf --version`):
wkhtmltopdf 0.12.4 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:
gem 'wkhtmltopdf-binary'

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
Ubuntu 18.04 server

**Comment by unixmonkey** [comment]
I see from the error message that it's failing after trying to execute this file:
```
/home/site/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf
```
Which is in the `wkhtmltopdf-binary` gem's source.
This file is a ruby script that chooses the best version of `wkhtmltopdf` to use based on your OS, and since it is a Ruby script it is trying to boot up Ruby with your bundler environment loaded, and for whatever reason that isn't working (likely due to your `asdf` config change).

I would suggest trying to hard-code the path to the actual binary (x86, x64, ARM), which is also packaged into that gem, something like this:
```ruby
WickedPdf.config = {
  exe_path: '/home/site/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_amd64'
  # or
  exe_path: "#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-#{Gem.loaded_specs['wkhtmltopdf-binary'].version}/bin/wkhtmltopdf_linux_amd64"
}
```
