### ISSUE TITLE
Keeping `pdf_to_string` temporary files

### ISSUE THREAD

**Issue by crespire** [mileszs/wicked_pdf#1044]
https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L46

I'm using the gem in a Rails context and I notice that the temp files remain until I restart the Rails server. Testing in my specific case, I didn't run into any issues changing `close` to `close!` in the `ensure` block. I see that the `pdf_from_url` method uses the `close!` method.

I was wondering if there was a reason we only close the file handle instead of using `close!` to also unlink/delete the tempfile in the `ensure` block. The useful work has already completed, and the block is forcing a file close, but leaving the temp file around. This led me to look into the blame and I found [this issue](https://github.com/mileszs/wicked_pdf/issues/948) which changed the usage of `close!` to `close` in order to preserve the files for debug purposes. Would it be possible to put this behind an option flag which defaults to using `close!`? There was discussion of this in the issue linked, but I don't think it was ever decided on or actioned. I have implemented a hacky "keep_temp" option for `pdf_from_string` which behaves as expected.

I think this allows folks to turn it on if they require it, but otherwise we don't stack a bunch of temp files that don't get cleaned up immediately. Happy to submit a PR on this, if maintainers agree on a default behaviour.

**Comment by steerio** [comment]
I've run into the same issue, found the exact same line in the code and was just checking issues to help me decide whether it warrants a PR.

I also haven't found any issues with using `close!`, and it would be a useful change - the way it's currently done a long-running process would accumulate tempfiles with no good reason.

**Comment by crespire** [comment]
I never got a response, so I just maintain a fork with this change. I implemented it with a switch parameter so it's easy for folks to decide against the default if they want it.

**Comment by unixmonkey** [comment]
I'd be happy to revert it back to `close!` or use a config option to keep them. I wasn't aware it'd be a problem to let the OS manage cleaning up the tempfiles.
