### ISSUE TITLE
weasy_pdf?

### ISSUE THREAD

**Issue by Nitrodist** [mileszs/wicked_pdf#1047]
## Issue description

wkhtmltopdf is deprecated and unmaintained now. The alternatives listed on their website indicate two options:

> * If you’re using it for report generation (i.e. with HTML you control), also consider using [WeasyPrint](https://weasyprint.org/) or the [commercial tool Prince](https://www.princexml.com/) – note that I’m not affiliated with either project, and do your diligence.

Let's move this code base to a weasy implementation - there is viable code available from the forked pdfkit here: https://github.com/gripapp/weasyprint that we can use as the backend replacement for the wkhtmltopdf binary calls.

## Expected or desired behavior

Backend is reimplemented in weasy

**Comment by unixmonkey** [comment]
https://github.com/mileszs/wicked_pdf/issues/1045
