### ISSUE TITLE
lines between header, template and footer

### ISSUE THREAD

**Issue by seba-hullop** [mileszs/wicked_pdf#1048]
I have a problem in which when I see my pdf in the viewer of my operating system or in slack and I see a white line between what would be the header, the template and the footer.
In my case for production I use background-image but I show it here in the example with background-color so the line looks.

For example:

This is what it looks like in the browser viewer

![image](https://user-images.githubusercontent.com/85506776/215869428-ecb3e5bd-917b-4005-9584-ea33a6a66a77.png)

From what we see in the image, there is no line between the header, the template and the footer. So we are great.

This is how it looks in the pdf viewer of my operating system, in which if I change the zoom the line between the header and template sometimes disappears but in the thumbnails on the left it always appears. And the line between the template and the footer always appears no matter how zoomed it is.

![image](https://user-images.githubusercontent.com/85506776/215869870-c293720d-f90d-428e-ae6b-bcc171cbe88c.png)

![image](https://user-images.githubusercontent.com/85506776/215869917-9999de36-9379-4ffe-a4dc-b6f17b82f737.png)

I don't understand why the line appears with one viewfinder and not in the other viewfinder.
I'm going to pass a bit of code, simply what I do is put the body of the layout the class 'body-background-color' which sets the background color. And I also put a smaller margin for the top and bottom and the header and footer are cut off so they can see that it is not a problem of margins.

I pass a bit of my code so you can see how I set everything up:

method that returns hash with parameters to print pdf:

```
def bic_pdf _organization = nil, *_args
    { pdf: pdf_name,
      template: 'conclusion_reviews/bic_pdf/conclusion_review.html.erb',
      margin: {
        top:    2,
        bottom: 2,
        left:   0,
        right:  0
      },
      header: {
        html: {
          template: 'conclusion_reviews/bic_pdf/header.html.erb'
        }
      },
      footer: {
        html: {
          template: 'conclusion_reviews/bic_pdf/footer.html.erb'
        }
      },
      orientation: 'Landscape',
      layout: 'pdf.html',
      disposition: 'attachment',
      show_as_html: false }
  end

```

header:

```
<div class="row">
  <div class="col-8 offset-4">
    <div class="row">
      <div class="col-3 offset-9">
        <%= 'LOGO 1' %>
        <%= 'LOGO 2' %>
      </div>
    </div>
  </div>
</div>
```

footer:

```
<div class="row">
  <div class="col-1 offset-11">
    <%= t 'wicked_pdf.number_pages_html' %>
  </div>
</div>
```

layout:

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag 'wicked_pdf' %>
    <%= wicked_pdf_javascript_include_tag 'wicked_pdf/number_pages' %>
  </head>
  <body onload="number_pages()" class="body-background-color">
    <%= yield %>
  </body>
</html>
```

scss:

```
.body-background-color {
  background-color: #c25d2e;
}
```

## System specifications

wicked_pdf (2.6.3)

wkhtmltopdf-binary (0.12.6.5)

Ubuntu 20.04.5 LTS

**Comment by unixmonkey** [comment]
I'm sorry, but there just isn't enough here to diagnose or reproduce your issue without actual markup used in the `conclusion_review.html.erb` file, and all CSS. It looks like you are using Bootstrap. What version?

The line to the left that you are pointing out looks like it could be some kind of quoting style. Possibly a print-only style, or a media query style that applies when the viewport is a certain size.

If you can create an example application that also demonstrates this, I can try to help, but this certainly isn't an issue with `wicked_pdf`, or even `wkhtmltopdf_binary`, but likely with the quite old rendering engine used by `wkhtmltopdf` itself.

Please let me know if you figure out anything, or would like me to take a closer look at an updated example.

**Comment by seba-hullop** [comment]
ok great, I open another issue with a simple example without bootstrap and showing you the files
