### ISSUE TITLE
wkhtmltopdf using Linux emulation not starting on FreeBSD

### ISSUE THREAD

**Issue by jcatrysse** [mileszs/wicked_pdf#1052]
On FreeBSD 13 AMD64 I am running `wkhtmltopdf_centos_8_amd64` from the `wkhtmltopdf-binary-0.12.6.6` gem, using the FreeBSD Linux emulator.

This runs fine from a standard shell, but it fails to run from within the Ruby exec() statement.

1. I am using Linux binaries because the FreeBSD builds are broken.
2. It is my understanding that FreeBSD is normally detecting the ELF file type and redirects all necessary files (like linked libraries) to `/compat/linux/...`
3. This seems not to happening when run from within a Ruby `exec()` statement.
4. The execution fails with:
        `/compat/linux/usr/bin/wkhtmltopdf: error while loading shared libraries: /usr/local/lib/libpng16.so.16: ELF file OS ABI invalid`

I unsuccessfully tried to start the command from `/compat/linux/bin/bash -c '/compat/linux/usr/bin/wkhtmltopdf'`

How could I proceed to make Ruby execute this binary in Linux emulation mode?

**Comment by jcatrysse** [comment]
I was able to resolve this by adding `ENV['LD_LIBRARY_PATH'] = '/compat/linux/usr/lib64'` before my `exec()` statement.
This adds the Linux library path to the set of paths used by the dynamic linker `ld-elf.so.1` when searching for shared libraries.

Setting an alternative shell was not useful: `ENV['SHELL'] = '/compat/linux/usr/bin/bash'`.

**Comment by unixmonkey** [comment]
Thanks for documenting your solution. It's been a long time since I used it, but I love FreeBSD.

**Comment by jcatrysse** [comment]
>  ...passing `disable_javascript: true` as wicked_pdf rendering options ... crashes seem to have stopped.

That is correct, the issue is indeed in the JavaScript engine, but we use JavaScript graphs in our PDF's... so we cannot disable it.

What was the error you had with the emulator? I think I needed to play around with the settings:
1. adding this line `ENV['LD_LIBRARY_PATH'] = '/compat/linux/usr/lib64'` before `exec *$*.unshift(binary)before` in `/usr/local/lib/ruby/gems/2.7/gems/wkhtmltopdf-binary-0.12.6.6/bin/wkhtmltopdf`
2. Changing the `shebang` path: `#!/usr/bin/env ruby` to `#!/usr/local/bin/ruby27`

**Comment by jarmo** [comment]
@jcatrysse thanks for asking. There were some dynamically linked libraries missing and I didn't want to spend more time on it than I already had. For me disabling JavaScript was a solution since it was not necessary, but thanks for your additional possible solution for someone else finding this from Google.

**Comment by jcatrysse** [comment]
I remeber now, I hadded to add those libraries manually. Here is my list of files attached.
[linux_libraries_update.tgz](https://github.com/mileszs/wicked_pdf/files/11480619/linux_libraries_update.tgz)
