### ISSUE TITLE
WickedPDF gem issue 

### ISSUE THREAD

**Issue by thechildwholovesyou** [mileszs/wicked_pdf#1065]
[Airbrake] [Production] Missing template spree/api/pages/show_deprecated, spree/api/base/show_deprecated with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :slim, :hbs, :handlebars, :haml, :rabl]...

Issue is with the wickedPDF gem 

can anyone help me out in this to resolve the issue .

**Comment by unixmonkey** [comment]
`formats: [:json]` should include `:pdf` also. Include that in your `render` call like:
```ruby
render pdf: “mypdf”, formats: [:html]
```

See more details in this thread: https://github.com/mileszs/wicked_pdf/issues/1005

**Comment by thechildwholovesyou** [comment]
@unixmonkey 

**earlier** 
if missing_invoices.empty? && invoices.present?
            respond_to do |format|
              format.pdf do
                render pdf: "#{@order.number}_invoices",
                       template: "spree/admin/orders/invoices/#{params[:invoice_format]}",
                       print_media_type: true, no_background: true, no_pdf_compression: false, orientation: "Portrait",
                       encoding: "utf8", locals: { invoices: invoices, invoice_copies: invoice_copies }
              end
            end
          else
          
**changed to** 

if missing_invoices.empty? && invoices.present?
            respond_to do |format|
              format.pdf do
                render pdf: "#{@order.number}_invoices", formats: [:html]
                       template: "spree/admin/orders/invoices/#{params[:invoice_format]}",
                       print_media_type: true, no_background: true, no_pdf_compression: false, orientation: "Portrait",
                       encoding: "utf8", locals: { invoices: invoices, invoice_copies: invoice_copies }
              end
            end
          else
          
Is thsi fine now ?
