### ISSUE TITLE
Gem breaks with Shakapacker v 7.0.

### ISSUE THREAD

**Issue by sdrioux** [mileszs/wicked_pdf#1066]
## Issue description

This gem does not work with the latest version of Shakapacker.  In version 7.0 all usages of "webpacker" was changed to "shakapacker".  As a result, this line results in an error: `cannot load such file -- webpacker/version (LoadError)`.  There may be other name issues hiding behind that one, as this gem refer to the `Webpacker` module in other places, however in this case the version.rb file was moved to `shakapacker/version.rb`

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 2.6.3

Webpacker version 7.0.1

**Comment by unixmonkey** [comment]
This is now in version 2.7.0 of wicked_pdf. Thank you for your help!
