### ISSUE TITLE
Rails 3.2.1, wicked_pdf 0.7.7 => PDF not displaying/generating

### ISSUE THREAD

**Issue by tedlin182** [mileszs/wicked_pdf#107]
I had this all working before I believe on Rails 3.1 and the same version of wicked_pdf, but for some reason now, the PDF doesn't seem to be getting generated.  

Previously when I had it working, it would automatically trigger the file download window prompt, but not just a blank page appears and no file download window appears.  

Not sure if anybody else is having this issue.  Here is my setup in my controller action:

format.pdf do
        render :pdf => "test",
               :template => "invoices/show_grouped_pdf.html.erb",
               :wkhtmltopdf => 'usr/local/bin/wkhtmltopdf',
               :show_as_html => params[:debug].present?,
               :layout => "pdf.html",
               :print_media_type => true,
               :margin => {
                   :top => 30
               },
               :header => {
                   :html => {
                       :template => "application/_header_pdf.html.erb",
                       :layout => 'pdf.html.erb'
                   }
               }
      end

Not sure if I'm missing something.

**Comment by nagrgk** [comment]
di you able to solve the error?

my wikedpdf running foverver and back with error and generated pdf is also empty.

give me suggestion.
