### ISSUE TITLE
wicked_pdf Auto-Print option for Rails 7

### ISSUE THREAD

**Issue by Vicky099** [mileszs/wicked_pdf#1071]
## Issue description
I am trying to auto-print using `system('lpr')` but it is not working for windows machine. haven't checked macos yet. Is there any solution in wicked_pdf present, using that we can auto-print the PDFs.

`system('lpr')` is working on ubuntu.

can anyone help me out in this to resolve the issue 

## Expected or desired behavior
auto print should work on any operating system (Windows/MacOS/Ubuntu)
## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):    `wicked_pdf (2.6.3) wicked_pdf (~> 2.6)`

wkhtmltopdf version (output of `wkhtmltopdf --version`): `wkhtmltopdf 0.12.6.1 (with patched qt)`

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): windows/macos

**Comment by unixmonkey** [comment]
WickedPDF can generate PDF files, but it's up to you how to get those files to print.

Yes, on Linux systems that have `lpr` and a printer setup, you should be able to call `system('lpr', 'path/to/pdf_file.pdf')`, but I'm not aware of anything natively like that for Windows.

I have seen a solution that loads the PDF in an iframe of the browser, and automatically triggers the Windows print dialogue like this:
https://stackoverflow.com/a/26524452/23915

And I've seen where someone created a Windows C# program to print without invoking a dialogue here: https://stackoverflow.com/questions/31896952/how-to-programmatically-print-to-pdf-file-without-prompting-for-filename-in-c-sh

Or perhaps you could setup the Windows machine to install the LPR driver to act like a Linux machine, as documented here:
https://docs.rocketsoftware.com/bundle/wwl1644034744378/page/syr1647367616074.html

But this is not something we can support as part of WickedPDF, so I'm closing this issue. Please let me know if anything works for you though.
