### ISSUE TITLE
tfoot repeating in every page

### ISSUE THREAD

**Issue by rafaeldev** [mileszs/wicked_pdf#1072]
## Issue description
I have a table to list some info where at its final, show a sum of infos. I'm using bootstrap stylish it.

When that table is big, it repeat ffoot info in each page:
![image](https://github.com/mileszs/wicked_pdf/assets/4596160/d625877e-6482-40c6-90f3-efb4e0177d39)

Table structure:
```html
<table class="table table-bordered" id="services">
  <tbody>
  <tr>
    <td rowspan="2" class="text-vertical-align" style="max-width: 50%">
      <small class="d-block text-muted">Item</small>
      Item 1 name
    </td>

    <td>
      <small class="d-block text-muted">Qtde.</small>
      50,0
    </td>
    <td>
      <small class="d-block text-muted">Kind</small>
      Kind name
    </td>
  </tr>
  <tr>
    <td class="nowrap">
      <small class="d-block text-muted">Unit.</small>
      R$ 200,00
    </td>
    <td class="nowrap">
      <small class="d-block text-muted">Subtotal</small>
      R$ 10.000,00
    </td>
  </tr>

  <!-- these sibling tr repeating many times -->

  </tbody>

  <tfoot class="table-borderless table-sm">
  <tr>
    <td colspan="3" class="text-right">
    </td>
  </tr>
  <tr>
    <td colspan="3" class="text-right">
      <span>Subtotal: R$ 13.366,44</span>
    </td>
  </tr>
  <tr>
    <td colspan="3" class="text-right">
      <span>Desconto: R$ 2.004,97</span>
    </td>
  </tr>

  <tr>
    <th colspan="3" class="text-right">
      <span>
        Total: R$ 11.361,47
      </span>
    </th>
  </tr>
  </tfoot>
</table>
```

## Expected or desired behavior
Don't repeat `tfoot` info

## System specifications
```
wicked_pdf (2.7.0)
    wicked_pdf
```

wkhtmltopdf version (output of `wkhtmltopdf --version`):
`wkhtmltopdf 0.12.6.1 (with patched qt)`

**Comment by rafaeldev** [comment]
I found [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3013) with the same problem and a good example to test:

[test.html.txt](https://github.com/mileszs/wicked_pdf/files/12445507/test.html.txt) (remove txt extension)

[test.pdf](https://github.com/mileszs/wicked_pdf/files/12445504/test.pdf)

**Comment by rafaeldev** [comment]
I found [this answer](https://stackoverflow.com/questions/24648383/wkhtmltopdf-repeating-thead-headers-overlapping-content)

Basically, I added this classes to my CSS file:
```css
table { word-break: break-word; }
tr { page-break-inside: avoid !important; }
thead, tfoot {
  display: table-row-group;
}
```

**Comment by zion** [comment]
@rafaeldev Thank you for this solution! Works perfectly! 🍻

**Comment by snjhyrglr** [comment]
How you apply bootstrap to your pdf?
