### ISSUE TITLE
Any HTML added to header or footer turns PDF Blank White

### ISSUE THREAD

**Issue by jeremygradisher** [mileszs/wicked_pdf#1076]
### My controller:
```ruby
def generate_pdf
    # generation logic
    # Assume the PDF content is in variable pdf_content
    pdf_filename = generate_pdf_filename
    
    s3 = Aws::S3::Resource.new(region: ENV['S3_REGION'])
    obj = s3.bucket(ENV['S3_BUCKET_NAME']).object(pdf_filename)
    obj.put(body: render_to_string(
      pdf: pdf_filename,
      template: "blank/_lorem",
      formats: [:html,:pdf],
      layout: "pdf_layout",
      page_size: 'Letter',
      encoding: 'utf8',
      javascript_delay: 600,
      footer: {
          html: {
            template: "blank/pdf_footer"
          }
        }
    ))
  
    # Save a record in the database
    GeneratedPdf.create(user: current_user, s3_key: pdf_filename)
  
    # Provide feedback to the user or redirect
    redirect_to blank_index_path, notice: 'PDF generated successfully!'
  end
```
### So if I use my footer (pdf_footer.html.erb) like this, it all goes blank white:
```ruby
<div class="ajg-pdf-footer" style="width:100%">
    <hr style="clear:both;">
    <%= wicked_pdf_image_tag asset_url('/images/affy-logo-github.png'), width: 50 %>
    <span class="move-right">Page <span class="page"></span> of <span class="topage"></span></span>
</div>
```
Showing blank PDF:
![Screenshot 2023-09-19 at 2 50 21 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/15d50448-30c5-45d4-8e66-15994c6a6669)

### but if I remove all html it generates the PDF just fine (pdf_footer.html.erb):
```
This is the html footer...
```
PDF generated fine:
![Screenshot 2023-09-19 at 2 48 10 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/8dbb8265-0cbb-4460-84ef-1af9edb3c834)

I believe it has something to do with render to string - or the difference between naming the file html.erb or pdf.erb. - Here is a separate example where I can get it to generate the PDF in a simpler way. Notice in this I have to use header and footer files that are formatted with pdf.erb as opposed to html.erb - if I don't it throws a missing template error.

### my controller for simpler generation
```ruby
class TestController < ApplicationController
  def index
    authorize :page, :affygility?
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "pdf-test-#{DateTime.now.strftime('%Y-%m-%d-%H-%M-%S')}", 
        save_to_file: Rails.root.join('public/pdfs', "pdf-test-#{DateTime.now.strftime('%Y-%m-%d-%H-%M-%S')}.pdf"),
        template: "test/index", 
        formats: [:html], 
        layout: "pdf_layout",
        page_size: 'Letter',
        encoding: 'utf8',
        javascript_delay: 600,
        header: {
          html: {
            template: "test/test_header"
          }
        },
        footer: {
            html: {
              template: "test/test_footer"
            }
          }
      end
    end
  end
end
```

### That header and footer were saved as pdf.erb as opposed to html.erb - if I don't it throws a missing template error.
![Screenshot 2023-09-19 at 2 41 40 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/d51f6150-bb37-41fb-b3a9-8dc84299201c)

### Using simpler way from above and saving the header and footer with pdf.erb:
Header and footer show up just fine:
![Screenshot 2023-09-19 at 2 56 52 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/0d2b5dbe-804a-4463-83d0-c8c16aaf8990)
![Screenshot 2023-09-19 at 2 57 03 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/73bf2690-2653-444c-ad3b-397f4a21f41b)

## Ruby on Rails 7 

wicked_pdf gem version (wicked_pdf (2.7.0)):

wkhtmltopdf version (wkhtmltopdf 0.12.6 (with patched qt)):

**Comment by jeremygradisher** [comment]
### I just figure this out - I am going to close the issue. I am keeping the header and footer files with the format pdf.erb and I just needed to add formats: [:pdf] within both the header and the footer.
```ruby
header: {
        html: {
          template: "blank/pdf_header",
          formats: [:pdf]
        }
      },
      footer: {
          html: {
            template: "blank/pdf_footer",
            formats: [:pdf]
          }
        }
```
For reference:
<img width="1084" alt="Screenshot 2023-09-19 at 3 34 43 PM" src="https://github.com/mileszs/wicked_pdf/assets/9622011/270c2b8c-7905-45b0-9f95-1a61bf832985">

**Comment by unixmonkey** [comment]
I'm glad you got this figured out. I really appreciate the detailed report.

Do you think there's somewhere in our README that could benefit from being clearer on file naming or using the `formats` option?
Older Rails versions didn't need the `formats: [:pdf]` thing, and it tripped up a lot of people upgrading to, or starting at Rails 6.1 (I think).

**Comment by jeremygradisher** [comment]
Much respect, I would add it to the README right after the template: 'users/header', line highlighted below:
![Screenshot 2023-09-19 at 8 51 55 PM](https://github.com/mileszs/wicked_pdf/assets/9622011/680a93ef-c1e3-4dc3-bd7a-fcf936771860)

You could have that read something like this:
```
header:  {   html: {            template: 'users/header',          # use :template OR :url
                                          formats: [:pdf],                          # or formats: [:html] 
                                          layout:   'pdf_plain',             # optional, use 'pdf_plain' for a pdf_plain.html.pdf.erb file, defaults to main layout
                                          url:      'www.example.com',
                                          locals:   { foo: @bar }},
```
Potentially doing the same thing to show it in the footer as well.
