### ISSUE TITLE
Can we limit PDF pages?

### ISSUE THREAD

**Issue by Vicky099** [mileszs/wicked_pdf#1077]
Hello All,

I want to generate a PDF with only one page and ignore the rest of the pages. My first page might be override to second page but in that case I want to ignore that second page. Is it possible using Wicked_pdf?

**Comment by unixmonkey** [comment]
You can generate the PDF normally, then pass the PDF file or blob into another tool, like [PDFtk](https://www.pdflabs.com/tools/pdftk-server/) to copy off the first page into another PDF like `pdftk wicked_pdf_multipage.pdf cat 1 output single_page.pdf`.

I think you could also use [Prawn-templates](https://github.com/prawnpdf/prawn-templates/blob/master/lib/prawn/templates.rb#L110) to do this, as I've done something similar in the past, back when templates were part of Prawn core.
