### ISSUE TITLE
PDF is being rendered with raw ERB code

### ISSUE THREAD

**Issue by mchavarriagam** [mileszs/wicked_pdf#1111]
## Issue description

I recently upgraded to Rails 7.0.8.1, Ruby 3.1.4, and while reviewing my site's functionality, I noticed PDFs are being rendered with raw HTML in them. Like this:

![image](https://github.com/mileszs/wicked_pdf/assets/521519/2e4fe6cf-0c33-43b7-a780-ed8ce181aedf)

## Expected or desired behavior

HTML should be rendered in the PDF instead of showing as raw text.

## System specifications

Ubuntu 22.04 (6.5.0-27-generic #28~22.04.1-Ubuntu), running Rails 7.0.8.1, Ruby 3.1.4, wicked_pdf 2.8.0 (also happening in 2.1.0), wkhtmltopdf 0.12.6 (with patched qt).

Not using a provider gem.

I think this issue may be similar to https://github.com/mileszs/wicked_pdf/issues/897 though unfortunately the person that posted the issue never updated their findings/fix.

This was working fine for me before I updated from Rails 5 to Rails 7.

This is the command being sent to wkhtmltopdf in my logs:

```
"/usr/local/bin/wkhtmltopdf", "--enable-forms", "--print-media-type", "--enable-local-file-access", "--header-spacing", "2", "--header-html", "file:////tmp/wicked_header_pdf20240419-207726-ptsrp8.html", "--footer-spacing", "2", "--footer-html", "file:////tmp/wicked_footer_pdf20240419-207726-zrygf0.html", "file:////tmp/wicked_pdf20240419-207726-m0y37w.html", "/tmp/wicked_pdf_generated_file20240419-207726-e0jtrd.pdf"
```

This is my "respond_to" block

```
respond_to do |format|
      format.html { render 'print' }
      format.json { render json: { body: @body } }
      format.pdf do
        render pdf: 'activity',
               file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print.html.erb'),
               layout: 'reader_print', # use 'pdf.html' for a pdf.html.erb file
               extra: '--enable-forms --print-media-type --enable-local-file-access', # directly inserted into the command to wkhtmltopdf
               header: {
                 html: {
                   template: 'active_reader/print_header',
                   file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print_header.pdf.erb'),
                   layout: 'reader_pdf_wrapper',
                   format: 'pdf'
                 },
                 spacing: 2
               },
               footer: {
                 html: {
                   template: 'active_reader/print_footer',
                   file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print_footer.pdf.erb'),
                   layout: 'reader_pdf_wrapper',
                   format: 'pdf'
                 },
                 spacing: 2
               }
      end
    end
```

When I check /tmp/wicked_pdf20240419-207726-m0y37w.html I can see the raw HTML code in there. I assume it's not really a wicked_pdf issue but something that Rails is doing. It doesn't happen on any of my other formats (HTML, CSS, JS, XLS) which is why I figured I'd start here.

Any ideas?

**Comment by unixmonkey** [comment]
It does not appear to me that your issue is related to HTML-escaping, but rather that your ERB templates are not being processed as ERB, but instead as plain-text.

Somewhere between Rails 5 and 7, the renderer changed a bit, where you are no longer supposed to put the file extension in the template string, but instead pass it in a `format: :html` or `formats: [:html]` option.

So, I think you'll be able to fix this by changing:

`file: file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print.html.erb'),`

to

`template: 'active_reader/print', formats: [:html]`

It might also work with `file:`, but I'm not sure if that preprocesses or not. Maybe it did in older Rails versions?

Please let me know how it goes!

**Comment by mchavarriagam** [comment]
Thanks @unixmonkey! 

> It does not appear to me that your issue is related to HTML-escaping, but rather that your ERB templates are not being processed as ERB, but instead as plain-text.

You're right. I didn't manage to change the title of the ticket in time, but that seems to be the case.

> Somewhere between Rails 5 and 7, the renderer changed a bit, where you are no longer supposed to put the file extension in the template string, but instead pass it in a format: :html or formats: [:html] option.

Right again! I remember seeing those deprecation warnings when running my tests. The test passed after I made the changes, but I never checked the contents of the file itself to make sure that the PDF is rendering what's expected, and not just raw ERB code.

> So, I think you'll be able to fix this by changing:
> 
> file: file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print.html.erb'),
> 
> to
> 
> template: 'active_reader/print', formats: [:html]

This is going in the right direction. If I change my "respond_to" block like this:

```
format.pdf do
        render pdf: 'activity',
               # file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print.html.erb'),
               template: 'active_reader/print', formats: [:html],
               layout: 'reader_print', # use 'pdf.html' for a pdf.html.erb file
               extra: '--enable-forms --print-media-type --enable-local-file-access', # directly inserted into the command to wkhtmltopdf
               header: {
                 html: {
                   template: 'active_reader/print_header',
                   file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print_header.pdf.erb'),
                   layout: 'reader_pdf_wrapper',
                   format: 'pdf'
                 },
                 spacing: 2
               },
               footer: {
                 html: {
                   template: 'active_reader/print_footer',
                   file: File.join(Rails.root, 'app', 'views', 'active_reader', 'print_footer.pdf.erb'),
                   layout: 'reader_pdf_wrapper',
                   format: 'pdf'
                 },
                 spacing: 2
               }
      end
```

It renders a blank PDF (without the raw ERB code). Commenting out my "header" and "footer" sections makes the PDF render the HTML & ERB content as expected, but with the header & footer missing (of course).

I tried changing "format: 'pdf" to "formats: [:pdf]" in both sections but that didn't work. Any ideas?

Thanks again for your help!

**Comment by mchavarriagam** [comment]
Duh! Silly me. The footer and header templates are named .pdf.erb. Changing the name to .html.erb and adding the "formats: [:html]" option did the trick.

Thanks again @unixmonkey!

This is my response_to block now:

```
format.pdf do
        render pdf: 'activity',
               template: 'active_reader/print', formats: [:html],
               layout: 'reader_print', # use 'pdf.html' for a pdf.html.erb file
               extra: '--enable-forms --print-media-type --enable-local-file-access',
               header: {
                 html: {
                   template: 'active_reader/print_header', formats: [:html],
                   layout: 'reader_pdf_wrapper'
                 },
                 spacing: 2
               },
               footer: {
                 html: {
                   template: 'active_reader/print_footer', formats: [:html],
                   layout: 'reader_pdf_wrapper'
                 },
                 spacing: 2
               }
      end
```

**Comment by unixmonkey** [comment]
I'm glad you got it figured out. It's definitely one of the more common issues with upgrading.

By the way, you can also now specify `print_media_type: true, enable_local_file_access: true` in your call as separate options, or put them in `config/initializers/wicked_pdf.rb` as global configuration instead of in the `extra:` config key.
