### ISSUE TITLE
wicked_pdf due to wkhtmltopdf not finding OpenSSL 1.1 despite installing over OpenSSL 3

### ISSUE THREAD

**Issue by AndyObtiva** [mileszs/wicked_pdf#1114]
## Issue description

After we upgraded our Rails 7 app to Ruby 3.1 and OpenSSL 3 in our build server, we are having an issue when using our Rails app to generate a PDF where `wicked_pdf` somehow fails due to expecting OpenSSL 1.1.

```
RuntimeError Failed to execute:
["/usr/bin/wkhtmltopdf", "--orientation", "Portrait", "--page-size", "Letter", "--margin-top", "45", "--header-html", "file:////tmp/wicked_header_pdf20240416-1-cz41ln.html", "file:////tmp/wicked_pdf20240416-1-g5no29.html", "/tmp/wicked_pdf_generated_file20240416-1-8tyx4w.pdf"]
Error: PDF could not be generated!
 Command Error: pid 49 exit 127
Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/bin/wkhtmltopdf)
Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /usr/bin/wkhtmltopdf)
```

We are installing `wkhtmltopdf` as a prerequisite from a Docker image (`madnight/docker-alpine-wkhtmltopdf`). 

## Expected or desired behavior

We expect `wicked_pdf` to work normally with our Docker image that has OpenSSL3 and Ruby 3.1 instead of OpenSSL 1.1 and Ruby 2.7

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

```
    wicked_pdf (2.7.0)
  wicked_pdf (~> 2.6, >= 2.6.3)
```

wkhtmltopdf version (output of `wkhtmltopdf --version`):

Version `0.12.5`, which comes with the Docker image `madnight/docker-alpine-wkhtmltopdf`

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

We don't use `wkhtmltopdf-binary`. 

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

Alpine Linux: `ruby:3.1-alpine`

--

We just tried relying on `wkhtmltopdf-binary` instead of the `wkhtmltopdf` library in the Docker image to fix the issue and our web server kept crashing upon accessing PDF URLs that use `wicked_pdf`.

Is there a way to make `wicked_pdf` work with OpenSSL3 using `wkhtmltopdf`? If not, can `wicked_pdf` work with an alternative low-level PDF library that is compatible with OpenSSL 3, like puppeteer perhaps?

**Comment by kimesf** [comment]
Seems related with https://github.com/zakird/wkhtmltopdf_binary_gem/issues/162

**Comment by aarestad** [comment]
We are hitting this too, using the `ruby:3.3.1` Docker image (aka `[3.3.1-bookworm](https://github.com/docker-library/ruby/blob/53646d3dc96008bd20218a4d9aeb5695619fb4f7/3.3/bookworm/Dockerfile)`). I found a related issue on [StackOverflow](https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory) and think I'll try the recommended path of grabbing `libssl` manually.

**Comment by kimesf** [comment]
You have to use the binary built against Debian `bookworm`.

`wkhtmltopdf_binary` gem still don't support it (see https://github.com/zakird/wkhtmltopdf_binary_gem/issues/162).

The package can be downloaded from Github (see https://github.com/wkhtmltopdf/packaging/issues/155).

**Get the binary from the package** and setup the project to use it with something like this:

```ruby
# config/initializers/wicked_pdf.rb
WickedPdf.config = {
  exe_path: Rails.root.join("bin", "wkhtmltopdf-amd64").to_s, # or wherever you put it
  enable_local_file_access: true
}
```

**Comment by patricksimpson** [comment]
Hit this issue as well. We we're able to install the `libssl` manually and get past it.  

Added after some other installs...

```
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
RUN dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
```

**Comment by patricksimpson** [comment]
Also changing our base to `FROM ruby:3.3.1-bullseye` works for us.

**Comment by kimesf** [comment]
`wkhtmltopdf_binary` is now supporting Debian 12 on `0.12.6.7` :tada:

I think this can be closed btw

**Comment by AndyObtiva** [comment]
My OS is Alpine Linux (`ruby:3.1-alpine` as mentioned in the issue description body), not Debian 12. But, we have a workaround that is good enough for now. If we decide to do an upgrade in the future, I will let you know if `wkhtmltopdf_binary` would not work. 

Thank you.

**Comment by fzcalebleung** [comment]
@AndyObtiva hello there - curious to know what your eventual workaround was?

**Comment by kimesf** [comment]
@fzcalebleung maybe check https://github.com/Surnet/docker-wkhtmltopdf for an alternative to Alpine

**Comment by kimesf** [comment]
@fzcalebleung Maybe you can check https://github.com/Surnet/docker-wkhtmltopdf for an alternative to build wkhtmltopdf on Alpine.
