### ISSUE TITLE
Slow load

### ISSUE THREAD

**Issue by bcackerman** [mileszs/wicked_pdf#112]
My pdf generation process takes about 10 seconds.  How can I speed this up?  Because in Heroku it times out.  

I'm pulling css and a few images into the pdf fyi.

**Comment by HuzaifaSaifuddin** [comment]
Nothing has worked for me so far...wicked_pdf takes almost 3 seconds to just load an empty pdf view...Is there no way around?? Please help it chokes my server if multiple print requests are placed

**Comment by unixmonkey** [comment]
@HuzaifaSaifuddin WickedPDF isn't exactly fast, it has to pre-render your html, the pass it to the `wkhtmltopdf` binary, which boots up a headless webkit browser that essentially paints your HTML and JS to the screen and does a "print to pdf" back to a tempfile which gets re-read and sent to the browser. On my dev machine (touchbar Macbook Pro), it takes about 2 seconds to render this:
```ruby
WickedPdf.new.pdf_from_string('<doctype html><html><head><title>Hello</title></head><body><h1>Hello</h1></body></html>')
```

If performance is a primary concern, you may want to try either rendering your PDFs in a background job, and delivering them via email, or evaluate switching to [Princely](https://github.com/mbleigh/princely), which uses [PrinceXML](https://www.princexml.com/) as it's HTML-to-PDF engine. Be aware Princely is quite costly, but could be worth it for your business.

Other than that, [Prawn](http://prawnpdf.org/) is much more performant, and gives you a high degree of control over authoring your documents, but you cannot use HTML, CSS, & Javascript to build them. I suggest giving that a look.
