### ISSUE TITLE
Bolding Bugs

### ISSUE THREAD

**Issue by beroneblitz** [mileszs/wicked_pdf#1130]
## Issue description
There are issues with bolding, essentially sometimes the tags don't close and the gem will bold everything after the bold tag opens within the pdf file.

## Expected or desired behavior
You should be able to wrap text within <b> or <strong> </strong> </b> and it will bold just the text within those tags.

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by unixmonkey** [comment]
This is an issue with wkhtmltopdf, not WickedPDF.
