### ISSUE TITLE
PDF and HTML look different with Letter Spacing.

### ISSUE THREAD

**Issue by dwickwire** [mileszs/wicked_pdf#130]
Hello,

Using both 0.79 and 0.7.2 the PDF generated looks slightly different than my original HTML.  Adding the show_as_html flag presents it as expected however the inline-styles are being handled differently in the PDF then they are in the HTML preview.

Specifically the problem I'm having is with letter-spacing declarations which also have a float not being rendered correctly.  So for instance on a right float element which has the letter-spacing, the PDF will space the characters too much and from center such that the text goes partially off the screen rather than bumping further to left for the difference of the letter-spacing width.

Here is the original HTML snippet:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  </head>
  <body>
     <div class="page-break fact-sheet">

    <table width="800" border="0">

      <tr>
        <td colspan="3"><span style="font-family:Helvetica, Arial, sans-serif;font-size:10pt;margin-top:18px;text-transform:uppercase;float: right;letter-spacing:2pt">Winter 2013</span></td>
      </tr>
    </table>

</div>
  </body>
</html>
```

Here is the code doing the rendering:

```
      render :pdf => 'file_name',
             :template => 'template.html.erb',
             :layout => 'pdf.html'
```

Here is the rendered HTML: http://jsfiddle.net/wX4DQ/

Here is the outputted PDF: http://imgur.com/sdUPM
Any suggestions as to what do here?

**Comment by joshuapinter** [comment]
I found the same thing happen when I was printing my PDFs. I tried a few things first, like alter the DPI and use a custom font but none of that worked. 

What did work was updating `wkhtmltopdf`to the latest version (0.12.2.1 at the time of writing) by using the edge binary gem: 

```ruby
gem 'wkhtmltopdf-binary-edge'
```

Hope this helps others.

**Comment by ehutzelman** [comment]
Thanks @joshuapinter that fixed it for me as well! Output looks so much better now.

**Comment by joshuapinter** [comment]
@ehutzelman :+1:

**Comment by aguynamedben** [comment]
@joshuapinter Ran across the same issue going through the README for the first time, and the same fix worked well.

Thanks for working on this fantastic library, it's working great!

**Comment by suhailgupta03** [comment]
Working with 0.12.3.2 but the issue persists  @joshuapinter

**Comment by joshuapinter** [comment]
@suhailgupta03 Then you might have a different problem. If you find out what it is, make sure to post back here to help others.

**Comment by sharpdot** [comment]
same problem here. using version 0.12.3 (with patched qt)

**Comment by vyagudin** [comment]
I also have issue with letter-spacing in pdf output. 
wkhtmltopdf 0.12.3 (with patched qt)

**Comment by BDhara** [comment]
Also have same problem in 0.12.4.. did anyone has a solution for this?

**Comment by maurice-does-software** [comment]
I have the same problem with 0.12.3. It appears to be rounding whatever letter-spacing value I give to the nearest pixel, but I need a letter spacing to be -0.6px.

**Comment by danielbellmas** [comment]
Setting a `letter-spacing: 0.2px` on the `body` tag, kind of worked for me but it's not ideal.
