### ISSUE TITLE
Need help with fitting in images in one page

### ISSUE THREAD

**Issue by surabhisahay** [mileszs/wicked_pdf#133]
I am using wicked_pdf to generate PDF in my Rails(3.0) application. Everything is working just fine with a small glitch. I have a looping of dynamic sized data (say comments and images) which are sequentially arranged.The images have a frame into which they are placed. I need to move the framed image to next page if does not fit in the space on the current page. Currently what is happening is the end part of the frame moves to the next page if doesn't fit.

**Comment by Leprosy** [comment]
I have an img surrounded by divs, I'm applying `page-break-inside: avoid` to the `divs` instead of the `img` tag but to no avail...using wkhtmltopdf 0.12.2.1 (with patched qt).

**Comment by henritrees** [comment]
For me, the pictures which were full width of the page (and smaller in height than the page) did break onto new pages with this css, but when an image was extreme portrait and not 100% of width, it did not break and was forced onto many pages. Setting the `max-height` for the `img` and initial `width` for the surrounding div in `mm` helped.

```
<div style="width:209mm;page-break-before:auto;page-break-inside:avoid;">
    <div>
        <img style="max-width:100%;max-height:280mm;"/>
    </div>
    <div>
        <span>title</span>
    </div>
</div>
```

**Comment by Crx4** [comment]
I experienced that @unixmonkey 's solution does not work, when installing the library via composer.
