### ISSUE TITLE
pass progress information (feature request)

### ISSUE THREAD

**Issue by matzke** [mileszs/wicked_pdf#144]
Is there a possibility to pass progress information back to the user?

**Comment by gregblass** [comment]
Interested in this too @Figedi!

**Comment by gregblass** [comment]
I think even a way to just pop up a loading modal with javascript, even without real progress (just a spinner) would be great.

I think if it wasn't in another tab it'd be trivial...just show the loader and then visit the controller action to generate the PDF.

Ideally I'd like to show the loader and then open the PDF in another tab though...but that will open the tab immediately.
