### ISSUE TITLE
Doesnot support unicode on all machines

### ISSUE THREAD

**Issue by Anoop1989** [mileszs/wicked_pdf#154]
I tried using wicked pdf on development machine, It works fine. But on remote server, wicked_pdf is not able to convert html with unicode characters to pdf(some junk characters like box is displayed)

**Comment by cesc1989** [comment]
This is very old but still does the job 😅 

Some `&ldquo;` where displaying like 💩 . Adding the 

```
<meta http-equiv='content-type' content='text/html; charset=utf-8' /> 
```

Fixed it.
