### ISSUE TITLE
wkhtmltopdf's --forms option for pdf form fields

### ISSUE THREAD

**Issue by rvrm** [mileszs/wicked_pdf#160]
Is there a way to use the --forms option which wkhtmltopdf provides to turn HTML form fields into pdf form fields?

_Update:_ Nowadays it's called **--enable-forms**. My bad!

**Comment by unixmonkey** [comment]
@rvrm @micksabox If you are looking for a good first contribution, you could add this option somewhere around [here](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L290) (and the README, of course).

**Comment by richardrails** [comment]
select tags, check boxes and radio buttons does not work. It is read only. How can I activate them?
