### ISSUE TITLE
Header and footer not showing up

### ISSUE THREAD

**Issue by EnriqueVidal** [mileszs/wicked_pdf#181]
I've been trying to follow https://github.com/mileszs/wicked_pdf/wiki/Background-PDF-creation-via-delayed_job-gem

And the PDF get's generated, but not the footer or the header, this is how I'm doing it:

``` ruby
pdf_html = view.render :template => 'dashboard/archives/one_page', :layout => 'layouts/archive_pdf.html.haml',
    :locals => { :application => application },
    :header   => { :html => { :template => 'dashboard/archives/header' } },
    :footer   => { :right => 'Page [page] of [topage]' }

doc_pdf = WickedPdf.new.pdf_from_string pdf_html, :page_size => 'Letter'
```

`view` is an instance of `ActionView::Base` and it has the `view_paths` set just like that wiki page, yet the footer and header  are not present in the resulting PDF and there is no error shown.

Please advise

**Comment by kendallmiyakawa** [comment]
Over 10 years later - this thread saved me!  I was trying to render html with an `image_tag` in the header, which was causing a footer similar to `{ :right   => 'Page [page] of [topage]' }` not to show up.  Setting `margin: { top: 10 }` in addition to the `header` and `footer` did the trick!
