### ISSUE TITLE
Failed to execute /opt/wkhtmltopdf: Broken pipe 

### ISSUE THREAD

**Issue by hanishj** [mileszs/wicked_pdf#184]
Failed to execute /opt/wkhtmltopdf: Broken pipe

```
Application Trace | Framework Trace | Full Trace
/home/ais/vendor/plugins/wicked_pdf/lib/nix_pdf_renderer.rb:16:in `pdf_from_string'
/home/ais/vendor/plugins/wicked_pdf/lib/pdf_helper.rb:54:in `make_pdf'
/home/aiss/vendor/plugins/wicked_pdf/lib/pdf_helper.rb:65:in `make_and_send_pdf'
/home/ais/vendor/plugins/wicked_pdf/lib/pdf_helper.rb:17:in `render'
/home/ais/app/controllers/student_controller.rb:543:in `profile_pdf'
```

MY WICKED_PDF.RB

```
WickedPdf.config = {
    :wkhtmltopdf => '/opt/wkhtmltopdf',
    :layout => "pdf.html",
    :margin => {    :top=> 40,
                :bottom => 20,
                :left=> 30,
                :right => 30},
    :header => {:html => { :template=> 'layouts/pdf_header.html'}},
    :footer => {:html => { :template=> 'layouts/pdf_footer.html'}},
    #:exe_path => '/usr/bin/wkhtmltopdf'
}
```

I have placed wkhtmltopdf and wkhtmltopdf-i386 in my opt folder also .

When I try to google it . I did not get any helpful info.Kindly help me

**Comment by matrinox** [comment]
@unixmonkey trailing commas in Ruby are not invalid, just style preference.

I'm also getting this error, but in different environments (not using WickedPdf, using PdfKit, but I'm sure it's a wkhtmltopdf issue, thought I'd post this in as many places as possible, in case someone knows the answer). Here's what I did:

I added a footer: `[page] of [toPage]`. The text is basically `hello world`. No other special properties.

The result:

```
The switch --print-media-type, is not support using unpatched qt, and will be ignored.The switch --footer-right, is not support using unpatched qt, and will be ignored.The switch --footer-font-size, is not support using unpatched qt, and will be ignored.libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/xorg/modules/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/xorg/modules/dri)
Error: This version of wkhtmltopdf is build against an unpatched version of QT, and does not support more then one input document.
Exit with code 1, due to unknown error.
```

Similar results as this guy except he used foot html.

**Comment by unixmonkey** [comment]
@matrinox In early 2013, when this issue was opened, Ruby 1.8 was still very common (and probably what I was using at the time), which would throw a syntax error for a trailing comma. I'm not sure if that also affected 1.9 or not. You are correct that it is no longer an issue.

The error message you posted tells you that you are using options that aren't supported with a minimalist build of `wkhtmltopdf`. You are encouraged to find a distribution that was built against a patched QT, or build it yourself.

**Comment by matrinox** [comment]
Thanks, patched QT did the trick
