### ISSUE TITLE
Header and footer covering part of the content

### ISSUE THREAD

**Issue by jalerson** [mileszs/wicked_pdf#185]
Hello people!

I'm having some problems using headers and footers: the header/footer is covering parte of the content at the page break.

The first page works fine, but the second page onwards, this problem occurs.

![second-page](https://f.cloud.github.com/assets/583500/111731/91362c08-6b00-11e2-82b7-cf6d29204478.png)

![third-page](https://f.cloud.github.com/assets/583500/111732/94d1860a-6b00-11e2-9568-8749c73dc01c.png)

My WickedPdf initializer:

``` ruby
WickedPdf.config = {
  :layout => 'layout',
  :margin => {
    :top => 38,
    :bottom => 25
  }
}
```

My controller:

``` ruby
format.pdf do
        render :pdf => 'consulta',
               :header => {
                  :html => {
                     :template => 'layouts/pdf-header.html'
                  }
               },
               :footer => {
                  :html => {
                     :template => 'layouts/pdf-footer.html'
                  }
               }
      end
```

Is there any way to fix this?

Thanks a lot!

**Comment by aldrienht** [comment]
I'm having trouble fixing the page break.
I'm using table to iterate the data, but when it gets to another page...the breaking of data happens.

please see my question in stackoverflow [http://stackoverflow.com/questions/38323519/wicked-pdf-unable-to-handle-page-break](url)


here is the sample error.
![wicked](https://cloud.githubusercontent.com/assets/10846020/16760225/b370473c-4855-11e6-9074-50d9faed8a72.png)

**Comment by unixmonkey** [comment]
I've added an answer to the StackOverflow post, but for posterity here:

I've gotten around this issue in the past by wrapping each table row in a div with the css page-break-inside: avoid;.

I know it isn't semantically correct, but it works.

That should ensure it transitions pages without cutting off table content in the middle of a row:

```html
<style>
  .nobreak:before {
    clear: both;
  }
  .nobreak {
    page-break-inside: avoid;
  }
</style>
<table>
  <div class="nobreak">
    <tr>
      <td>First row</td>
    </tr>
  </div>
  <div class="nobreak">
    <tr>
      <td>Second row</td>
    </tr>
  </div>
</table>
```

**Comment by cesc1989** [comment]
@jalerson tweaking header's spacing and content's margin top I could solve this. Saved my day :D

**Comment by JoaoSeger** [comment]
@unixmonkey I'm not achieving use the margin bottom in footer ? Do you have one example ?
