### ISSUE TITLE
wicked_pdf_stylesheet_link_tag problem on production.

### ISSUE THREAD

**Issue by lafeber** [mileszs/wicked_pdf#188]
In my code I have 

```
<%= wicked_pdf_stylesheet_link_tag "admin/bootstrap_print" -%>
```

Everything works fine in development, but in production I get the error:

ActionView::Template::Error (No such file or directory - /assets/admin/bootstrap_print-6febc03c8e3adc61b770e6c7471ae248.css):

The file is compiled and is there, though... I'm really puzzled.
It must have something to do with the asses pipeline? I use wicked_pdf gem version 0.9.2

Thanks in advance for any help!

**Comment by dimmg** [comment]
@brunzino that did the trick for me, excepting that now it should be added to `initializers/assets` as with the rails update.
