### ISSUE TITLE
WickedPDF Email attachment not rendering correctly 

### ISSUE THREAD

**Issue by davidpatters0n** [mileszs/wicked_pdf#203]
I am trying to send a PDF as an attachment. My set up appears to be slightly working because I am getting an email however the output of this email is not the prettiest. 

Mailer:

```
class OvertimeMailer < ActionMailer::Base

  default :from => DEFAULT_FROM

  def overtime_pdf(user, hospital_booking)
    @hospital_bookings = hospital_booking
    @user = user
    attachments["hospital_bookings.pdf"] = WickedPdf.new.pdf_from_string(
      render_to_string(:pdf => "overtime",:template => 'hospital_bookings/index.pdf.erb', :layouts => "pdf.html")
    )
    #self.instance_variable_set(:@lookup_context, nil)
    mail :subject => "Overtime", :to => user.email
  end
end
```
## Email Output:

Date: Fri, 22 Mar 2013 13:33:28 +0000
Mime-Version: 1.0
Content-Type: application/pdf;
charset=UTF-8;
filename=hospital_bookings.pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
filename=hospital_bookings.pdf
Content-ID: 514c5da86b3e2_9c812a0ffc235c2@dj-VirtualBox.mail

JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7/KQovQ3JlYXRvciAo/v8p
Ci9Qcm9kdWNlciAo/v8AdwBrAGgAdABtAGwAdABvAHAAZABmKQovQ3JlYXRp
b25EYXRlIChEOjIwMTMwMzIyMTMzMzI4WikKPj4KZW5kb2JqCjMgMCBvYmoK
PDwKL1R5cGUgL0V4dEdTdGF0ZQovU0EgdHJ1ZQovU00gMC4wMgovY2EgMS4w
Ci9DQSAxLjAKL0FJUyBmYWxzZQovU01hc2sgL05vbmU+PgplbmRvYmoKNCAw
....more binary blob

What precisely is causing this?

**Comment by A1iAshoor** [comment]
+1 @unixmonkey thanks for the help, I spent hours and hours trying to solve this..
