### ISSUE TITLE
What is the correct way to enable external links

### ISSUE THREAD

**Issue by willmcclellan** [mileszs/wicked_pdf#217]
I'm using Wicked PDF to convert a html string to a pdf:

```
WickedPdf.new.pdf_from_string(html, WickedPdf.config)
```

And in my initializer I'm setting my options such as:

```
:exe_path => 'path/to/local/binary'
:temp_path => File.join(Rails.root, "tmp"),
:disable_external_links => false,
:page_size => 'A4'
```

I'm trying to enable links contained within the html so they can be clicked in the PDF but can't get it to work. The links are there but they don't go anywhere (they get rendered as blank links in the PDF).

I've tried a combination of :disable_external_links and :enable_external_links each on their own and together with true/false as the value but they don't work.

I took the generated html and saved it to a file locally and used wkhtmltopdf from the command line to convert and that generated the PDF with links correctly.

I'm wondering if it's pdf_from_string that's causing the problem (instead of using a file). Are there some other options that wickedpdf uses that could be interfering with the links?

**Comment by joshuapinter** [comment]
@willmcclellan So what was your final wicked_pdf configuration you needed to do in order to enable external links?
