### ISSUE TITLE
Repeat thead of a table in all pages

### ISSUE THREAD

**Issue by cyruscavalcante** [mileszs/wicked_pdf#242]
I try   put thead {display: table-header-group;} in css but does not work

**Comment by btrscott** [comment]
+1

Might be time to put something into implementing this.  Sorry I'm not personally skilled to do it and do a pr

**Comment by marcelo-rebello** [comment]
To this works (relatively well, some issues with blank lines) you need the table element with:
 {position: relative} style 
and then the tr element must have this class:

      .nobreak:before {
        clear: both;
      }
      .nobreak {
        page-break-inside: avoid;
      }
