### ISSUE TITLE
Problem with header option

### ISSUE THREAD

**Issue by arturmalecki** [mileszs/wicked_pdf#25]
Hi!

When I'm using header option:

```
:header => {:html => { :template => 'sites/header.pdf.haml'}}
```

i got:

```
uninitialized constant PdfHelper::WickedPdfTempfile
```

**Comment by besi** [comment]
This worked for me (However, I did not get an error just that the header was not there):

Instead of:

    options = {
        header: {html: {template: 'shared/_header', layout: nil}},
    }

I did use this:

    options = {
        header: {content: render_to_string('shared/_header', layout: nil)},
    }
