### ISSUE TITLE
Wicked PDF doesnt render text

### ISSUE THREAD

**Issue by sarsena** [mileszs/wicked_pdf#250]
I have an app I am creating that creates a packing slip.  When I go to my/pathto/invoice.pdf It generates the images and background colors and the format but none of the text is actually shown.  I dont know if I'm missing something.  Its probably some step I overlooked but any help or suggestions would be greatly appreciated.  Thanks!

**Comment by thisisole** [comment]
Are there any new, cool solutions? Tried everything but cant get wicked_pdf to work with my fonts. Tried also base64... 

Or is there somewhere an example how to do this exactly? (including css files etc.)

**Comment by unixmonkey** [comment]
@thisisole Did you try converting your font to .otf? I know there are some formats that `wkhtmltopdf` can't work with.

The example I posted above, I actually tried before posting.

**Comment by thisisole** [comment]
thanks, having an ttf... will try to convert it to otf and come back then.

another question: i have to implement the font with: wicked_pdf_stylesheet_link_tag, correct?

**Comment by unixmonkey** [comment]
@thisisole No, but I would recommend it. You can use regular stylesheet_link_tag if you like, but the `wicked_pdf_` one inlines the CSS, so it's one less thing that `wkhtmltopdf` needs to go out and download, but there are cases where you'd want to use the regular ones (like precompiling with the asset pipeline).

**Comment by thisisole** [comment]
YAY!!! its working with the asset_data_base64 function... man... what a fight... costs me 3 days... thx for help.

**Comment by danieljacobarcher** [comment]
I can't get it working with .otf or .ttf, and I've tried converting to base64 as well... Any other solutions?

Font displays perfectly in html (debug=true), but not in render PDF...

**Comment by unixmonkey** [comment]
@danieljacobarcher Can you post the relevant bits from your code (and the font if legal to do so)?
If it isn't you can email me: dave @unixmonkey dot net and I'll delete after getting it working.

**Comment by danieljacobarcher** [comment]
@unixmonkey Totally. I'm just using Google Web Fonts Roboto.

````
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Regular.ttf') %>");
	font-weight: normal;
	font-style: normal;
}
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Medium.ttf') %>");
	font-weight: 500;
	font-style: normal;
}
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Bold.ttf') %>");
	font-weight: 700;
	font-style: normal;
}
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Black.ttf') %>");
	font-weight: 900;
	font-style: normal;
}
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Light.ttf') %>");
	font-weight: 300;
	font-style: normal;
}
@font-face {
	font-family: "Roboto";
	src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Thin.ttf') %>");
	font-weight: 100;
	font-style: normal;
}

**Comment by unixmonkey** [comment]
I was able to get this working locally and pushed it up to https://github.com/unixmonkey/wicked_pdf_issues

in this commit: https://github.com/unixmonkey/wicked_pdf_issues/commit/386aba4e6007c776abb8136f590cb63ecc571e87

You can see it online at https://wicked-pdf-issues.herokuapp.com/pages/issue_250

I added a second font "Poiret One" because at first I was having trouble telling Roboto from the normal body font, but then I realized that Roboto's TTF just wasn't working for me in PDF, so I ran a few of them through https://everythingfonts.com/ttf-to-otf, and they were working. I guess some fonts just work differently from others?

Let me know how it goes.

**Comment by danieljacobarcher** [comment]
@unixmonkey Thanks for checking it out and sharing some example code. I finally figured it out - that it needs the assets precompiled for wkhtmltopdf to pick them up. Somehow I missed that in the documentation..

**Comment by henry-p** [comment]
For anyone having trouble with sprockets > 3.0, here is an improved version of the asset_data_base64 helper.
```
def asset_data_base64(path)
    asset = (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset(path)
    throw "Could not find asset '#{path}'" if asset.nil?
    base64 = Base64.encode64(asset.to_s).gsub(/\s+/, "")
    "data:#{asset.content_type};base64,#{Rack::Utils.escape(base64)}"
 end
```

**Comment by katebeavis** [comment]
I tried everything, spent a day trying to figure it out, encoding in base64 etc. Turns out simply converting from ttf to otf got it to work for me! Hope this helps somebody....

**Comment by unixmonkey** [comment]
@henry-p Can you open a new PR or issue describing what trouble you are having, and your revised code?

**Comment by aivils** [comment]
Nowadays we have helper asset_data_uri() and in the scss asset-data-url()
After updrade to rails5 fonts in PDF disappears. Both methods above helps to restore PDF.

**Comment by deeparajen** [comment]
> @unixmonkey Totally. I'm just using Google Web Fonts Roboto.
> 
> ```
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Regular.ttf') %>");
>     font-weight: normal;
>     font-style: normal;
> }
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Medium.ttf') %>");
>     font-weight: 500;
>     font-style: normal;
> }
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Bold.ttf') %>");
>     font-weight: 700;
>     font-style: normal;
> }
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Black.ttf') %>");
>     font-weight: 900;
>     font-style: normal;
> }
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Light.ttf') %>");
>     font-weight: 300;
>     font-style: normal;
> }
> @font-face {
>     font-family: "Roboto";
>     src:url("<%= ApplicationHelper.asset_data_base64('Roboto/Roboto-Thin.ttf') %>");
>     font-weight: 100;
>     font-style: normal;
> }
> ```

I had implemented on the same way but oops not working.  Wicked_pdf doesn't support roboto font-family

layouts/pdf.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
		<meta name="description" content="">
		<title>Aurora</title>
		<%= wicked_pdf_stylesheet_link_tag "application" %>
		<%= wicked_pdf_stylesheet_link_tag "pdf" %>
	</head>
	<body class="fixed-nav top-nav">

		<div class="content-wrapper">
			<div class="box-container">
				<div class="container-fluid">
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>

pdf.css.scss
@font-face {
    font-family: "Roboto Regular";
    src:url("<%= ApplicationHelper.asset_data_base64('roboto/Roboto-Regular.ttf') %>");
    font-weight: 300px;
    font-style: normal;
}
@font-face {
    font-family: "Roboto";
    src:url("<%= ApplicationHelper.asset_data_base64('roboto/Roboto-Bold.ttf') %>");
    font-weight: 700;
    font-style: normal;
}

controller
  def report_generation
    respond_to do |format|
      format.html
      
      format.pdf do
        render :pdf => "report_generation",
              :template => 'dashboard/report_generation.html.erb',
              :layout => 'layouts/pdf.html.erb',
              :save_to_file => Rails.root.join('pdfs', 'report_generation.pdf'),
              :disposition => "attachment"
      end
    end
  end

Can anyone help me to fix this issue.

**Comment by mostafasobh** [comment]
what i have now is:
`@font-face {
  font-family: 'Roboto';
  src: url('http://fonts.googleapis.com/css?family=Roboto') format('woff2');
  font-weight: normal;
  font-style: normal;
} `
adding ` format('woff2')` fixed the issue for me
