### ISSUE TITLE
clarification on usage with asset pipeline?

### ISSUE THREAD

**Issue by peashutop** [mileszs/wicked_pdf#257]
Hi, I'm trying to figure out the best way to handle references to stylesheets when using wicked_pdf with a generic Rails 4 app.

The README says "the best option for Rails _without_ the asset pipeline" is to use the wicked_pdf_stylesheet_link_tag, which will generate absolute links.

There's a brief mention of usage with the asset pipeline, but it doesn't provide the detail I'm looking for. How would adding pdf.css to the config.assets.precompile list help with the absolute links issue? Do I need to tweak some setting, e.g. config.action_controller.asset_host?

Thanks!

**Comment by allaire** [comment]
@unixmonkey Starting a new project and was still confused with the README. Can I PR a README that will remove any reference to assets pipeline, except the note that you need to add to your precompile array any .css or javascript that you create outside application.css and application.js (like anything in Rails).

I think this would remove any confusion and make it clear that assets pipeline or not, you need to use the wicked_pdf helpers.

Thanks!

**Comment by unixmonkey** [comment]
@allaire 
I'm not sure exactly what you are proposing, but it would be great if you could contribute! The README *has* gotten a little confusing over time, with all the changes in the asset pipline in each new version of Rails, and new/discontinued options available to `wkhtmltopdf`.

What's even better, is if you could also work in something about usage with the `wicked_pdf_asset_base64` helper, [which was recently introduced](https://github.com/mileszs/wicked_pdf/commit/144991778dbbdc459790409aaeea4bc68ba5e543), but is not yet documented in the README. I think this may be the better option for many people, since it embeds the document, instead of accessing through a `file://` interface (and may help with your usage, too).

You can use it like this:
```erb
<%= stylesheet_link_tag(wicked_pdf_asset_base64('pdf.css')) %>
<%= javascript_include_tag(wicked_pdf_asset_base64('somefile.js')) %>
<%= image_tag(wicked_pdf_asset_base64('foo.png')) %>
```

**Comment by allaire** [comment]
@unixmonkey then should we rewrite every wicked helper using `wicked_pdf_asset_base64` ?

AFAIK, we can't  use `stylesheet_link_tag`, `javascript_include_tag` and `image_tag` directly, assets pipeline or not, and that's what I find unclear in the README. I think we should make it clear that wicked_* helpers must be used no matter what, and add a special note about precompile array.

**Comment by unixmonkey** [comment]
@allaire I don't think it's a good idea to do that *yet*, as it hasn't been out there long enough to work out the kinks. For instance, right now it will only work with assets that can be found with `find_asset`. I'd like it to also work with `/public` assets and/or CDN assets.

It would also be a backwards-incompatible change, warranting a new major version bump.

Also, it isn't true that the helpers must be used no matter what. Many people have no issues with the regular helpers (but they do slow down PDF generation), and slightly older versions of Rails don't require adding things to the precompile array.

Again, this can probably be made clearer in the README, so your help would definitely be appreciated.

**Comment by allaire** [comment]
@unixmonkey Are you aware of the Rails versions that work with regular asset helpers? I can't get anything to work with Rails 4.

**Comment by unixmonkey** [comment]
1, 2, 3.

I'm not sure if they stopped working in the general case in 3.2 or 4.0. It's also possible that updates made to the asset helpers in this gem had broken backwards compatibility in some way, but there are other ways to use the regular Rails helpers that should be OK.

Aside from fingerprinted assets, you may also be running a version of `wkhtmltopdf` that won't load assets over https (on most networks), since that version relied on SSLv3. Make sure you are running a recent version of `wkhtmltopdf`.

**Comment by allaire** [comment]
@unixmonkey Yeah I'm running latest version so no issue here :)

So to recap, how can I usefully contribute to make the whole thing clearer?

**Comment by unixmonkey** [comment]
A PR to the README with a clear and concise explanation/example of what works *best for you* at the top of the assets section?

If I knew for sure, I'd have done it myself already :/

**Comment by gamov** [comment]
Adding my 2 cents:
I built a tempting engine for invoices (user chooses the layout) and the engine creates the pdf with the selected layout (based on 2 css files, one generic and one specialised for this layout).
Trying to migrate this to the asset pipeline is not straightforward.
I believe that if you need to start adding many files to the config.assets.precompile array, you are using it wrong.
Therefore, I want to keep my layouts css files organised in the public folder as before.
v1.0.4 makes it almost work without changes (thanks @unixmonkey!, checking for absolute path), except that 'stylesheets' is not added to the path anymore:

    = wicked_pdf_stylesheet_link_tag 'pi_layouts/lined' # stopped working
I had to change to 

    = wicked_pdf_stylesheet_link_tag 'stylesheets/pi_layouts/lined' # bingo!

PS: As 1.0.4, WickedPdfHelper::Assets#read_asset(source) fails silently if it cannot find the asset (nil.to_s = '')

**Comment by Yaroslav-F** [comment]
The problem still remains for me:

production.rb:
`config.assets.precompile += %w( pdf_layout.js pdf_layout.css )`

pdf_layout.html.erb:
```
<%= wicked_pdf_stylesheet_link_tag('application', media: :print) %>
<%= wicked_pdf_javascript_include_tag('pdf_layout', media: :print) %>
<%= wicked_pdf_stylesheet_link_tag('pdf_layout', media: :print) %>
```
Works great locally, but throws this on production: 

```
ActionView::Template::Error (No such file or directory @ rb_sysopen - /home/prod_user/app/public/pdf_layout.js):
    3:     <meta charset="utf-8" />
    4:     <%= wicked_pdf_stylesheet_link_tag('application', media: :print) %>
    5: 
    6:     <%= wicked_pdf_javascript_include_tag('pdf_layout', media: :print) %>
    7:     <%= wicked_pdf_stylesheet_link_tag('pdf_layout', media: :print) %>
    8:   </head>
    9:   <body>
```
I've tried `wicked_pdf_asset_base64`, tried using `asset_path` helper, but neither of these two worked.
Does anyone have any idea how can I fix this?

**Comment by unixmonkey** [comment]
@Yaroslav-F Is `config.assets.compile` set to `true`?

**Comment by Yaroslav-F** [comment]
My bad, after precompiling assets manually it worked. Cheers.
