### ISSUE TITLE
pdf getting not generated.

### ISSUE THREAD

**Issue by abhishekthehulk** [mileszs/wicked_pdf#258]
I have written wickedpdf code in my controller as ,

pdf = render_to_string :pdf => "pdf_file.pdf", :template => '/administrator/orders/show.pdf.html.erb'

send_data pdf, :type => "application/pdf" #,   :filename => "Pdf"

i have done all the installation of wickedpdf on server also. i can generate pdf from command line.

now when i try to generate pdf from application view its giving error as below.

  Failed to execute:
"/usr/local/bin/wkhtmltopdf" -q        "file:////tmp/wicked_pdf20131009-12795-10zq1ju.html" "/tmp/wicked_pdf_generated_file20131009-12795-1g5dwm.pdf"
Error: PDF could not be generated!
 Command Error:
  vendor/bundle/ruby/1.9.1/gems/wicked_pdf-0.9.6/lib/wicked_pdf.rb:82:in `rescue in pdf_from_string'

i also tried to debug wicked_pdf.rb but unable to get any solution.

please help !

**Comment by Richathkkar** [comment]
> From your production environment, does wkhtmltopdf work standalone (without wicked_pdf)?
> 
> You should be able to test from the command-line with something like:
> 
> ```
> /path/to/bin/wkhtmltopdf http://google.com google.pdf
> ```

it's not wokring

**Comment by Richathkkar** [comment]
can anyone give proper solution for this error?

**Comment by Richathkkar** [comment]
Rendered students/_pro.pdf.erb (Duration: 0.0ms | Allocations: 7)
[wicked_pdf]: ["/usr/local/bin/wkhtmltopdf", "--orientation", "Portrait", "--dpi", "400", "--page-width", "50", "--page-height", "225", "--margin-top", "0", "--margin-bottom", "0", "--margin-left", "0", "--margin-right", "4", "file:////tmp/wicked_pdf20210322-12665-g39ssl.html", "/tmp/wicked_pdf_generated_file20210322-12665-mk9fyb.pdf"]
Completed 500 Internal Server Error in 5039ms (ActiveRecord: 25.9ms | Allocations: 7908)


  
RuntimeError (Failed to execute:
["/usr/local/bin/wkhtmltopdf", "--orientation", "Portrait", "--dpi", "400", "--page-width", "50", "--page-height", "225", "--margin-top", "0", "--margin-bottom", "0", "--margin-left", "0", "--margin-right", "4", "file:////tmp/wicked_pdf20210322-12665-g39ssl.html", "/tmp/wicked_pdf_generated_file20210322-12665-mk9fyb.pdf"]
Error: PDF could not be generated!
 Command Error: /var/lib/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf:55:in `initialize': Permission denied @ rb_sysopen - /var/lib/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_ubuntu_20.04_amd64 (Errno::EACCES)
	from /var/lib/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf:55:in `open'
	from /var/lib/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf:55:in `<top (required)>'
	from /usr/local/bin/wkhtmltopdf:23:in `load'
	from /usr/local/bin/wkhtmltopdf:23:in `<main>'
):
can anyone give proper solution?

**Comment by unixmonkey** [comment]
@Richathkkar 

> Permission denied @ rb_sysopen - /var/lib/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_ubuntu_20.04_amd64

This tells me that your system cannot execute the binary installed as part of the gem as the user that your webserver runs as.

For instance, if you install the gem as `root`, but your webserver runs as `www`.

One solution could be to `sudo chmod -R 755 /var/lib/gems/*/gems/wkhtmltopdf-binary-*`.
Another could be to install `wkhtmltopdf` with your system's package manager (instead of a gem).
Yet another could be to copy the binary into your project, make sure the permissions are good, and point to that in `WickedPdf.config[:exe_path]`.

See #911 for more details and suggestions.
