### ISSUE TITLE
Margin in Headers

### ISSUE THREAD

**Issue by lauramosher** [mileszs/wicked_pdf#264]
For some reason when the PDF is being rendered, the header template is being pushed down the same margin distance as the page and then overlapping the top content of the page.

Removing the header it's simply moves the weird block to the top of the page.

I've tested all my styles and nothing is giving any kind of margin that large.

Rendering as HTML the content displays as expected.

**Comment by eltiare** [comment]
@lauramosher What element(s) had the height and position set?

**Comment by jsfeldman** [comment]
In case anyone else stumbles upon this, I had a similar looking issue because I didn't set the spacing key in the header hash.
