### ISSUE TITLE
How can I add page number to a custom footer?

### ISSUE THREAD

**Issue by abacha** [mileszs/wicked_pdf#269]
I'm rendering an html footer, how can I print the page number on it?

**Comment by mnagdewani-systango** [comment]
@unixmonkey Hi mate,I got stuck so need a suggestion from your side.

Here is the problem:

I have combined many pdfs from different string and now I want to add a common footer(which included page number too) for this final combined pdf, so how we can go with wicked PDF?Is there any option listed in wicked pdf for same?

**Comment by unixmonkey** [comment]
@mnagdewani-systango I would suggest you leave space at the bottom of all your pdfs pre-combining them, and apply a footer afterwards with a tool like [PDFtk or StampTk](https://www.pdflabs.com/docs/how-to-add-headers-footers-watermarks-and-stamps-to-pdf/)

Let me know how it goes!

**Comment by mnagdewani-systango** [comment]
@unixmonkey Thanks for help.Still I have an another concern.I want to generate index page after generate pdf with dynamic page numbers in index.Can you let me know, is there any options in wicked pdf or in combined pdf to get this easily or I will have to traverse all pages of PDF.

**Comment by joshuapinter** [comment]
It's right in the [`wkhtmltopdf` docs](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt) and doesn't have anything to do with `wicked_pdf`. See this SO answer for more: https://stackoverflow.com/a/66369004/293280
