### ISSUE TITLE
Trouble with FontAwesome Icons

### ISSUE THREAD

**Issue by brunzino** [mileszs/wicked_pdf#277]
I'm having trouble getting FontAwesome icons to show up in pdf's. Several things are working, except rendering and saving .pdfs. Fonts are now included in base64, though they actually rendered correctly in a couple cases before. 
e.g. 

```
$ wkhtmltopdf http://fortawesome.github.io/Font-Awesome/icons/ icons.pdf
```

renders the icons correctly to icons.pdf

*What is working: *

pointing browser to `http://localhost:3000/my_file.pdf?debug=1` shows icons correctly 

```
$ wkhtmltopdf http://localhost:3000/my_file.pdf?debug=1 my_saved_file.pdf
```

renders icons correctly to my_saved_file.pdf 

Any other ideas to try? Would it help to set up a Github project with my whole set up?

**Comment by hooverlunch** [comment]
Getting rid of // for https:// fixed it for me.
