### ISSUE TITLE
Embed other PDF

### ISSUE THREAD

**Issue by josephzidell** [mileszs/wicked_pdf#285]
This may seem like a strange question, but I actually need this. Can wicked_pdf display another pdf inside?

Essentially, my requirement is to allow users to download a PDF of the current page, which may be either text, or another PDF.

This website has restaurant menus, some of which are plain text, others are PDF. Can I use wicked_pdf to display another PDF?

**Comment by donnguyen** [comment]
Hi @josephzidell, could you please share your solution to solve this issue? Thanks :)
