### ISSUE TITLE
Problem with background images

### ISSUE THREAD

**Issue by UnConundrum** [mileszs/wicked_pdf#302]
I need to use an image as a watermark on various documents I'm generating and converting to PDFs with wicked-pdf.  It took a while, but I have virtually everything working.  My show.pdf.erb is:  

```
<!DOCTYPE html>
<html>
  <head >
    <style type="text/css">
        <%= Rails.application.assets.find_asset('wicked.css').to_s.html_safe %>
    </style>
  </head>
  <body class='wicked'>
    <div>
        <p><%= "#{Doc.last.contents} ".html_safe %></p>
    </div>
  </body>
</html>
```

</pre>

My wicked.css is:  

```
.wicked {
  background-image:url(/assets/test2.jpg);
  background-repeat: no-repeat;
  background-position: 50% -15%;
}
```

And my controller simply calls:  

```
    render :pdf         => "test2",
        :formats        => [:pdf],
        :show_as_html => true
```

All this works fine.  The watermark and the text pulled from the db present properly.  However, when I remove the "show_as_html" from the controller, the watermark disappears and only the text displays as a PDF.  Similarly, if I add "save_to_file", the file saves with only text and no watermark.  I'm baffled as to what I might be doing wrong.  I can't find any errors in any logs.  Thanks for any suggestions.

: show_as_html => true
![screen shot 2014-05-12 at 8 48 07 pm](https://cloud.githubusercontent.com/assets/789152/2952301/905bba20-da38-11e3-88f2-615777e49037.png)

:show_as_html=false
![screen shot 2014-05-12 at 8 52 38 pm](https://cloud.githubusercontent.com/assets/789152/2952318/f5202d10-da38-11e3-9cfc-9fff46bfc021.png)

**Comment by carlosdanielpohlod** [comment]
> This should work in both environments:
> 
> ```
> background-image:url('<%= "file://#{Rails.root.join('app','assets','images','test2.jpg')}" %>');
> ```

I tried this method, but rails not allow the resource access, and I got the `turbolinks.js:718 Not allowed to load local resource: file:///var/www/...` message
