### ISSUE TITLE
ChartKick charts do not show when rendering to PDF using Wicked_PDF

### ISSUE THREAD

**Issue by Steggur** [mileszs/wicked_pdf#343]
I am using Rails 4, Wicked_PDF and Chartkick Gem's
For Google Charts I use:

<%= javascript_include_tag "//www.google.com/jsapi", "chartkik" %>

The html view comes up with charts and everything as expected. When I append .pdf to the url the pdf document shows in the browser but the ChartKick charts do not show.
The following error appears where the chart should be:

Error Loading Chart: No adapter found

I have found the following online in the PDFKit documentation.

Resources aren't included in the PDF: Images, CSS, or JavaScript does not seem to be downloading correctly in the PDF. This is due to the fact that wkhtmltopdf does not know where to find those files. Make sure you are using absolute paths (start with forward slash) to your resources. If you are using PDFKit to generate PDFs from a raw HTML source make sure you use complete paths (either file paths or urls including the domain). In restrictive server environments the root_url configuration may be what you are looking for change your asset host.

I am assuming that wkhtmltopdf is not finding the link to the charts, but I am not sure how to fix this.
Does anyone have a suggestion?

I have tried this:
<%= wicked_pdf_javascript_include_tag "application", "chartkick" %>

**Comment by vsrboth** [comment]
Please use `javascript_delay: 5000`. This works for me with ChartJS.

**Comment by raffe90** [comment]
I've been trying to make this work, but I am unable, I get this error:

Error: PDF could not be generated! Command Error: Unknown long argument --javascript-delay

**Comment by unixmonkey** [comment]
@raffe90 

`javascript_delay` is only usable with newer versions of `wkhtmltopdf`.

Try replacing the `wkhtmltopdf-binary` gem with `wkhtmltopdf-edge`, and let me know how it goes!

**Comment by raffe90** [comment]
@unixmonkey you're right. I uninstalled the gem and instead I'm using my local (direct) install. 

All is good now.

Thanks

**Comment by amitfriedman12** [comment]
@unixmonkey just to clarify, you are referring to [wkhtmltopdf-binary-edge](https://github.com/pallymore/wkhtmltopdf-binary-edge)

**Comment by Yaroslav-F** [comment]
+1, [wkhtmltopdf-binary-edge](https://github.com/pallymore/wkhtmltopdf-binary-edge) worked for me

**Comment by unixmonkey** [comment]
Yep, sorry, I did mean [wkhtmltopdf-binary-edge](https://github.com/pallymore/wkhtmltopdf-binary-edge).

**Comment by Owohlet** [comment]
I'm having a similar issue. I used the helpers provided by but somehow I don't think the javascript is being loaded in the pdf. The space where the charts are supposed to load shows only "loading..."
![chartkick](https://user-images.githubusercontent.com/8749154/31387088-0a217958-adc1-11e7-981e-c43d6e6aa858.png)

For the pdf layout (`generate_pdf.pdf.erb`) I have these
`<%= wicked_pdf_javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>`
`<%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>`
`<%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js" %>
`
which are the exact same assets I'm using in the HTML template and the charts work.
I have tried to use javascript_delay: 9000 with no success. I've tried to change the gem to` 'wkhtmltopdf-binary-edge'` no luck. 
I tried to extract the libraries and put them in my application manually in the bin file. The pdf works well but no charts. Any tips?

**Comment by unixmonkey** [comment]
Those are all CDN-provided js files, you can try regular `javascript_include_tag` in place of `wicked_pdf_javascript_include_tag`.

Let me know how it goes!

**Comment by jbmyid** [comment]
Not working me as well
```
k = PDFKit.new "https://developers.google.com/chart/interactive/docs/gallery/barchart"
k.to_file "some/path"

```
added  
```
 config.default_options = {
    javascript_delay: 5000
  }

```
Its not displaying charts

**Comment by Owohlet** [comment]
@unixmonkey I figured out what was wrong with mine. Turns out it wasn't loading `//= require Chart.bundle` and `//= require chartkick` in my `application.js` which I thought it did. Adding `<%= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track' => true %>` fixed it for me.

**Comment by jbmyid** [comment]
I made it work with the google charts using

`<script type="text/javascript" src="https://www.google.com/jsapi"></script>`


instead of 
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.jsi"></script>`

**Comment by tanakaworld** [comment]
I made it to work by [this way](https://github.com/ankane/chartkick/issues/373#issuecomment-356538556)

**Comment by AssoMania** [comment]
And how did you increase the size of the chart tanakaworld ? I use , width: "100%", height: "300px" but still the same size, weird

**Comment by MoacirPetry** [comment]
Any solution for this "Loading..."???
I tried every tip here, but it continues appearing when I generated a pdf file. On the Html page, the chartkick works fine. 😩

**Comment by bonafernando** [comment]
I'm also waiting for a solution nothing really seems to fix it.

**Comment by anarbelaez** [comment]
hello! did you find any solution for this issue? I tried every solution but nothing really fix it 😪

**Comment by bonafernando** [comment]
@anarbelaez I stopped searching for a solution. I was able to convince the client on opening a new tab as HTML and using the browser to print. Not good at all, but it is what it is. But my last attempt was on the day of this question, maybe there were some updates?
