### ISSUE TITLE
Generating PDF from XML and XSL

### ISSUE THREAD

**Issue by josegrad** [mileszs/wicked_pdf#345]
Is it possible to generate a pdf suplying an XML string and XSL file?

**Comment by colinambler** [comment]
@josegrad - would you be willing to send your XML and XSL files?   I'm woking on customizing my table of contents.  Although, first time dabbling in XML and certainly XSL!  Would be great to work off a foundation rather than scratch.  Thanks in advance.

**Comment by josegrad** [comment]
@colinambler - you can reach me at josegrad@gmail.com
I can send you something over there.
