### ISSUE TITLE
AngularJS-Rails Gem Injected Into Body

### ISSUE THREAD

**Issue by jonhainstock** [mileszs/wicked_pdf#367]
I'm having an issue rendering PDFs with AngularJS. I'm using the [angularjs-rails gem](https://github.com/hiravgandhi/angularjs-rails) and require angular with a pdf javascript manifest file that is called from the header using wicked_pdf_javascript_include_tag. 

I can see that angular is not being wrapped in the head script tag, but instead, it is injected into the body. It doesn't do this with any of the other scripts (jQuery, underscore, Bootstrap, etc...). 

![screen_shot_2014-12-01_at_6_55_56_pm](https://cloud.githubusercontent.com/assets/1247220/5256319/752f4944-798c-11e4-9234-021252ff5b5d.png)

Any ideas on how I can fix this? 

Thank you!

**Comment by unixmonkey** [comment]
@jonhainstock Did you ever get things working?

**Comment by jonhainstock** [comment]
@unixmonkey no, but we ended up pulling the wicked_pdf functionality back into rails and created some light pages for reporting instead of trying to do things in Angular. Thanks!
