### ISSUE TITLE
Table Row took extra space 

### ISSUE THREAD

**Issue by vf-sohail** [mileszs/wicked_pdf#380]
I am facing issue while rendering table to pdf. In pdf certain rows are too long with blank spaces. The issue only comes in certain columns not all.
![issue](https://cloud.githubusercontent.com/assets/9191591/5932964/adba287c-a6d9-11e4-86e7-b4c4516de9a6.png)

As you see in image first row take some extra space.  Any help?

**Comment by unixmonkey** [comment]
This looks like a css/stylesheet issue to me. If you resize your browser or preview a print dialog, does it behave similarly? What if you remove all styling?

You might play with the height of the cells, or the zoom to correct it.

This thread details a similar issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1908

**Comment by vf-sohail** [comment]
Thanks for your suggestions. I fixed the issue. The issue is coming due to following lines of code.
td div, th div{
    page-break-inside: avoid;
}
After removing these lines all the extra spaces removed.

**Comment by raghvendra1501** [comment]
I also have the same issue but not with the table, it is with few images. If I don't write 
td div, th div{
page-break-inside: avoid;
}
It overlaps sometimes with the text and if I add it, it adds extra spaces after or before the image. Not sure what should I do ?

**Comment by BDhara** [comment]
I also have same issue and this resolve it but  I have to use page-break-inside in table otherwise it will print continously without breaking rows on new page..what to do?

**Comment by BDhara** [comment]
@raghvendra1501  did you find any solution .. I also face same problem
