### ISSUE TITLE
JS only works in debug mode

### ISSUE THREAD

**Issue by ozeron** [mileszs/wicked_pdf#385]
Hello,
I'm trying to print pdf for a complicated page with mapbox maps and few js flots charts. When I'm rendering page with debug param, everything works as expected, but when I switch to normal mode works only css, and I have only one map with broken bounds and position and don't see any charts or other maps. I have feeling that smth goes wrong during printing stage, if there is any way to check printing for errors? Or any other suggestions why things goes wrong?

 Currently I'm developing on my local machine, and I'm not using Assets pipeline. I'm using wicked_pdf helpers  in my source code, so all css and js file are concatenated and works fine in debug mode. 

I'm using Rails 3.2 and wkhtmltopdf 0.12.2.1 (with patched qt).

I have tried to render pdf with different options, here is my rendering options
```
render pdf: "report.pdf",
               layout: "application.pdf",
               formats: [:html, :pdf],
               disable_javascript: false,
               show_as_html: params[:debug].present?,
               orientation: 'Landscape',
               encoding: 'UTF8'

**Comment by ozeron** [comment]
Ok, It looks like, that this is a wkhtmltopdf problem.

**Comment by Pawlarius** [comment]
@ozeron what did you do? i also have same problem..

**Comment by unixmonkey** [comment]
Sounds to me like JS might be taking too long and wkhtmltopdf gives up and renders.

You can avoid that by using a `window_status: 'done_with_js'` setting

which waits to render through wkhtmltopdf until some JS sets `window.status` to the given string, so you could trigger that with something like this:

```javascript
// do_other_javascript_stuff.then(function() {
  window.status = 'done_with_js';
});
```

You might also be able to use no_stop_slow_scripts: true.

Alternately, you might try not using the `wicked_pdf_javascript_include_tag` helper, which can sometimes have issues with JS libraries that include HTML or SCRIPT tags in them.

Keep us updated with what works for you!
