### ISSUE TITLE
Temp Directory Issues and Request

### ISSUE THREAD

**Issue by JackWCollins** [mileszs/wicked_pdf#388]
This is a request for a fix / better support of custom specified temporary directories. We currently have a code flow that starts with `PdfHelper#render_with_wicked_pdf`. That calls `PdfHelper#make_and_send_pdf`, subsequently `PdfHelper#make_pdf`, which creates a new `WickedPdf` class and calls `WickedPdf#pdf_from_string`. During these calls the options hash is passed around appropriately.

The problem starts with `WickedPdf#pdf_from_string`. That method reads the `temp_path` but then deletes it from the options hash. That method subsequently calls `pdf_from_html_file` which checks  in the options hash **for the temp path that was just deleted**. Since the temp path in the hash is not present, we fall back on the default `Dir.tmpdir` in `WickedPdfTempfile` class.

      
      def pdf_from_string(string, options={})
        temp_path = options.delete(:temp_path) # !! Read and subsequently delete
        string_file = WickedPdfTempfile.new("wicked_pdf.html", temp_path)
        string_file.binmode
        string_file.write(string)
        string_file.close

        pdf = pdf_from_html_file(string_file.path, options)
        pdf
      rescue Exception => e
        raise "Error: #{e}"
      ensure
        string_file.close! if string_file
      end

      def pdf_from_html_file(filepath, options={})
        if WickedPdf.config[:retreive_version]
          retreive_binary_version
        end

        temp_path = options.delete(:temp_path) # !! Check for it again
        generated_pdf_file = WickedPdfTempfile.new("wicked_pdf_generated_file.pdf", temp_path)
        command = [@exe_path]

        ... code omitted for brevity ...

        pdf
      rescue Exception => e
        raise "Failed to execute:\n#{command}\nError: #{e}"
      ensure
        generated_pdf_file.close! if generated_pdf_file && !return_file
      end

I believe a better method would be to specify a temp_path as part of the `WickedPdf.config` and just check for that in each of these methods.

      def pdf_from_string(string, options={})
        temp_path = WickedPdf.config[:temp_path]
        string_file = WickedPdfTempfile.new("wicked_pdf.html", temp_path)
        
        ... code omitted ...

      end

      def pdf_from_html_file(filepath, options={})
        if WickedPdf.config[:retreive_version]
          retreive_binary_version
        end

        temp_path = WickedPdf.config[:temp_path]
        generated_pdf_file = WickedPdfTempfile.new("wicked_pdf_generated_file.pdf", temp_path)
        command = [@exe_path]

        ... code omitted ...

      end

If you are interested in making this change, I would be happy to make a pull request.

**Comment by unixmonkey** [comment]
That would be great!

**Comment by JackWCollins** [comment]
After forking and checking out the code, it looks like this was already fixed in (pull 332)[https://github.com/mileszs/wicked_pdf/pull/332]. Once you release a new version then that fix will be included. I'll close this for now.
