### ISSUE TITLE
wicked_pdf shows javascript code on production

### ISSUE THREAD

**Issue by itshakeel23** [mileszs/wicked_pdf#389]
I have installed required libraries on production server but when i render PDF it shows the following:

![test](https://cloud.githubusercontent.com/assets/538055/6426107/4141e38c-bf62-11e4-9a44-68733cdced1f.png)

any help ?

**Comment by unixmonkey** [comment]
`wicked_pdf_javascript_include_tag` will inline the JS in a `<script>` tag (for speed and portability). With some larger JS libraries, there can be HTML code that "breaks out" of it.

Try using a regular `javascript_include_tag` or base64-encoding it as shown in #257

**Comment by unixmonkey** [comment]
@itshakeel23 Did you get this working?

**Comment by itshakeel23** [comment]
Yes it worked.
