### ISSUE TITLE
javascript_delay is not working

### ISSUE THREAD

**Issue by vsrboth** [mileszs/wicked_pdf#397]
I am currently facing a problem with `javascript_delay` option.
This seems not working as explain in the READ.MD, here is the error I got:

`RuntimeError - Error: Failed to execute:
["/Users/sereyboth/.rvm/gems/ruby-2.0.0-p353@yoolk_portal/bin/wkhtmltopdf", "-q", "--javascript-delay", "6000", "file:///var/folders/ms/3gmwdkpd1cs4j8gmzlj8g6zc0000gn/T/wicked_pdf20150330-2170-1b0861o.html", "/var/folders/ms/3gmwdkpd1cs4j8gmzlj8g6zc0000gn/T/wicked_pdf_generated_file20150330-2170-1fwwqff.pdf"]
Error: PDF could not be generated!
 Command Error: Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to` `bundle binstub wkhtmltopdf` `to work around a system/bundle conflict.
Unknown long argument --javascript-delay`

Name:
  wkhtmltopdf 0.9.9`

My current `wicked_pdf` and `wkhtmltopdf-binary`

gem 'wicked_pdf',                   '~> 0.11.0'
gem 'wkhtmltopdf-binary',           '~> 0.9.9.3'

**Comment by unixmonkey** [comment]
`--javascript-delay` is only in newer versions of `wkhtmltopdf` (I think it was introduced in 11.x). I would suggest you update `wkhtmltopdf` or wrap your javascript initialization in a `setTimeout` to achieve the same effect:

```js
setTimeout(function(){
   // javascript initialization code here
}, 6000);
```

**Comment by vsrboth** [comment]
Thank you so much for your prompt response @unixmonkey 

May I have some advices on how I can convert the chart to PDF while I am currently using Flot Chart to render charts?
The flow is to run in a background mode whereby it doesn't go through the browser. I feel like the javascript doesn't work while converting to pdf. Here is my codes:

`RoR`:

`html = render_to_string(template, layout: PDF_LAYOUT_TEMPLATE)`
`pdf   = WickedPdf.new.pdf_from_string(html)`
 `send_data(pdf, filename: file_name, disposition: 'attachment')`

`html & JS`:

!!!
%head
  %meta{ http_equiv: 'Content-Type', content: 'text/html', charset: 'UTF-8' }
  = javascript_include_tag 'https://code.jquery.com/jquery-2.1.3.min.js'
  = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js'
  = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.canvas.min.js'
  = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js'

  = wicked_pdf_stylesheet_link_tag 'listings/campaigns'

  :javascript
    setTimeout(
      function drawPieChart() {
        var object = $('#adwords-pie-chart');
        var data   = parseFloat(object.attr('data-chart-value')).toFixed(2);
        var label  = object.attr('data-label');

        var another_data = parseFloat(100 - data).toFixed(2);
        var dataset = [{label: label, data: data}, {label: 'Search Imp. Share Lost', data: another_data}]
        var plot   = $.plot(object, dataset,{ series: {
              pie: {
                  show: true,
                  radius: 1,
                  label: {
                    show: true,
                    radius: 2/3,
                    formatter: null,
                    threshold: 0.1
                  }
              }
            },
            legend: {
              show: false
            }
          });

        var ctx = plot.getCanvas();
        var url = ctx.toDataURL("image/png");
        object.attr('src', url);
      }
    , 6000)

%body{ onload: 'drawPieChart()' }
  = yield

**Comment by unixmonkey** [comment]
Looks to me like you want to wait until the chart is fully drawn (with JS) before you want wkhtmltopdf to take its screenshot, instead of waiting before the JS fully executes. Instead of wrapping your JS, try adding the setTimeout outside:

```js
function drawPieChart() {
  // code to draw chart
  setTimeout(function(){ /* do nothing */ }, 6000);
}
```
This might coax the browser to wait before taking its snapshot, but I would suggest you do update `wkhtmltopdf`. This StackOverflow thread shows someone had success with Flot:

http://stackoverflow.com/questions/19425421/javascript-delay-throwing-error-in-wicked-pdf

**Comment by vsrboth** [comment]
seems like it doesn't work as expected. What I am suspecting is that the javascript is not executing while converting to PDF without going through the browser.

The chart is rendering fine while setting an option `show_as_html: true` on a browser.

**Comment by vsrboth** [comment]
@unixmonkey by using the latest `wkhtmltopdf` with `javascript_delay` solve my issue.

Thank you so much for your help.

**Comment by joshuapinter** [comment]
I had the same issue and in my case I was fetching the JSON data, with `$.getJSON`. 

This would cause the chart to show up blank.

Removing this and pre-fetching the data made it work. 

My guess is that `getJSON` is async and wkhtmltopdf doesn't "know" to wait for that to finish before taking the snapshot. It properly waits for synchronous calls, though.
