### ISSUE TITLE
Can not install this wicked_pdf gem from git repo.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [mileszs/wicked_pdf#414]
Hi,I am trying to install wicked_pdf gem by the command ```bundle install``` from git but it gave me the following message.

You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git

Check my gemfile below.
```
source 'https://rubygems.org'

gem 'rails', '3.2.19'
gem 'mysql'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'momentjs-rails', '>= 2.8.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'
gem 'bootstrap-datepicker-rails', '>= 0.6.21'
gem 'will_paginate', '~> 3.0'
gem 'wicked_pdf', :github => 'mileszs/wicked_pdf', :branch => 'master'
```

It is working file on windows xp.But i am using windows 7 64 bit system.I have already installed also github in my system.Please provide me the steps to install this wicked_pdf gem from git.

**Comment by unixmonkey** [comment]
Is this still an issue for you?

Your system doesn't appear to have `git` installed in a way that ruby can use it.

I'm closing this because it isn't a problem with `wicked_pdf`, but feel free to comment and I'll try to help you out if necessary.
