### ISSUE TITLE
pdf_from_url not working as documented

### ISSUE THREAD

**Issue by EminenceHC** [mileszs/wicked_pdf#419]
Hi, wherever I use pdf_from_url I receive an error like:  

undefined method `pdf_from_url' for #WickedPdf:0x007f8d6caa81f0

Am I missing something, or is this feature not yet implemented?

**Comment by unixmonkey** [comment]
If you are using the gem from rubygems.org, then you are using a version of wicked_pdf that does not have that feature yet.

You can point your gemfile at the latest github version with:

__Gemfile__
```ruby
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
```

and `bundle install` to use the very latest.

**Comment by EminenceHC** [comment]
Thank you for that insanely fast reply!

**Comment by EminenceHC** [comment]
I did happen to notice that with this version:  <%= wicked_pdf_stylesheet_link_tag "application", :media => "all" %> Now says nil class instead of pulling stylesheet information.

**Comment by unixmonkey** [comment]
Interesting. What version of Rails? Where is your stylesheet located, and what is it named?

**Comment by EminenceHC** [comment]
Rails 4.0.2 
My stylesheet is located in the default asset pipeline at: app/assets/stylesheets/application.css.scss

**Comment by EminenceHC** [comment]
If I remove  *= require_tree . from my application.css.scss file, the pdf generates without an issue. 

What I find strange is, if i leave require tree in application.css, and comment out ALL of my separate css files, I still get error nil class when trying to generate PDF.

**Comment by unixmonkey** [comment]
I think that might be related to this issue/pull request: https://github.com/mileszs/wicked_pdf/pull/379

Does it work if you point it at a plain stylesheet with only one extension like `application.scss` instead of `application.css.scss`?

**Comment by EminenceHC** [comment]
I tried renaming my application.css.scss to application.scss and then tried to reference like:

 <%= wicked_pdf_stylesheet_link_tag "application", media: "all" %>
 <%= wicked_pdf_stylesheet_link_tag "application.scss", media: "all" %>

I also tried renaming it to application.css and tried: 

 <%= wicked_pdf_stylesheet_link_tag "application", media: "all" %>
 <%= wicked_pdf_stylesheet_link_tag "application.css", media: "all" %>

Each gives me that NilClass error. Here is a gist of the stylesheet I am using to reference, and my controller code. https://gist.github.com/EminenceHC/fe6b0afe9b3b3e7aaca0

**Comment by EminenceHC** [comment]
I can confirm that the stylesheets are not being loaded at all, even after pointing to a plain stylesheet with no dependencies. The only good changing the name from "application" to "application.scss" did was silence the Nil Class error.

**Comment by EminenceHC** [comment]
I can confirm that the stylesheets are not being loaded at all, even after pointing to a plain stylesheet with no dependencies. The only good changing the name from "application" to "application.scss" did was silence the Nil Class error.

**Comment by brianmwadime** [comment]
hello @unixmonkey, noticed even after pointing to the gitub version of the gem. Pdf's are still not generated when calling *pdf_from_url*

QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv2_server_method
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setOpacity: Painter not active
QPainter::setFont: Painter not active

I'm guessing it's a problem with my setup. Any ideas?

**Comment by brianmwadime** [comment]
@unixmonkey managed to get it running by installing the latest version of wkhtmltopdf v0.12.2.1 which doesn't require ann x-server to run.

**Comment by unixmonkey** [comment]
Thanks for the clarification 👍
