### ISSUE TITLE
WickedPdf.new.pdf_from_url() problem using localhost path

### ISSUE THREAD

**Issue by EminenceHC** [mileszs/wicked_pdf#422]
.pdf_from_url() works fine when using a non-local url like www.google.com.

However, when I try it from a localhost path, WickedPdf.new.pdf_from_url("http://localhost:3000")

The PDF file is never created. The browser just sits there and waits for a response. I do not get an error message unless I stop the server completely. Any idea about what might be blocking this?

**Comment by unixmonkey** [comment]
Yes. By default, `rails server` is a single-threaded webserver. So your first request hits your endpoint to generate the pdf, then WickedPDF shells out to `wkhtmltopdf` to get your website contents, only your localhost rails server is still in the middle of serving your first request, so `wkhtmltopdf` has to wait for that first request to finish before it gets a response.

You can try to use a threaded webserver with multiple workers, like puma, or use Foreman to start up multiple unicorns or something like that, but I would recommend trying to render your content locally. It will be a lot faster, and won't depend on a multithreaded server.

**Comment by EminenceHC** [comment]
Thanks for the great explanation. The reason I want to render localhost urls is so I can use this gem to run reports (a single PDF from multiple pages). I was thinking I would just create a PDF from all the URLs that I want in the report and then use something like PDF merge gem to combine them into a single PDF. Maybe there is a better way to do this locally?

**Comment by EminenceHC** [comment]
Thanks for the great explanation. The reason I want to render localhost urls is so I can use this gem to run reports (a single PDF from multiple pages). I was thinking I would just create a PDF from all the URLs that I want in the report and then use something like PDF merge gem to combine them into a single PDF. Maybe there is a better way to do this locally?
