### ISSUE TITLE
Show images from URL(i.e. from CDN) In pdf

### ISSUE THREAD

**Issue by sshinde2011** [mileszs/wicked_pdf#425]
I want to show images from URL into pdf i.e. images from CDN. I have used wicked_pdf_image_tag but it shows images on file system.

**Comment by unixmonkey** [comment]
Then use the full CDN URL and don't use `wicked_pdf_image_tag`.

https://github.com/mileszs/wicked_pdf#cdn-reference

Let me know if you have any trouble and I'll reopen.

**Comment by sshinde2011** [comment]
thank you for your reply. I got the part.
