### ISSUE TITLE
:toc option fails with wkhtmltopdf 0.12

### ISSUE THREAD

**Issue by farneman** [mileszs/wicked_pdf#427]
Using wicked_pdf 0.11 with current versions of wkhtmltopdf-binary-edge or wkhtmltopdf-heroku that use wkhtmltopdf 0.12.x throws the following:
 
    Error: Failed to execute:
    ["/Users/farneman/.rbenv/versions/1.9.3-p547/bin/wkhtmltopdf", "-q", "--footer-center", 
    "[page] of    [topage]", "--toc", "--margin-top", "5mm", "--margin-bottom", "5mm", "--margin-left", 
    "5mm", "--margin-right", "5mm", "--page-size", "Letter", "--dpi", "300", "--disable-smart-shrinking", 
    "file:///var/folders/vp/t45ttc756jq3fd_ld3p77bf80000gq/T/wicked_pdf20150709-99190-5olp3c.html", 
    "/var/folders/vp/t45ttc756jq3fd_ld3p77bf80000gq/T/wicked_pdf_generated_file20150709-99190-1qoea1h.pdf"]
    Error: PDF could not be generated!
    Command Error: Unknown long argument --toc
    ...

From the wkhtmltopdf docs for the current version at http://wkhtmltopdf.org/usage/wkhtmltopdf.txt that the usage for a TOC has changed. Looks like wicked_pdf will need to be updated to support this new syntax.

**Comment by unixmonkey** [comment]
Have you tried against master? I'm pretty sure that's already been patched.

You can by changing your Gemfile like this:
```ruby
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
```
Let me know if that works for you.

**Comment by farneman** [comment]
@unixmonkey That works, thanks!
