### ISSUE TITLE
header/footer with html template not render in every page

### ISSUE THREAD

**Issue by fmh** [mileszs/wicked_pdf#429]
Hello,
I have a strange issue. in my case , the header or footer is not rendered in every page, and footer disappers when header is defined,
`````ruby
format.pdf {
                render pdf: "myfile",
                       header: {
                           html: {template: 'my_views/generate_pdf_header'}
                       },
                       footer: {
                           html: {template: 'my_views/generate_pdf_footer'}
                       },
                       show_as_html: params[:as_html]
              }
 ````````````
is this a problem caused by margin ?

<img width="212" alt="capture d ecran 2015-07-13 a 08 54 27" src="https://cloud.githubusercontent.com/assets/56861/8644198/4d1e126c-293d-11e5-8979-32a893572556.png">

**Comment by fmh** [comment]
use master branch, resolve my issue ,

**Comment by fmh** [comment]
but have  on top of every  page. I think is caused by wicked_pdf_stylesheet_link_tag when join multiple style
Don't need  .join("\n") to make a new line for new or maybe try with single quote ('\n')

`````ruby
#workaround
(wicked_pdf_stylesheet_link_tag "mycss.css").gsub('\n',"").html_safe

**Comment by fmh** [comment]
but have a "\n" on top of every  page. I think is caused by wicked_pdf_stylesheet_link_tag when join multiple style.
Don't need  .join("\n") to make a new line for new or maybe try with single quote ('\n')

`````ruby
#workaround
(wicked_pdf_stylesheet_link_tag "mycss.css").gsub('\n',"").html_safe

**Comment by unixmonkey** [comment]
:+1: Thanks for bringing this to my attention.

I've fixed this on the master branch.

Let me know if you have any trouble after updating.

**Comment by fmh** [comment]
work fine ,thx.
have you planned any new release ?
