### ISSUE TITLE
Problem finding css

### ISSUE THREAD

**Issue by gavinheale** [mileszs/wicked_pdf#430]
I am using rails 4.0 and trying to get a stylesheet via the asset pipeline.  My code works fine in development mode but does not find the css in production mode.  I get the following:
```
F, [2015-07-13T17:53:30.929978 #17417] FATAL -- :
ActionView::Template::Error (No such file or directory @ rb_sysopen - /DemoStuff/project/public/leaflet.css):
    2: <html style="height:100%">
    3: <head>
    4:   <meta charset='utf-8' />
    5:   <%= wicked_pdf_stylesheet_link_tag "leaflet" -%>
```

I noticed that there was a commit to do with css so I changed to the master branch on git and now I am getting this error
```
F, [2015-07-13T18:18:43.119069 #19874] FATAL -- : 
ActionView::Template::Error (undefined method `+' for nil:NilClass):
    2: <html style="height:100%">
    3: <head>
    4:   <meta charset='utf-8' />
    5:   <%= wicked_pdf_stylesheet_link_tag "leaflet" -%>
```

The file in question is assets/stylesheets/leaflet.css.scss

Is there anything special I need to be doing?

**Comment by unixmonkey** [comment]
https://github.com/mileszs/wicked_pdf#asset-pipeline-usage

You'll need to precompile leaflet for it to find the version without an asset fingerprint:
```ruby
config.assets.precompile += ['leaflet.css.scss']
```

Let me know if you have any trouble.

**Comment by gavinheale** [comment]
I still seem to be getting the same error.

**Comment by unixmonkey** [comment]
I'll take a look soon, but the instructions to precompile should fix the first issue you posted using the non-master version of the gem.

**Comment by gavinheale** [comment]
Thanks,

I seem to have got it going.  The problem was the precompile wasnt working with 'leaflet.css.scss'.  I changed that to 'leaflet.css' and moved back to the non-master version and I seem to have it working now.

Thanks again for all the hard work.
