### ISSUE TITLE
ActionView::Template::Error (no implicit conversion of nil into String)

### ISSUE THREAD

**Issue by StevenHarlow** [mileszs/wicked_pdf#434]
I'm trying to render a pdf in a production environment (everything works fine locally), but this line 

    <%= wicked_pdf_stylesheet_link_tag "pdf" %>

causes this error

    ActionView::Template::Error (no implicit conversion of nil into String)

**Comment by unixmonkey** [comment]
What does pdf.css look like? Does it exist?

**Comment by StevenHarlow** [comment]
app/assets/pdf.css.scss exists

**Comment by unixmonkey** [comment]
It's trying to load pdf.css (not pdf.css.scss), I'm pretty sure you can get around this if you precompile first.

https://github.com/mileszs/wicked_pdf#asset-pipeline-usage

    config.assets.precompile += ['pdf.css.scss']

Let me know how it goes!

**Comment by StevenHarlow** [comment]
I already had config.assets.precompile += ['pdf.css'], and changing it to include the scss didn't help in my case.  I choose to try with the Rails helpers, and managed to get to another errror.

    RuntimeError (Error: Failed to execute:
    ["/app/vendor/bundle/ruby/2.1.0/bin/wkhtmltopdf", "-q", "--javascript-delay", "5000",  "file:////tmp/wicked_pdf20150803-12-gw3m93.html", "/tmp/wicked_pdf_generated_file20150803-12-17lt4au.pdf"]
    Error: PDF could not be generated!
    Command Error: Unknown long argument --javascript-delay

The version of wkhtmltopdf that the 'wkhtmltopdf-binary' gem included is apparently 0.9.6.  Does this version not include options for javascript-delay?  I'm rendering d3 charts so it's needed here.

**Comment by unixmonkey** [comment]
`javascript-delay

**Comment by StevenHarlow** [comment]
I fixed the javascript-delay error by using the wkhtmltopdf-heroku gem instead of the wkthmltopdf-binary gem, though as expected the assets aren't showing with the Rails helpers.  So the original error still persists.  I've gone through the steps to add ['pdf.css'] (and the alternate version ['pdf.css.scss']) to the precompile array.

**Comment by unixmonkey** [comment]
I am guessing your stylesheet has some other references inside of it like background images. Is that correct?

`wkhtmltopdf` will need a *full* file path or URI for all assets, since it needs to render everything from a static file.

Try with a full filesystem path:
```css
background-image: url('<%= Rails.root.join('public','images','mylogo.jpg') %>');
```
or a full URI with host and protocol:
```css
background-image: url('http://yourdomain.com/mylogo.jpg');
```
Or you can base64-encode all your assets with a helper like this (put it in application_helper.rb):
```ruby
def asset_data_base64(path)
  asset = Rails.application.assets.find_asset(path)
  throw "Could not find asset '#{path}'" if asset.nil?
  base64 = Base64.encode64(asset.to_s).gsub(/\s+/, "")
  "data:#{asset.content_type};base64,#{Rack::Utils.escape(base64)}"
end
```

and use like this:
```erb
background-image: url('<%= asset_data_base64('images/mylogo.jpg') %>');
```

With this helper you can also use regular asset helpers instead of the `wicked_pdf_*` helpers, and remove the precompile directive:

```erb
<%= stylesheet_link_tag(asset_data_base64('pdf.css')) %>
<%= javascript_include_tag(asset_data_base64('somefile.js')) %>
<%= image_tag(asset_data_base64('foo.png')) %>
```

Let me know how it goes!

**Comment by StevenHarlow** [comment]
I did have other url's in the generated css, but even when I delete all the css rules, rename the pdf.css.scss to "pdf.css" with only one rule body{ background-color: green}, and include pdf.css in the precompile array the error still persists.

pdf.css is now app/assets/stylesheets/pdf.css, and there is a public/assets/pdf.css with the same rule.


The proposed solution above wouldn't be ideal for my use case as I would have to know which libraries (ie bootstrap) are also including urls and override them to use asset_data_base64

**Comment by unixmonkey** [comment]
Because it is being precompiled, try to reference the copy in /public/assets/pdf.css directly like this:

```erb
<%= stylesheet_link_tag "file://#{Rails.root.join('public','assets','pdf.css')}" %>
```

See if that makes any difference, please.

If it doesn't, please try to include the full stacktrace, including line numbers.

**Comment by StevenHarlow** [comment]
That was exactly what I was trying next and it works!  Thank you for your help @unixmonkey
