### ISSUE TITLE
Footer + toc + cover issue

### ISSUE THREAD

**Issue by klatooine** [mileszs/wicked_pdf#435]
I'm trying to add a footer to a PDF with cover and TOC, but the footer only renders in the TOC pages. The problem is that in the call to wkhtmltopdf the footer option is passing as a local option of the TOC. Is there anyway of putting it as a Global option for all the document?

If I delete the TOC and the cover everything is ok, if not the footer option is in the end of the call and wkhtmltopdf take it as a local option.

I found this after a long search https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1631#issuecomment-40567711

What can I do? is there anyway to put it as a global option?

**Comment by unixmonkey** [comment]
What does the `wkhtmltopdf` command look like? (in development mode, it is in the server log when the PDF generates)

What version of `wkhtmltopdf` and `wicked_pdf` are you using?

Does the problem go away if you use the master branch version of this gem like this:

__Gemfile__
```ruby
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
```

**Comment by klatooine** [comment]
Hi, i have already it using the master branch version. 

The command is this:

"***************[\"PATH_TO_APP/vendor/bundle/ruby/2.2.0/bin/wkhtmltopdf\", \"-q\", \"--margin-top\", \"10\", \"--margin-bottom\", \"10\", \"--margin-left\", \"10\", \"--margin-right\", \"10\", \"cover\", \"http://www.fasant.com/cover/1\", \"toc\", \"--toc-header-text\", \"1. Table of Contents\", \"--footer-right\", \"[page] of [topage]\", \"file:////var/folders/2y/_22jw6d50s989szbmhbrxbzw0000gn/T/wicked_pdf20150805-28804-l9j9d0.html\", \"/var/folders/2y/_22jw6d50s989szbmhbrxbzw0000gn/T/wicked_pdf_generated_file20150805-28804-87cbuc.pdf\"]***************"

Thank you

**Comment by unixmonkey** [comment]
It is still important to know what version of `wkhtmltopdf` you are using, as the TOC option positions changed between 0.9.x and 0.10.x (or was it 0.10.x and 0.11.x - I don't remember).

Is this coming from the `wkhtmltopdf-binary-gem`?

You can find out the version number by running this in the terminal:
```shell
PATH_TO_APP/vendor/bundle/ruby/2.2.0/bin/wkhtmltopdf --version
```

**Comment by klatooine** [comment]
Yes, I am using wkhtmltopdf 0.12.2.1 (with patched qt), with the gem 'wkhtmltopdf-binary-edge', '~> 0.12.2.1'

**Comment by klatooine** [comment]
Hi, i am still stuck with this, any hint?

**Comment by unixmonkey** [comment]
Can you show me what your controller `render :pdf` call looks like?

**Comment by klatooine** [comment]
Yes of course      
```ruby
format.pdf do
        render pdf: "Guide", footer: { right: '[page] of [topage]' },
          no_background: false,
          disable_internal_links: false,
          image: true,
          layout: 'pdf.html',
          cover: "http://www.url.com/cover/#{params[:id]}",
          margin:  {   top:               10,
                       bottom:            10,
                       left:              10,
                       right:             10 },
          toc: {
                         text_size_shrink: 0.92,
                 header_text: "Table of Contents" }
end
```

If I delete the lines of "cover" and "toc" the footer renders well, but if i don't only the TOC is numerated. 
If I delete the toc, nothing is numerated.

**Comment by unixmonkey** [comment]
I don't know if I'm missing the point or something else is going on with your setup, but I'm pretty sure this is working fine for me.

I added your code to the [wicked_pdf_issues](https://github.com/unixmonkey/wicked_pdf_issues) repository in [this commit](https://github.com/unixmonkey/wicked_pdf_issues/commit/860474fbbc5117ef5420c20e1f0efbe597c1c028)

And it appears to be doing the right thing here:

https://wicked-pdf-issues.herokuapp.com/pages/issue_435.pdf

The cover itself isn't numbered, but the TOC and subsequent pages are.

I even made sure to use the version of `wkhtmltopdf-binary-edge` you specified.
Do you have `config/initializers/wicked_pdf.rb` setup and pointing to a different version of the executable?

**Comment by klatooine** [comment]
Lol, bundle update did the trick, but neither wkhtmltopdf nor wicked_pdf were updated.

Thank you and sorry

**Comment by unixmonkey** [comment]
No problem! I'm glad you got it working!
