### ISSUE TITLE
How does Wicked PDF Determine when to use /tmp

### ISSUE THREAD

**Issue by nathantechie9** [mileszs/wicked_pdf#437]
Is there a threshold for using /tmp? Like memory? File size? I am trying to determine if /tmp is only written to when the pdf is a certain size. Because I am getting the error. It looks like the tmp file isn't being created.

PDF could not be generated! Command Error: Error: Failed loading page file:////tmp/wicked_header_pdf20150

**Comment by unixmonkey** [comment]
WickedPDF creates a temp file for every PDF render, as well as header/footer renders.

A failure to load the page doesn't mean it failed to write the tempfile. Are you retrieving assets over HTTP instead of with abolute file:// path references? Are your documents complete and valid HTML?

You might be able to throw a debugger around here:

https://github.com/mileszs/wicked_pdf/blob/63803cbb30a9e122e63b8487c692dc8e5a1e4a66/lib/wicked_pdf.rb#L54

with `bundle open wicked_pdf`, and see what's happening.

Let me know how it goes!

**Comment by nathantechie9** [comment]
Thank you for the tips. I will try that out.

**Comment by nathantechie9** [comment]
Ah ok. You make sense. I am generating a new header each time over http. It sounds like I could just use an absolute path to a permanent header file, instead of generating a new one each time?

**Comment by unixmonkey** [comment]
WickedPDF will render your header and footer to tempfiles first, then include those files in the final call to `wkhtmltopdf` to build the PDF:

https://github.com/mileszs/wicked_pdf/blob/63803cbb30a9e122e63b8487c692dc8e5a1e4a66/lib/wicked_pdf/pdf_helper.rb#L84

**Comment by nathantechie9** [comment]
I think I can solve this by using --ignore-load-errors. I tried it manually and it ignored the segmentation fault error. How can I set that binary flag in the Rails config initializer for wicked? I can't find it in the docs.

**Comment by unixmonkey** [comment]
You should be able to do it like this on a case-by-case basis:

```ruby
render pdf: 'mypdf', extra: '--ignore-load-errors'
```

Or by adding it to `config/initializers/wicked_pdf.rb` like this:
```ruby
WickedPdf.config = {
  extra: '--ignore-load-errors'
}
```

Let me know how it goes!

**Comment by nathantechie9** [comment]
It didn't work. I got this error. What is wkhtmltopdf_lin ?

Aug 13 23:18:01 ip-10-100-32-138 kernel: [115852.295107]
wkhtmltopdf_lin[13493]: segfault at 0 ip           (null) sp
00007fff1a7b5118 error 14

**Comment by unixmonkey** [comment]
That's the Linux version of the `wkhtmltopdf` binary.

Try adding a space inside the quotes:
```ruby
WickedPdf.config = {
  extra: ' --ignore-load-errors '
}
```

**Comment by unixmonkey** [comment]
Did you get this working the way you want?

Please reopen if it's still an issue.
