### ISSUE TITLE
WickedPdf is not a module (TypeError)

### ISSUE THREAD

**Issue by silvio-ai** [mileszs/wicked_pdf#440]
I'm having this issue installing and trying to explore your gem in a new dummy project:
/wickedPdf/config/application.rb:9:in `<top (required)>': WickedPdf is not a module (TypeError)

I can't generate the initialiser nor running the server
Any idea what could be the issue?

Rails 4, new and clean project
Thanks in advance

**Comment by silvio-ai** [comment]
Sorry, ignore this, I was naming my app WickedPdf, so conflict of naming...

**Comment by unixmonkey** [comment]
No problem! Thanks for letting us know.
