### ISSUE TITLE
Margin options in initializers/wicked_pdf.rb do not stick after first refresh

### ISSUE THREAD

**Issue by a-maas** [mileszs/wicked_pdf#441]
I'm using the WickedPdf Middleware to be able to print out specific pages as PDFs. Every page will have the same PDF options so I have put them into `config/initializers/wicked_pdf.rb`. After adding these options and restarting the server, the PDF renders with the correct margins. When I refresh the same page, the custom margins are now gone and are back to the default margins. I can't get the margins to show again until I restart the server again, which is less than ideal :smile: 

In my `config/initializers/wicked_pdf.rb`:
```ruby
WickedPdf.config = {
  exe_path: '/usr/local/bin/wkhtmltopdf',
  margin: { top:    5,
            bottom: 5,
            left:   5,
            right:  5 },
  page_size: 'Tabloid',
  orientation: 'Landscape'
}
```

In my `config/application.rb`:
```ruby
require File.expand_path('../boot', __FILE__)
require 'rails/all'
Bundler.require(*Rails.groups)

module MyApp
  class Application < Rails::Application
    config.active_record.raise_in_transactional_callbacks = true
    config.eager_load_paths += ["#{config.root}/lib"]
    require 'wicked_pdf'
    config.middleware.use WickedPdf::Middleware
  end
end
```

**Comment by unixmonkey** [comment]
Options concerned with rendering are usually removed from the options hash at render-time.
This is to prevent any unintended behavior or name collisions with actual options that should be passed to `render`.

However, you can pass your render-specific options into the middleware by providing them in the second argument to `use` like this:

```ruby
wicked_pdf_options = {
  margin: { top: 5, bottom: 5, left: 5, right: 5 },
  page_size: 'Tabloid',
  orientation: 'Landscape'
}
config.middleware.use WickedPdf::Middleware, wicked_pdf_options
```

And they should work across requests.

Let me know how it goes!

**Comment by a-maas** [comment]
Thanks so much for your reply @unixmonkey. I put the options into `application.rb` (I'm using Rails 4) as the second parameter to `use`, but the issue with the margin still persists. The page size and orientation stay persistent, but the margin goes away after the first refresh still.

**Comment by unixmonkey** [comment]
Thanks for letting me know it's still an issue; I think I see why.

When removing these options before passing to render (like `options.delete(:some_key)`), we are actually modifying the original `options` hash in memory. It would be better if we worked off of a copy of `options` inside each method that does that kind of thing.

This should be as simple as adding something like this to the tops of methods that need them:
```ruby
def parse_options(options)
  options = options.dup
  ... other stuff
end
```

Do you think you could give that a shot, try it out, and send a pull request?

If not, I'll try and get to it soon.
