### ISSUE TITLE
wkhtmltopdf creates expected pdf but wicked_pdf does not

### ISSUE THREAD

**Issue by KCErb** [mileszs/wicked_pdf#450]
Hi there,

Thanks for the great tool. I've been able to get everything working well except for a chart I'm trying to insert into the page (via lazy high charts).

The issue is that the pdf just doesn't show the chart. To test other aspects I've enabled the dubug parameter (`?debug=1`) and obtained the html. It looks fine, is styled fine, javascript is fine, everything works!

Next I saved that html and ran the command-line tool directly:

```
$ wkhtmltopdf debug.html debug.pdf
Loading pages (1/5)
Resolving links (2/5)                                              
Counting pages (3/5)                                                      
Printing pages (5/5)                                                      
Done             
```

The pdf it produced is great, the chart is in there and everything!

But for some reason, if I go to my pdf page (without the debug option) then I get everything styled correctly etc but I get a blank spot on the page where the chart belongs.

I tried using `redirect_delay` when I was on `wkhtmltopdf` 0.9.9, then I updated to the `edge` binary gem:

```
$ wkhtmltopdf -V
wkhtmltopdf 0.12.2.1 (with patched qt)
```

and used `javascript_delay` of 5 seconds. Still no chart.

Any suggestion of what to try debugging next?

**Comment by unixmonkey** [comment]
Are you using any of the `wicked_pdf_*` asset helpers in your views? If you are, try without, if you aren't try with.

Does a longer `javascript_delay` make a difference?

Can you gist me what your view file and debug.html look like?

**Comment by KCErb** [comment]
> Are you using any of the wicked_pdf_* asset helpers in your views?
Yes in a layout called `pdf.haml` I'm pulling in all of the application's assets like so:

```haml
!!!
%html
  %head
  %title Test PDF
  = wicked_pdf_stylesheet_link_tag    "application", :media =>"all"
  = wicked_pdf_javascript_include_tag "application"
  %body
    = yield
```

> try without

I changed the layout to:

```haml
!!!
%html
  %head
  %title Test PDF
  = stylesheet_link_tag    "application", :media =>"all"
  = javascript_include_tag "application"
  %body
    = yield
```

And the pdf has definitely lost it's style, but not charts.


> Does a longer javascript_delay make a difference?

Changed it to 60 seconds and still no chart.

> Can you gist me what your view file and debug.html look like?

Sure. I'm still just testing so the view file is very simple:

```haml
-# report.pdf.haml
%h2 Testing a High Chart

= high_chart("chart-div", @chart)
```

As you may guess from my "include entire application's js and css" approach to debugging this, the html file is quite large: 43k lines! So I'll only give a gist of the content of the body (much smaller): https://gist.github.com/KCErb/bdf944d259be5f56b937

The head is generated from `application.cs` and `application.js` and includes bootstrap and jquery like so:

```js
//= require jquery
//= require jquery_ujs
//= require jquery-ui/slider
//= require turbolinks
//= require bootstrap-sprockets
//= require highcharts
//= require highcharts/highcharts-more
//= require_tree .
```

```sass
/*
 *= require_tree .
 *= require jquery-ui/slider
 *= require_self
 */

@import "bootstrap-sprockets"
@import "bootstrap"
```

I can send you the full 1.4 MB html file some other way (chrome balked at pasting the whole thing into the gist textbox) so that you can see that in spite of the mountain of javascript it's able to produce the expected pdf in about 2 seconds.

Thanks for the quick response!

**Comment by KCErb** [comment]
While playing around this morning I did the following in an irb session

```
$ irb
2.1.2 :001 > require 'wicked_pdf'
 => true 
2.1.2 :002 > pdf = WickedPdf.new.pdf_from_html_file('/Users/KC/test/debug.html')
=> super long pdf output
2.1.2 :003 > File.open('/Users/KC/test/test.pdf', 'wb') do |file|
2.1.2 :004 >     file << pdf
2.1.2 :005?>   end
 => #<File:/Users/KC/test/test.pdf (closed)> 
```

And the pdf was fine. So I tried the same in my app and was able to email the pdf attachment *with chart* which is my end-goal anyways. Perhaps for now my workaround will be to create and save the html.

I'd be happy to do anything else needed to help with debugging such as making a minimal example app (that reproduces this error) for you to play with.

**Comment by unixmonkey** [comment]
That would be great.

If you like, there's already an app I use for debugging issues here at https://github.com/unixmonkey/wicked_pdf_issues

Fork that and add some code that reproduces the issue (or a mini app of your own), and I'll gladly take a look.

**Comment by KCErb** [comment]
Well that was fun!

Here's an app I created from scratch that seems to behave identically.

https://github.com/KCErb/chart_pdf_debug_app

I think stuff is explained decently in the index so just clone it, fire it off and read that. I'm happy to answer any questions.

If the send email part isn't working for you, that may be due to a bug I just fixed on the lazy high charts part of this: https://github.com/michelson/lazy_high_charts/pull/199 so you may need to pull down the latest version . . I'd put that in the gemfile but I've got to catch a bus :bus:

Thanks again!

**Comment by KCErb** [comment]
Hmm, I'm starting to think the problem lies in how I'm including my assets. I just ran into a similar problem with font-awesome. I'll be sure to post here if I figure it out.

**Comment by KCErb** [comment]
Just noticed [this issue](https://github.com/mileszs/wicked_pdf/issues/277) and fix and it worked for my font-awesome issue. I'll see what that can tell me about my high charts issue . . .

**Comment by KCErb** [comment]
Yup, that was it! Here's [the commit](https://github.com/KCErb/chart_pdf_debug_app/commit/9336e5f10240ea85d585c82b3bc1464b9bc63bbf) that fixes the app.

If someone from the future runs into similar problems the summary is: for some reason including the javascript in-line doesn't work. You need to include a cdn reference instead.

Does that sound right to you @unixmonkey?

**Comment by unixmonkey** [comment]
It looks to me like you didn't add application.js to the precompile list like specified in [the README](https://github.com/mileszs/wicked_pdf#asset-pipeline-usage)

Without that, there is no actual compliled application.js for `wicked_pdf` to use with the `wicked_pdf_javascript_include_tag` helper.

In development mode, Rails treats a request for that as a request from all the things it requires, but not the actual file. It likely would have behaved fine in production.

Try reverting that last commit, and adding application.js and application.css to `config/initializers/assets.rb`, and see how that goes.

__config/initializers/assets.rb__
```ruby
Rails.application.config.assets.precompile += %w( application.js application.css )
```

**Comment by KCErb** [comment]
Oh I missed that part in the README. Probably my lazy brain seeing the word Heroku and skipping. Thanks for the tip!

Unfortunately I tried what you suggested (revert and edit) and put in on a new [branch called precompile](https://github.com/KCErb/chart_pdf_debug_app/tree/precompile). It doesn't seem to have fixed the problem though.
