### ISSUE TITLE
How do you style ToC page ?

### ISSUE THREAD

**Issue by abhishekverma3189** [mileszs/wicked_pdf#457]
Below is how I render my PDF

      format.pdf {
        render pdf: "report_#{params[:id]}.pdf",
          cover: 'path/to/file',
          toc: {
            
          },
          footer: {
            :html => {
              template: "shared/reports/pdf/_report_footer.pdf.haml",
              layout: "layouts/#{layout}"
            }
          },
          template: "assessment_reports/#{template}",
          layout: "layouts/#{layout}",
          handlers: [ :haml ],
          margin: { :left => "0mm",:right => "0mm", :top => "0mm", :bottom => "0mm" },
          formats: [:pdf],
          locals: { :@view_mode => "pdf" }
      }

**Comment by unixmonkey** [comment]
According to [http://wkhtmltopdf.org/usage/wkhtmltopdf.txt](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt):

```
toc [TOC OPTION]...
  All options that can be specified for a page object can also be specified for
  a toc, further more the options from the TOC Options section can also be
  applied. The table of content is generated via XSLT which means that it can be
  styled to look however you want it to look. To get an aide of how to do this
  you can dump the default xslt document by supplying the
  --dump-default-toc-xsl
```

Let me know how it goes!
