### ISSUE TITLE
Images with wrong path when CDN schema is not specified

### ISSUE THREAD

**Issue by guilhermearaujo** [mileszs/wicked_pdf#458]
My application has the asset host set like this:
`config.action_controller.asset_host = '//cdn.domain.com'`

When `wicked_pdf_image_tag 'logo.png'` is executed, the output tag will be:
`<img alt="Logo" src="file://///cdn.domain.com/assets/images/logo-b375ce445490ac078500cbf7bda369d3.png">`

I think this happens because the asset host has no explicit schema (`http:` or `https:`), therefore the `file:///` is prepended to the path.

We're using version 0.9.4 of Wicked PDF.

**Comment by unixmonkey** [comment]
Please try against `master`

__Gemfile__
```ruby
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
```

I'm pretty sure there are some very recent merges that address this.

**Comment by guilhermearaujo** [comment]
I will try, thanks!

**Comment by unixmonkey** [comment]
Since I haven't heard back, I'm assuming things worked out with using `master`, and FYI, I've just published a new gem version, so you don't have to pin to GitHub.

**Comment by guilhermearaujo** [comment]
Sorry for taking so long.
I tested it and it worked.
I also have just updated the gem and it is OK.

👍🏻
