### ISSUE TITLE
undefined method `pathname' for nil:NilClass in v1.0, but v. 0.11.0 works well

### ISSUE THREAD

**Issue by igorkasyanchuk** [mileszs/wicked_pdf#463]
In layout:
  = wicked_pdf_stylesheet_link_tag "application"

app/assets/stylesheets/application.css
/*
  *= require_self
  *= require font-awesome
  *= require base.css.scss
  *= require bootstrap
  *= require style
*/

Error:
wicked_pdf (1.0.0) lib/wicked_pdf/wicked_pdf_helper.rb:92:in `asset_pathname'
wicked_pdf (1.0.0) lib/wicked_pdf/wicked_pdf_helper.rb:71:in `wicked_pdf_asset_path'
wicked_pdf (1.0.0) lib/wicked_pdf/wicked_pdf_helper.rb:49:in `block in wicked_pdf_stylesheet_link_tag'
wicked_pdf (1.0.0) lib/wicked_pdf/wicked_pdf_helper.rb:45:in `gsub'
wicked_pdf (1.0.0) lib/wicked_pdf/wicked_pdf_helper.rb:45:in `wicked_pdf_stylesheet_link_tag'
app/views/layouts/pdf.pdf.slim:6:in `_app_views_layouts_pdf_pdf_slim__1705478257647234968_70115923166080'

Rails 4.2.5 (but for 4.2.4 same)

With wicket_pdf version 0.11.0 everything works correctly.

**Comment by igorkasyanchuk** [comment]
more stack trace with local version

/Users/igorkasyanchuk/Projects/wicked_pdf/lib/wicked_pdf/wicked_pdf_helper/assets.rb:67:in `asset_pathname'
/Users/igorkasyanchuk/Projects/wicked_pdf/lib/wicked_pdf/wicked_pdf_helper/assets.rb:46:in `wicked_pdf_asset_path'
/Users/igorkasyanchuk/Projects/wicked_pdf/lib/wicked_pdf/wicked_pdf_helper/assets.rb:24:in `block in wicked_pdf_stylesheet_link_tag'
/Users/igorkasyanchuk/Projects/wicked_pdf/lib/wicked_pdf/wicked_pdf_helper/assets.rb:20:in `gsub'
/Users/igorkasyanchuk/Projects/wicked_pdf/lib/wicked_pdf/wicked_pdf_helper/assets.rb:20:in `wicked_pdf_stylesheet_link_tag'
app/views/layouts/pdf.pdf.slim:6:in `_app_views_layouts_pdf_pdf_slim__3275615023577928730_70320479552460'

**Comment by igorkasyanchuk** [comment]
Issue happens because in CSS I've

url("../images/glyphicons-halflings-white.png");

And then 

[3] pry(#<#<Class:0x007f82dc6c19a0>>)> Rails.application.assets.find_asset("../images/glyphicons-halflings.png")
=> nil

**Comment by igorkasyanchuk** [comment]
Not sure if I need to make a PR, but I can .... but what is the desired solution?

I've made this PR https://github.com/mileszs/wicked_pdf/pull/464, at least my app works now.

The other fix is to change CSS to use asset-path

**Comment by unixmonkey** [comment]
Thanks for the PR! It's been merged!

**Comment by woohoou** [comment]
if I do a bundle update of the gem, this will be fix it automatically? or I need to install the master branch.

**Comment by woohoou** [comment]
I confirm that it works in master branch

**Comment by unixmonkey** [comment]
`bundle update wicked_pdf` should work for you now. I just pushed `1.0.1` to Rubygems.
