### ISSUE TITLE
issue locating wkhtmltopdf

### ISSUE THREAD

**Issue by mustmodify** [mileszs/wicked_pdf#472]
I'm sorry to even be adding a ticket; I see that there are a ton of "hey please solve my problem" issues around. And if you give me a push about what might be wrong I'll try to put together a PR or whatever. Here's a weird issue:

tail -f log/production.log
```
... snip ...
["/home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf", "-q", "file:///tmp/wicked_pdf20151202-2932-qgb7lz.html", "/tmp/wicked_pdf_generated_file20151202-2932-1s8i959.pdf"]
Error: PDF could not be generated!
 Command Error: An exception occurred running /home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf:

wkhtmltopdf-binary is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

Backtrace:

 { } in Kernel(Object)#replace_gem at /opt/rubies/rbx-2.5.2/gems/gems
                                      /bundler-1.7.12/lib/bundler
                                      /rubygems_integration.rb:256
                 Object#__script__ at /home/production/mako2/shared/bundle/rbx
                                      /2.1/bin/wkhtmltopdf:22
   Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
   Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
            Rubinius::Loader#script at kernel/loader.rb:655
              Rubinius::Loader#main at kernel/loader.rb:809

I, [2015-12-02T15:40:32.189743 #2932]  INFO -- : [Rollbar] Scheduling payload
I, [2015-12-02T15:40:32.190027 #2932]  INFO -- : [Rollbar] Sending payload
I, [2015-12-02T15:40:32.232187 #2932]  INFO -- : [Rollbar] Success
I, [2015-12-02T15:40:32.232443 #2932]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=4dc5a29d-da2a-4814-922b-d595c15d53cd (only available if report was successful)
D, [2015-12-02T15:40:32.232655 #2932] DEBUG -- : [Rollbar] Exception uuid saved in env: 4dc5a29d-da2a-4814-922b-d595c15d53cd
F, [2015-12-02T15:40:32.238428 #2932] FATAL -- :
RuntimeError (Error: Failed to execute:
["/home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf", "-q", "file:///tmp/wicked_pdf20151202-2932-qgb7lz.html", "/tmp/wicked_pdf_generated_file20151202-2932-1s8i959.pdf"]
Error: PDF could not be generated!
 Command Error: An exception occurred running /home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf:

wkhtmltopdf-binary is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

Backtrace:

 { } in Kernel(Object)#replace_gem at /opt/rubies/rbx-2.5.2/gems/gems
                                      /bundler-1.7.12/lib/bundler
                                      /rubygems_integration.rb:256
                 Object#__script__ at /home/production/mako2/shared/bundle/rbx
                                      /2.1/bin/wkhtmltopdf:22
   Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
   Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
            Rubinius::Loader#script at kernel/loader.rb:655
              Rubinius::Loader#main at kernel/loader.rb:809
):
  app/controllers/reports_controller.rb:10:in `pob_summary'
  app/controllers/reports_controller.rb:7:in `pob_summary'
```

and just in case that wasn't clear: 

```
production@esoteric:~/mako2/current$ grep wk Gemfile.lock
    wkhtmltopdf-binary (0.9.9.3)
  wkhtmltopdf-binary

production@esoteric:~/mako2/current$ ls /home/production/mako2/shared/bundle/rbx/2.1/bin/w* -l
-rwxr-xr-x 1 production production 533 Oct  6 14:19 /home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf
```

but wkhtmltopdf is already installed on the server (and with a newer version).

```
production@esoteric:~/mako2/current$ which wkhtmltopdf
/usr/local/bin/wkhtmltopdf
```

I created config/initializers/wicked.rb and did this clever thing:

```
WickedPdf.config = {exe_path: `which wkhtmltopdf`}
```

but as usual trying to be clever did not work. It found the gem version:

```
/home/production/mako2/shared/bundle/rbx/2.1/bin/wkhtmltopdf
```

So then I changed that init file to:

```
WickedPdf.config = {exe_path: '/usr/local/bin/wkhtmltopdf'}
```

I would rather it find that on its own. /usr/local/bin is in the path (both because it was found via which as because I checked)... but it still doesn't work. 

Why why why?
============

**Comment by brixen** [comment]
@mustmodify what are you using to set up your Ruby environment (eg chruby, RVM, rbenv)?

It sort of looks like the environment is not set up correctly when the subcommand runs. Do you bundle into a local path so everything is packaged up and isolated for deployment? Does this work in a dev environment but fail in production?

**Comment by unixmonkey** [comment]
So it is working with this config, correct?
```ruby
WickedPdf.config = {exe_path: '/usr/local/bin/wkhtmltopdf'}
```

When commands are run through `bundle exec` (which wicked_pdf does in the absence of an `exe_path` config option), bundler will preferentially run binaries in the bundle, and return them when `which` is called. See [Environment Modifications](http://bundler.io/man/bundle-exec.1.html).

If you need to run a different binary in your dev/test environments, you can make the config dynamic like this:
```ruby
WickedPdf.config = {
  exe_path: (Rails.env.production? ? '/usr/local/bin/wkhtmltopdf' : `which wkhtmltopdf`)
}
```

**Comment by mustmodify** [comment]
capistrano, chruby, rbx-2.5.2. 

It was initially working in dev, and then it worked when I added wkhtmltopdf in dev, but when I removed wkhtmltopdf from my gemfile, I started having the same issue... that it was trying to use the binary from the gem even though that gem wasn't in the gemfile. So I removed the wkhtmltopdf gems from the local store and it was good again.

**Comment by unixmonkey** [comment]
Ah, but removing a gem from your `gemfile`, still leaves the gem installed, and hence the binary is still installed, and I'm not sure what bundler would/should do in that case. If you were using Rbenv, I might suggest you `rbenv rehash` to build new binstubs.

**Comment by mustmodify** [comment]
That's true. But my question is why the binary seemed to work when the gem was in the Gemfile but did not work when it wasn't. Mysterious.

**Comment by mustmodify** [comment]
Especially since the one I compiled did work.
