### ISSUE TITLE
Unknown long argument --toc-depth

### ISSUE THREAD

**Issue by joshuapinter** [mileszs/wicked_pdf#478]
When using `toc: { depth: 3 }` as the [README documentation](https://github.com/mileszs/wicked_pdf#advanced-usage-with-all-available-options) shows, it produces the following error from `wkhtmltopdf`:

``` bash
Command Error: Unknown long argument --toc-depth
```

This is running on version 0.12.2.1 of `wkhtmltopdf`.

It looks like that option is no longer supported in `wkhtmltopdf` or it may have been renamed to `--outline-depth` as per http://wkhtmltopdf.org/usage/wkhtmltopdf.txt.

**Comment by unixmonkey** [comment]
`wicked_pdf` supports syntaxes for both the older versions of `wkhtmltopdf` as well as the newer ones.

It would be helpful to note in the README or wiki, that some options are only supported in one version or another.

**Comment by joshuapinter** [comment]
Gotcha.

Is it possible to check the version and adjust the syntax based on that?

**Comment by unixmonkey** [comment]
Possibly, if there's an equivalent in both versions ([you can do version comparison like this](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L176)), although I think I might prefer you use the commands that map to the correct version of `wkhtmltopdf` that you are using. WickedPDF is a wrapper around `wkhtmltopdf`, and not really its own DSL.

**Comment by joshuapinter** [comment]
I agree with you. Updating the docs to indicate this would be the best approach. If I make a simple PR with some mods to the README, would that be work?

**Comment by unixmonkey** [comment]
Yes, please. That would be great!

**Comment by joshuapinter** [comment]
Finally got around to adding a little quip in the README to warn users that the options available is based on the specific version of wkhtmltopdf that they are using. PR found here: https://github.com/mileszs/wicked_pdf/pull/832
