### ISSUE TITLE
undefined method `info' for "1172fb1556ec4433ae81447c":String

### ISSUE THREAD

**Issue by shivabhusal** [mileszs/wicked_pdf#479]
Hey Guys; I am stuck with this issue can any one help?

---
NoMethodError in MyController#billing
undefined method `info' for "1172fb1556ec4433ae81447c":String

Extracted source (around line #14):
              
```ruby
    respond_to do |format|
        format.pdf do
          target_partial_path = Rails.root + '/app/views/my/billing/_billing_history.pdf.slim'
          file_name = "billing_history_#{Time.now.to_i}.pdf"
          render file: target_partial_path,
                 pdf: file_name, 
                 locals: {
                            billing_histories: @billing_histories
                        }
        end
        format.html { render 'my/billing' }
     end

```

Rails Version: `4.2.0`
Ruby : `2.1`
Machine : `Ubuntu 14.04`
Wicked PDF : `0.11.0`

**Comment by unixmonkey** [comment]
Inside WickedPDF, there is a place where it calls `logger.info` if `logger` exists ([here](https://github.com/mileszs/wicked_pdf/blob/03adff29738835e4729a232a2d3c53266fa1d3b2/lib/wicked_pdf/pdf_helper.rb#L41)).

This is supposed to be the Rails logger. If you have another method named `logger` that returns the above string, it may be possible that is being called instead.

Let me know if this helps!

**Comment by shivabhusal** [comment]
Thanks man, looks like I have created a method called logger in application controller; this might be have been called everytime `WickedPDF` wanted to call `Rails Logger`

thanks again

**Comment by unixmonkey** [comment]
I just pushed v 1.0.4 of the gem, which checks that `logger.respond_to?(:info)`, so this shouldn't be a problem for you or anyone else (unless your logger also responds to info, in which case, it is probably adhering to the standard logger convention).

Please let me know and/or reopen if you have any issues!
