### ISSUE TITLE
Need to embed audio file in pdf

### ISSUE THREAD

**Issue by complitech** [mileszs/wicked_pdf#482]
I want to embed audio file into pdf but audio_tag is not working in pdf. How I can embed audio to pdf file?

**Comment by unixmonkey** [comment]
WickedPDF is a wrapper around `wkhtmltopdf`, which essentially loads a website up in a headless web browser, and does a print-to-pdf.

Although it is possible to embed audio in a PDF with some of the Acrobat tools, it is not possible with `wkhtmltopdf` or WickedPDF. Sorry.
