### ISSUE TITLE
Embed audio into pdf

### ISSUE THREAD

**Issue by shefaleeComplitech** [mileszs/wicked_pdf#484]
I need to play audio inside generated pdf file. audio tag does not working for it. Is there any way I can embed directly audio not link to audio file.

**Comment by unixmonkey** [comment]
Duplicate of #482.

WickedPDF is a wrapper around wkhtmltopdf, which essentially loads a website up in a headless web browser, and does a print-to-pdf.

Although it is possible to embed audio in a PDF with some of the Acrobat tools, it is not possible with wkhtmltopdf or WickedPDF. Sorry.
