### ISSUE TITLE
Issues with Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by andymilk** [mileszs/wicked_pdf#485]
When I open a PDF generated by wicked_pdf in Adobe Acrobat Reader DC, there are a couple issues:

1.  If I add a Sticky Note to it and save the file, the Sticky Note shows on every page of the PDF.

2.  On a PC, I get an error from Acrobat:  "The document could not be saved.  There was a problem reading this document. (23)"

Has anyone else come across this?  Is there something I can set in the wicked_pdf options to prevent these issues?

Thanks

**Comment by jspillers** [comment]
Same problem... when I render my PDF in the controller via

```
        render(
          pdf: 'scorecard',
          template: 'scorecards/index.pdf.haml',
          show_as_html: params.key?('debug'),
          javascript_delay: 1000,
        )
```

I get this from  Acrobat Reader DC:

![screen shot 2016-03-22 at 11 59 37 am](https://cloud.githubusercontent.com/assets/2891/13958274/df4efd22-f025-11e5-9fe6-8225b97dfc56.png)

**Comment by unixmonkey** [comment]
This is a problem `wkhtmltopdf`, which powers the headless browser that creates a PDF based on the HTML `wicked_pdf` feeds it.

Check the issues tracker at https://github.com/wkhtmltopdf/wkhtmltopdf and see if there is something there about this, or post your issue there. A cursory search didn't turn up anything for me, though.
