### ISSUE TITLE
How pass option without value?

### ISSUE THREAD

**Issue by gf59ru** [mileszs/wicked_pdf#490]
I tries to generate Pdf with js arcgis map inside.
When I set `show_as_html` as `true`, page with map correctly renders and shows in browser.
But when I set it to `false`, pdf file renders without map.

I unsuccesfully tried to enlarge `javascript_delay`, then read `wkhtmltopdf.exe` help (`wkhtmltopdf.exe -H` command)
There I found interesting arguments:
<pre>
--stop-slow-scripts		Stop slow running javascripts (default)
--no-stop-slow-scripts	Do not Stop slow running javascripts
</pre>

I supposed that is due to large arcgis javascript and css library and tried to use this option. But unlike other options as `javascript_delay` or `show_as_html` these han't values when `render` method assumed passing options in key-values mode.

I try two variants: with `nil` and `true` values:
```ruby
render :pdf => 'pdf',
       :no_stop_slow_scripts => nil,
       # :no_stop_slow_scripts => true,
       :javascript_delay => 3000,
       :template => 'pdf.pdf',
       :disposition => 'attachment',
       :show_as_html => false
```

Option is not passed when value is `nil`:
<pre>
***************WICKED***************
  Rendered qwe/show.pdf.erb (45.0ms)
"***************[\"c:\\\\Program Files (x86)\\\\wkhtmltopdf\\\\bin\\\\wkhtmltopdf.exe\", \"--javascript-delay\", \"3000\", \"file:///C:/Users/qwe/AppData/Local/Temp/wicked_pdf20160211-3536-a6zul9.html\", \"C:/Users/qwe/AppData/Local/Temp/wicked_pdf_generated_file20160211-3536-4gi196.pdf\"]***************"
  Rendered text template (0.0ms)
</pre>
And pdf renders without map again.

And error causes when value is `true`:
<pre>
***************WICKED***************
  Rendered qwe/show.pdf.erb (46.0ms)
"***************[\"c:\\\\Program Files (x86)\\\\wkhtmltopdf\\\\bin\\\\wkhtmltopdf.exe\", \"--javascript-delay\", \"3000\", \"--no-stop-slow-scripts\", \"true\", \"file:///C:/Users/qwe/AppData/Local/Temp/wicked_pdf20160211-3536-phdilw.html\", \"C:/Users/qwe/AppData/Local/Temp/wicked_pdf_generated_file20160211-3536-1oqq6td.pdf\"]***************"
Completed 500 Internal Server Error in 8140ms (ActiveRecord: 251.1ms)

RuntimeError (Error: Failed to execute:
["c:\\Program Files (x86)\\wkhtmltopdf\\bin\\wkhtmltopdf.exe", "--javascript-delay", "3000", "--no-stop-slow-scripts", "true", "file:///C:/Users/qwe/AppData/Local/Temp/wicked_pdf20160211-3536-phdilw.html", "C:/Users/qwe/AppData/Local/Temp/wicked_pdf_generated_file20160211-3536-1oqq6td.pdf"]
Error: PDF could not be generated!
 Command Error: Loading pages (1/6)
[>                                                           ] 0%
[===>                                                        ] 5%
[======>                                                     ] 10%
[==================>                                         ] 30%
[=================================>                          ] 55%
Error: Failed loading page http://true (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
</pre>
Option was passed to executable file, but `true` value was passed too as another yet argument!

But how can I just pass option without value, is it possible?
Or may be there are other ways to fix bug with map missing in pdf?

**Comment by unixmonkey** [comment]
What version of `wkhtmltopdf` are you using? What version of `wicked_pdf`?

For those type of arguments, you are expected to pass `true` as the value, and `wicked_pdf` should know whether to omit the value for that argument or not. That is happening [here](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L324)

It looks like perhaps this should be a `:boolean` type instead of `nil`.

Can you verify if changing that makes a difference for you? You can check with `bundle edit wicked_pdf`, and change that line, then restart your local development server. If that works, please let me know or send a pull request. It would also be nice if that option were listed in the full listing of the README.

**Comment by gf59ru** [comment]
Yes, it helped - `no_stop_slow_scripts` option passes correctly now
I created pull request
But map is still not shows in Pdf, only in Html :(
How can I debug Pdf generating?
`wkhtmltopdf` version is `0.12.3.1`, `wicked_pdf` version is `1.0.4`

**Comment by gf59ru** [comment]
I tries use `wkhtmltopdf` directly
It doesn't work in Windows (generated pdf file doesn't contain map) but in Linux works.
I creates [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2801) at `wkhtmltopdf` repository
Thanks!
