### ISSUE TITLE
PDF doesn't show same thing as debug

### ISSUE THREAD

**Issue by javimbk** [mileszs/wicked_pdf#513]
I have some troubles displaying a page full of charts built with C3.js with WickedPDF.

Here are the differences between the PDF and `show_as_html: params.key?('debug')`:

[Graph 1 PDF](http://puu.sh/nWQex/75083b8bf8.png) vs. [Graph 1 Debug](http://puu.sh/nWQbj/30c858eae7.png) (This one's weird because you can almost see it on the PDF)
[Graph 2 PDF](http://puu.sh/nWQgW/6f2054c995.png) vs. [Graph 2 Debug](http://puu.sh/nWQhN/f78e39b53f.png)
[Graph 3 PDF](http://puu.sh/nWQiN/674e948abc.png) vs. [Graph 3 Debug](http://puu.sh/nWQjy/a0ca3d2f9e.png)

I already tried increasing `javascript_delay`to a huge number but that doesn't do anything. It's not a matter of Wicked not having enough time to display the charts.

Also, I've included the correct `wicked_pdf_stylesheet_link_tag` and `wicked_pdf_javascript_include_tag` , otherwise the charts on debug wouldn't be showing correctly.

I would appreciate the help, I can't think of any other way to debug this other than using the `debug` function and a lot of tries I've already done. On debug everything works correctly.

**Comment by unixmonkey** [comment]
`javascript_delay` tells `wkhtmltopdf` to wait x milliseconds before executing any javascript (to make sure all the HTML fully rendered?).

You might have more luck with `no_stop_slow_scripts: true`, or perhaps specifying (in CSS) the width of the viewport (since it looks like things are being shrunk).

Let me know how it goes!

**Comment by baramik** [comment]
@unixmonkey javascript_delay this option seems to be working. I was facing the same issue with highcharts. Hope this will help somebody. Thanks

**Comment by javimbk** [comment]
@unixmonkey , sorry for not writing back on this one.
You were totally right, it was the `javascript_delay` mixed with CSS not being specified. So I could solve it with a mix of the two.
