### ISSUE TITLE
Shellescape-ing is escaping too much 

### ISSUE THREAD

**Issue by stevenharman** [mileszs/wicked_pdf#514]
After updating to the latest `wicked_pdf` I noticed the `title` of generated PDFs had escape characters (`\`) in them. I believe this is related to the recent change to `shellescape` options [024e74928dc3de49abfb6b326746829e6ae91bb2]. Here's the log output from a real PDF generation on our system. I added a `footer: { left: 'Footer with spaces' }` option to show the extra escaping there, and also in the `title` option.

> `"***************[\"/usr/local/bin/wkhtmltopdf\", \"-q\", \"--orientation\", \"Portrait\", \"--page-size\", \"Letter\", \"--title\", \"Inspection\\\\ Report:\\\\ 3\\\\ -\\\\ Case\\\\ 1021F\", \"--image-dpi\", \"300\", \"--image-quality\", \"90\", \"--margin-top\", \"35\", \"--margin-bottom\", \"12\", \"--margin-left\", \"0\", \"--margin-right\", \"0\", \"--header-spacing\", \"3\", \"--header-html\", \"file:////var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_header_pdf20160329-62966-tl3oqd.html\", \"--footer-left\", \"Footer\\\\ with\\\\ spaces\", \"file:////var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_pdf20160329-62966-zrrl6d.html\", \"/var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_pdf_generated_file20160329-62966-1yi7ial.pdf\"]***************"`

The same thing, in a copy/paste friendly format:
```
"***************[\"/usr/local/bin/wkhtmltopdf\", \"-q\", \"--orientation\", \"Portrait\", \"--page-size\", \"Letter\", \"--title\", \"Inspection\\\\ Report:\\\\ 3\\\\ -\\\\ Case\\\\ 1021F\", \"--image-dpi\", \"300\", \"--image-quality\", \"90\", \"--margin-top\", \"35\", \"--margin-bottom\", \"12\", \"--margin-left\", \"0\", \"--margin-right\", \"0\", \"--header-spacing\", \"3\", \"--header-html\", \"file:////var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_header_pdf20160329-62966-tl3oqd.html\", \"--footer-left\", \"Footer\\\\ with\\\\ spaces\", \"file:////var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_pdf20160329-62966-zrrl6d.html\", \"/var/folders/fn/v6thy0kj12x63fv112zrz9vr0000gn/T/wicked_pdf_generated_file20160329-62966-1yi7ial.pdf\"]***************"
```

**Comment by stevenharman** [comment]
In the end, `wicked_pdf` is using the multiple argument version of `popen3`, meaning it's bypassing the shell and each argument is passed as an argument to the command itself. When this happens, my understanding is Ruby will escape those values for you, so you need not explicitly `shellescape` them.

**Comment by raykin** [comment]
So does it cause the builtin page string failed?
```shell
"***************[\"/Users/raykin/studio/deltux/bin/wkhtmltopdf\", \"-q\", \"--footer-center\", \"Page\\\\ \\\\[page\\\\]\\\\ of\\\\ \\\\[topage\\\\]\", \"fi
le:////var/folders/_v/1zky8zxd113f7f2dbq_d2fj00000gn/T/wicked_pdf20160404-62151-1nla5a3.html\", \"/var/folders/_v/1zky8zxd113f7f2dbq_d2fj00000gn/T/wicked_pd
f_generated_file20160404-62151-tvcxf6.pdf\"]***************"
```
The Page [page] of [topage] doesn't worked any more.

**Comment by unixmonkey** [comment]
I've reverted this in a new version of the gem: `1.0.6`.

Closing this thread, but reopening #432.
