### ISSUE TITLE
Fail to include CSS assets in production

### ISSUE THREAD

**Issue by pastullo** [mileszs/wicked_pdf#516]
Hello guys, 
i am successfully using 
`<%= wicked_pdf_stylesheet_link_tag "pdf" %>`
in development to load my asset. However in production this won't work anymore, and i can't really understand why.

Also opened a stackoverflow issue: [http://stackoverflow.com/questions/36354174/including-css-files-in-pdf-using-wicked-pdf-helpers](here)

**Comment by pastullo** [comment]
hey @unixmonkey what do you think about the issue above?
The problem is that in production on rails 4.2 the helper above do not work, which breaks obviously the app while it works great in development.

Maybe i am wrong, but i think that the helper should "just work" also in production and have some kind of simmetry

**Comment by unixmonkey** [comment]
Did you try `wicked_pdf_stylesheet_link_tag "pdf.scss.erb"`?

**Comment by muhic** [comment]
Hey @pastullo, in case you're using the asset pipeline, you should try including the files in your precompile list in `config/initializers/assets.rb` as described in the [Asset pipeline usage](https://github.com/mileszs/wicked_pdf#asset-pipeline-usage) section of the README. Then the include helpers should work once you precompile your assets in production

**Comment by IlkhamGaysin** [comment]
@pastullo I can to precompile your assets in your local machine. 
1. ``rake assets:clean``
2. ``rake assets:precompile``
And then you will be able to emulate work wicked_pdf in compiled assets.
If you don't include your files in your ``config/initializers/assets.rb`` then you CSS styles will not apply to your pdf template. You have to added them.

**Comment by g-ilham** [comment]
@pastullo I can to precompile your assets in your local machine. 
1. ``rake assets:clean``
2. ``rake assets:precompile``
And then you will be able to emulate work wicked_pdf in compiled assets.
If you don't include your files in your config/initializers/assets.rb then you CSS styles will not apply to your pdf template and you have to add them.

**Comment by pastullo** [comment]
@unixmonkey @dstrus hey guys,
i notice the change in 1.1.0, tested it in production and now 
`stylesheet_link_tag wicked_pdf_asset_base64('pdf') `

just works!

So i guess you fixed it! 👍

**Comment by unixmonkey** [comment]
Oh yeah, `wicked_asset_base64` didn't tap into sprockets before that change, but does now. :)

**Comment by pastullo** [comment]
btw @unixmonkey i made a PR to explain a bit better in the readme how to use the asset helpers together with the asset pipeline. I think the readme are not very clear about that. 

(https://github.com/mileszs/wicked_pdf/pull/592)
