### ISSUE TITLE
Missing 1.0.5 and 1.0.6 tags

### ISSUE THREAD

**Issue by yuku-t** [mileszs/wicked_pdf#517]
![image](https://cloud.githubusercontent.com/assets/96157/14271603/99bf0e80-fb35-11e5-9733-5715be0ce7b5.png)

so that some links in [CHANGELOG.md](https://github.com/mileszs/wicked_pdf/blob/master/CHANGELOG.md#compare-releases) are broken.

**Comment by unixmonkey** [comment]
Thanks for noticing!

I've pushed up those tags.
