### ISSUE TITLE
Rails 4 and I18n

### ISSUE THREAD

**Issue by MarinoGit** [mileszs/wicked_pdf#521]
Hi, 

First of all, thanks for your work.

Unless I am mistaken, I can´t see any option to automatic translate like I18n in html.erb templates. ¿This is a candidate for a new feature?

Thanks

**Comment by unixmonkey** [comment]
If you are using i18n's `translate('some.key')` or `I18n.t('some_key')` or `t('some_key')`, the views are run through the Rails renderer, and should be translated. No options required.

Does that help? Please reopen if you have any issues or questions!

**Comment by mateuyabar** [comment]
I had the same problem. It was because I was using t(".some.key"), and the controller+view were not infered correctly.
I have changed the keys to t("controller.view.some.key") and working now.

**Comment by lucasqueiroz** [comment]
@mateuyabar is there any way to fix it without using the complete scope? Maybe setting the default scope of that page? I don't want to write the whole scope for every translation... But if that is the only way, it's better than nothing.

**Comment by mateuyabar** [comment]
I don't know. There must be a better way, but that is how I fixed it.

**Comment by just4fun** [comment]
@mateuyabar - Same issue here, I can't use [lazy lookup](https://guides.rubyonrails.org/i18n.html#lazy-lookup) to get translations, but it's working for me to use full path as you suggested.
