### ISSUE TITLE
PDF from console file path error

### ISSUE THREAD

**Issue by chabgood** [mileszs/wicked_pdf#542]
I am on a mac el capitan,  I am using ROR 4.2.6.
Gems:
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
gem 'wkhtmltopdf-binary'

 I am getting a file load error:

WickedPdf.new.pdf_from_html_file('/Users/chabgood/projects/me/RYH/registeryourhorse/app/views/paypal_transactions/receipt.html.haml') --ignore-load-errors
"***************[\"/Users/chabgood/.rvm/gems/ruby-2.3.0@registeryourhorse/bin/wkhtmltopdf\", \"-q\", \"file:////Users/chabgood/projects/me/RYH/registeryourhorse/app/views/paypal_transactions/receipt.html.haml\", \"/var/folders/d0/w6rqqqrn7s77_xk5n8qj71c80000gn/T/wicked_pdf_generated_file20160525-19791-fykkjc.pdf\"]***************"
RuntimeError: Failed to execute:
["/Users/chabgood/.rvm/gems/ruby-2.3.0@registeryourhorse/bin/wkhtmltopdf", "-q", "file:////Users/chabgood/projects/me/RYH/registeryourhorse/app/views/paypal_transactions/receipt.html.haml", "/var/folders/d0/w6rqqqrn7s77_xk5n8qj71c80000gn/T/wicked_pdf_generated_file20160525-19791-fykkjc.pdf"]
Error: PDF could not be generated!
 Command Error: Error: Failed loading page file:////Users/chabgood/projects/me/RYH/registeryourhorse/app/views/paypal_transactions/receipt.html.haml (sometimes it will work just to ignore this error with --ignore-load-errors)
from /Users/chabgood/.rvm/gems/ruby-2.3.0@registeryourhorse/bundler/gems/wicked_pdf-fbf51da43aac/lib/wicked_pdf.rb:93:in `rescue in pdf_from_url'

**Comment by unixmonkey** [comment]
`pdf_from_html_file` requires the contents to be static HTML, and won't parse HAML.
Render it out first with something like this:
```ruby
WickedPdf.new.render_from_string(
  render_to_string(pdf: 'mydoc.pdf', template: 'paypal_transactions/receipt.html.haml')
)
```

Let me know how it goes!

**Comment by chabgood** [comment]
Would someone please update the readme?

**Comment by unixmonkey** [comment]
@chabgood Would you like to do that?

**Comment by chabgood** [comment]
Not really I have 2 side projects I am on right now.

**Comment by chabgood** [comment]
Oh btw, I get this error:

WickedPdf.new.render_from_string(render_to_string(pdf: 'mydoc.pdf', template: 'paypal_transactions/receipt.html.haml'))
NoMethodError: undefined method `render_to_string' for main:Object

and I tried this:

WickedPdf.new.render_from_string(WickedPdf.new.render_to_string(pdf: 'mydoc.pdf', template: 'paypal_transactions/receipt.html.haml'))
NoMethodError: undefined method `render_to_string' for #<WickedPdf:0x007fd7033ecf60>

**Comment by chabgood** [comment]
@unixmonkey , it is not working why is this closed?

**Comment by unixmonkey** [comment]
Because it isn't an issue with `wicked_pdf`, which wasn't designed to work from the console, but in the context of a controller. `render_to_string` is available in the controller context, but in the console, you need to access it a little differently.

Here's some code that should actually work from the Rails console.

```ruby
helper.view_paths = 'app/views'
html = helper.render(template: 'paypal_transactions/receipt', locals: {})
pdf_as_string = WickedPdf.new.pdf_from_string(html)
```

**Comment by chabgood** [comment]
OK, thanks.  I would need to create PDF on a job afterwards.

**Comment by amitdotagarwal** [comment]
> Because it isn't an issue with `wicked_pdf`, which wasn't designed to work from the console, but in the context of a controller. `render_to_string` is available in the controller context, but in the console, you need to access it a little differently.
> 
> Here's some code that should actually work from the Rails console.
> 
> ```ruby
> helper.view_paths = 'app/views'
> html = helper.render(template: 'paypal_transactions/receipt', locals: {})
> pdf_as_string = WickedPdf.new.pdf_from_string(html)
> ```

This won't work if you pass 

` page_size: 'A4',
               template: 'template_pdf/acb.pdf.erb',
               layout: 'layouts/pdf.html.erb',
               footer: {
                   center: 'Page [page] of [topage]',
                   font_size: '8',`
