### ISSUE TITLE
undefined method: asset_data_base_64

### ISSUE THREAD

**Issue by turgs** [mileszs/wicked_pdf#549]
In my `print.pdf.erb` i'm using
`<%= stylesheet_link_tag asset_data_base_64('application') %>`

but get an exception:

> NoMethodError at /invoices/1/print.pdf
> undefined method `asset_data_base_64' for #<#<Class:0x007fbca03471c8>:0x007fbca22d99f0>

my controller is:
```
  # GET /invoices/1/print
  def print
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice #{@invoice.id}"
      end
    end
  end
```

Is there something i'm missing?

**Comment by unixmonkey** [comment]
The name of the helper is `wicked_pdf_asset_base64`, but the README was showing `asset_data_base_64` as the name. I feel like this may have been transplanted from one of the issues where the base64 feature was first proposed with a different name.

I pushed a fix for the README to this project, but you can use it right away by changing your calling method to `wicked_pdf_asset_base64`.
