### ISSUE TITLE
Issue in rendering the header/footer in ubuntu 14.04

### ISSUE THREAD

**Issue by Karthikds** [mileszs/wicked_pdf#550]
Hi,
  I am using the below version gems to render my PDF
wicked_pdf - 0.11.0
wkhtmltopdf - 0.1.2
wkhtmltopdf-binary - 0.9.9.3.

Below is my controller cod
```
render :pdf => "#{@route.route_name} report", 
:template => 'reports/index.pdf.erb',
page_size: "A4",
:header => {:html => { :template=> 'reports/footer.html.erb'}
}
```
I am trying to render the header in the PDF pages. It works absolutely fine in Ubuntu 12.04, but not in 14.04.

Please help me out in this.

**Comment by Karthikds** [comment]
Issue is with wkhtmltopdf, Hence closing the issue here

**Comment by unixmonkey** [comment]
Have you tried updating WickedPDF and wkhtmltopdf? The 0.9.x version is pretty old, and I think I remember there being some relatively recent updates around headers and footers.

You could also try setting your footer margins to `0`, and giving the footer css a margin and padding of 0, as I think the margin/padding can obscure your content in headers and footers.

**Comment by Karthikds** [comment]
Thanks for the response, 
But except wicked_pdf, the other two are up-to date as pr rubygems.org.
I have updated the wicked_pdf to 1.0.6 and set the margin top & bottom to 0. But it still header/footer is not rendered.
