### ISSUE TITLE
WickedPdf.new..pdf_from_url() From sidekiq job, with token based authentication.

### ISSUE THREAD

**Issue by EminenceHC** [mileszs/wicked_pdf#554]
I am trying to use .pdf_from_url to generate a PDF. Localhost paths did not work until I moved this command to a sidekiq job per your suggestion. The URL is protected with authentication, so I added token based authentication. When I visit the URL with my token included, I see the show page that I want to generate a PDF for. However, when I put the URL inside WickedPdf.new..pdf_from_url():

pdf = WickedPdf.new.pdf_from_url("http://localhost:3000/intake_agreements/68?user_email=my@email.com&user_token=my-user-token")

I get the following error:

Permission denied
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

If I turn off authentication in the controller, the PDF does generate. What should I try?

**Comment by unixmonkey** [comment]
It looks to me like that `@` symbol or possibly the `&` may be breaking out of the shell command that gets fed into `wkhtmltopdf`. Try escaping or quoting, and paste the full output of the error if you keep having trouble.

**Comment by EminenceHC** [comment]
Your comment lead me to a solution.

If I do not escape the & key and @ symbol, wicked_pdf breaks. If I escape the & key, my token authentication breaks. 

My solution was to put it in double quotes, and then I didn't need to escape anything.

pdf = WickedPdf.new.pdf_from_url("'http://www.mysite.net/intake_agreements/68?user_email=my@email.com&user_token=my-user-token'")

Notice the single quote URL wrapped inside a double quote.
