### ISSUE TITLE
No styling in generated pdf when used as email attachment (Rails 4.2.0)

### ISSUE THREAD

**Issue by jessewmc** [mileszs/wicked_pdf#558]
I'm having what seems to be a very unusual problem. `wicked_pdf_stylesheet_link_tag` seems to be working whenever I straight up render a pdf as in
`render pdf: 'invoice', template: 'invoices/print', layout: false`
but if I render to string in controller and pass the string to a mailer, as in
`pdf = render_to_string pdf: 'invoice', template: 'invoices/print', layout: false`
and
`attachments['invoicedate.pdf'] = pdf`
the attachment pdf does not contain any styling. I have further tested by passing a debug param to the controller action that either mails as above, or manually sets response.body with the pdf string as below:
`response.body = render_to_string pdf: "invoice", template: 'invoices/print', layout: false`
Somehow this generates the correct pdf, even though the attachment is incorrect! I'm really at a loss.

**Comment by jessewmc** [comment]
Alright I was hoping this was some simple known issue but of course it's actually my own fault. For future reference: Rails (obviously in retrospect) looks up templates in render calls based on the current format. My render to string was in a controller action firing on an html (or js) request, and was therefore not grabbing my pdf template of the same name. I have switched to manually specifying the format in the render call and all is well.

**Comment by unixmonkey** [comment]
Thanks a lot for updating with your answer. I'm sure it will help others in the future.
