### ISSUE TITLE
Hanging when using Open3 in Mac OSX

### ISSUE THREAD

**Issue by Jellyfishboy** [mileszs/wicked_pdf#579]
WickedPdf gem version: 0.9.9
wkhtmltopdf version: 0.12.3
Operating system: El Capitan 10.11.6 (15G31)
Ruby: 2.3.0

I am currently trying to convert HTML to PDF with the above tool versions. However, it keeps on hanging at the current snippet of code in the `wicked_pdf.rb` file:

``` ruby
err = Open3.popen3(command) do |stdin, stdout, stderr|
      stderr.read
end
```

When I run the command manually through the `wkhtmltopdf` binary, it is successful. This means that it is something within the wicked_pdf gem.

Any ideas? I don't know much about the `Open3` library.

**Comment by Jellyfishboy** [comment]
This seems to happen the the `stderr.read` command is run https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L79

**Comment by unixmonkey** [comment]
@Jellyfishboy Can you please update `wicked_pdf` to the latest version and let me know if this solves your problem or not?

**Comment by vdombr** [comment]
There seems to be a problem with old wkhtmltopdf wrapper. Try to update wkhtmltopdf-binary to newer version.

**Comment by Jellyfishboy** [comment]
@unixmonkey @vdombr I have updated to the following versions and it is still hanging:
```sh
wicked_pdf (1.1.0)
wkhtmltopdf-binary (0.12.3.1)
```

I am using the `render_to_string` method for parsing the HTML:
```ruby
def create_pdf
        @pdf = WickedPdf.new.pdf_from_string(
            render_to_string(
                pdf: "#{Store.settings.name}-order-#{@order.id}.pdf",
                template: "themes/#{Store.settings.theme.name}/emails/orders/completed.html.erb",
                layout: "../themes/#{Store.settings.theme.name}/layout/email.html.erb"
            )
        )
end
```
https://github.com/Jellyfishboy/trado-pdf-invoice-module/blob/master/app/controllers/trado_pdf_invoice_module/admin/orders_controller.rb#L19

Any ideas as to why this is happening?

Screenshot of terminal:
![screen shot 2016-11-13 at 18 33 44](https://cloud.githubusercontent.com/assets/2140830/20245256/f2cebf04-a9cf-11e6-9310-f1d3ceced445.png)

**Comment by Jellyfishboy** [comment]
@vdombr @unixmonkey Any idea why this is happening? Still experiencing the same.

**Comment by unixmonkey** [comment]
Does switching the gem to `wkhtmltopdf_binary_gem` help? How about [installing the official binary for your platform](http://wkhtmltopdf.org/downloads.html)?
What version of your local operating system are you running?

**Comment by Jellyfishboy** [comment]
@unixmonkey I am currently using the `wkhtmltopdf-binary` gem to access the binary and my operating system is macOS Sierra `10.12.2`.

I will try installing the binary directly to see if this works.

**Comment by Jellyfishboy** [comment]
@unixmonkey It now works when using the installed Official binary rather than the gem, thanks a bunch!
