### ISSUE TITLE
Not working at all on Sierra OS

### ISSUE THREAD

**Issue by Loschcode** [mileszs/wicked_pdf#580]
I installed Sierra OS this morning on my Mac and i can't use Wicked PDF anymore. Here's the error : 

```
Error: Failed to execute:
["/Users/Loschcode/.rvm/gems/ruby-2.3.0/bin/wkhtmltopdf", "-q", "file:////var/folders/2w/lw3glw5d58g25qvv4cx6yk0m0000gn/T/wicked_pdf20161006-11772-t1lhv9.html", "/var/folders/2w/lw3glw5d58g25qvv4cx6yk0m0000gn/T/wicked_pdf_generated_file20161006-11772-1onzon8.pdf"]
Error: PDF could not be generated!
 Command Error: 
```

**Comment by Loschcode** [comment]
I ended up solving the problem by trying random changes on the fresh system, i don't know if it's related or not but you can try : 

- Update Xcode and activate it
- `bundle update`
- Removing entirely `wicked_pdf` and `wkhtmltopdf`then reinstall it
- Alternatively run the `wkhtmltopdf` binary directly from their site

Hope it helps :)

**Comment by amitsuryavanshi** [comment]
Facing the same issue after upgrading to Sierra. Removing entirely wicked_pdf and wkhtmltopdfthen reinstall it, is not working for me. Any help with this would be much appreciated.

**Comment by amitsuryavanshi** [comment]
Its working for me now after upgrading wkhtmltopdf-binary gem to lated 0.12.3 version.

**Comment by aquajach** [comment]
No need to reinstall `wicked_pdf` or `wkhtmltopdf`, but upgrade wkhtmltopdf-binary to 0.12.3 or later as @amitsuryavanshi said

**Comment by mhassaan** [comment]
Upgrading wkhtmltopdf-binary to 0.12.3 worked. thanks guys

**Comment by bhgames** [comment]
Upgraded to 0.12.4 and it hangs intermittently. Also, the pages are absurdly wide now. Not sure why. Wish I'd never upgraded OSes.
