### ISSUE TITLE
Javascript only loads in debug mode

### ISSUE THREAD

**Issue by lbrito1** [mileszs/wicked_pdf#581]
I'm working on a dashboard application using wicked pdf. With `show_as_html` set to `true`, my javascript files included with `wicked_pdf_javascript_include_tag` load up fine:

![screenshot from 2016-10-07 15-26-48](https://cloud.githubusercontent.com/assets/2048939/19201155/def7869a-8ca2-11e6-91f8-a46c6214fc9a.png)

But when not in debug mode, i.e. when `show_as_html` = false, no javascript files are loaded. It does not seem to be a matter of if they have enough time to finish: I'm fairly certain none of them load at all (put some `console.log`s in the beginning of the files, nothing is printed in console).

The same js-loaded chart in the picture above doesn't load (note that css-defined styles loads fine, though):

![screenshot from 2016-10-07 15-26-36](https://cloud.githubusercontent.com/assets/2048939/19201156/defa8480-8ca2-11e6-81a2-29171e54ffb7.png)

Is this somehow expected behavior? Am I missing something?

**Comment by lbrito1** [comment]
Update: Javascript works as expected if I use `wkhtmltopdf` to directly render the html page, bypassing wickedpdf. So the issue is probably with wickedpdf.

**Comment by unixmonkey** [comment]
What does the output (from viewing the source) around the JS tags look like with `show_as_html: true`? Are they fully qualified paths or URLs?

If they are relative links, the wkhtmltopdf headless browser won't be able to reference them when rendering. You probably need to add the reference javascript files to your precompiled assets list [as shown here on the README](https://github.com/mileszs/wicked_pdf#asset-pipeline-usage).

**Comment by lbrito1** [comment]
>What does the output (from viewing the source) around the JS tags look like with show_as_html: true? Are they fully qualified paths or URLs?

The actual js code is inserted just as they would using Rails' helpers. So around `<%= wicked_pdf_javascript_include_tag "dashboards/surcharge.js" %>` I have `surcharge.js` code.

The only paths I see in the source are font-related.

I had already added the relevant js files to the precompile list (except some larger libs like jQuery, d3 etc which are declared in application.js - do I also have to somehow include them with wickedpf helpers?).

**Comment by unixmonkey** [comment]
Yes, any JS you need to render your PDF version.

**Comment by lbrito1** [comment]
Okay, that doesn't include sprockets-handled js, right? They seem to make their way to the final html fine.

I've narrowed down my problem to d3's horrible choice of liberally using UTF-8 symbols like ε and π throughout their code.

I'm using a wrapper gem (`d3-rails`) that cotains d3-v3's source. Passing the `--debug-javascript` flag to wkhtmltopdf, I get `SyntaxError: Invalid character '\u8364'` errors pointing to the epsilons and pis in d3's source code.

Now I can see that the issue has likely little to do with wickedpdf. For the sake of creating a precedent for this kind of error and maybe helping others in the future, do you have any suggestions of what to do @unixmonkey ? I kind of have my hands tied as far as using sprockets goes; the d3 code is used in many places...

**Comment by unixmonkey** [comment]
My recommendation for you for this problem would be to not use `wicked_pdf_javascript_include_tag`, and instead include the full http path to each JS file like:
"http://someurl.com/assets/javascripts/d3.js", however, this means that in the process of building your PDF, `wkhtmltopdf` will have to hit your server for those assets.

If you are using the default `rails server` (on some versions of Rails), which is single-threaded, you'll cause a deadlock waiting for resources, so your PDF request will never finish. You can avoid this by running a multi-threaded web server in development (like Puma).

You could possibly also get around this by using CDN referenced files.

Let me know how it goes!

**Comment by lbrito1** [comment]
@unixmonkey The thing is, the offending code isn't included by wickedpdf's helper, but by sprockets.

Anyway I did some more research and the problem seems to be with the encoding of the intermediary html file:

    $ file -i /tmp/wicked_pdf20161010-18929-1uotcye.html
    /tmp/wicked_pdf20161010-18929-1uotcye.html: text/html; charset=us-ascii

I saved the file as UTF-8 with BOM. The `Invalid character` was gone and my d3 charts executed normally.

Tomorrow I'll try to modify `WickedPdfTempfile` so that the user-defined encoding passed in options is always enforced.

**Comment by lbrito1** [comment]
@unixmonkey I inserted BOM at the beginning of the file and js worked fine. Looks like webkit is picky about encoding and expects a BOM if the html has any non-ascii chars.

Anyway, made a PR for this.

**Comment by unixmonkey** [comment]
Interesting. I'll be sure to take a closer look at this soon.

Even without this change, does adding `<meta charset='utf-8' />` in the `<head>`, make any difference?

**Comment by lbrito1** [comment]
Adding a `<meta charset="utf-8">` to the html seems to solve the issue without adding the BOM. The PR is no longer necessary.
