### ISSUE TITLE
Can't turn off lowquality: option when using render

### ISSUE THREAD

**Issue by Rodionov5** [mileszs/wicked_pdf#586]
Good day, 

I am using wicked_pdf version 1.1.0 with wkhtmltopdf 0.12.2.1 (with patched qt).

When I set lowquality: false, my pdf file size does not change at all when compared to lowquality:true.  Here is a snippet of my code:

respond_to do |format|    	  	  
      format.pdf do
        render 	pdf: 'Report_',   
        	   	disposition: 'inline',
      			template: 'generate_pdf/test.pdf.erb',
                        dpi: '600',
                        lowquality: false,                      
                        image_quality: 100,                        
      			save_to_file: Rails.root.join('pdfs', "Report_1.pdf"),
      			layout: 'layouts/pdf_layout.html',      			            
                        javascript_delay: 3000            
      end
    end

I am using ChartJs version 2 to generate the charts. Unfortunately, the charts come out really bad quality when I open the pdf file. Changing image_quality or dpi does not change my pdf size either. 

Perhaps there is another option which I am missing and this is why setting lowquality: false, does not do anything. 

Alternatively, it may also be an issue with chartjs.

**Comment by Rodionov5** [comment]
Apologies. After some testing, I realised this is not wicked_pdf issue. The issue is with chartJS/wkhtmltopdf. 

Still looking for a solution.

**Comment by montalvomiguelo** [comment]
@Rodionov5 How did you solve this?
