### ISSUE TITLE
Font icons not rendering correctly (font awesome & bootstrap glyphicons)

### ISSUE THREAD

**Issue by efigarolam** [mileszs/wicked_pdf#587]
Hello, I have been not able to successfully render font awesome nor bootstrap glyphicons on the generated PDF.

I have used the exact code described on #474 and actually copy and pasted what is described here https://github.com/unixmonkey/wicked_pdf_issues/commit/fdfbe4b2291abdc43d40c936357077e7ed343976 without luck.

On debug mode I can see the icons working as expected:
<img width="314" alt="screen shot 2016-10-26 at 23 18 59" src="https://cloud.githubusercontent.com/assets/2565682/19756652/1f87336a-9bd3-11e6-9548-06f8f658c5aa.png">

But on PDF they display like this:
<img width="257" alt="screen shot 2016-10-26 at 23 17 43" src="https://cloud.githubusercontent.com/assets/2565682/19756668/30025e72-9bd3-11e6-8f3b-91e2278341ee.png">

I am including font awesome in the same way as here https://github.com/unixmonkey/wicked_pdf_issues/commit/fdfbe4b2291abdc43d40c936357077e7ed343976#diff-8abf13ff2282e9406f136f6fc73d9d71R7

The same issue exists on Bootstrap Glyphicons. My specs are the following:
- OS X Yosemite
- Ruby 2.3.0
- Rails 4.2.7
- gem 'wicked_pdf', '= 1.0.6' (suggested on #474)
- gem 'wkhtmltopdf-binary', '= 0.12.3' (suggested on #474)

Any ideas? I feel really lost on this.

**Comment by unixmonkey** [comment]
There must be some difference.

Do you have a `<meta charset="utf-8">` in your layout?

Is there another font being loaded after `font-awesome`?

I did a reverse image search and the "WM" logo looks like it might be a stand-in for an invalid unicode character on Mac systems:

http://forums.macrumors.com/threads/strange-icon-files.1603397/
https://eparo.de/axure/webfont-ohne-web (Used Google to translate from German)

**Comment by efigarolam** [comment]
Thanks for your reply @unixmonkey, I did have the meta tag on my layout. Unfortunately the issue still persists after I removed it. I was loading some Google Fonts before the font-awesome, I also removed them to leave font-awesome alone but issue still happens. If this is a Mac problem, I think I will create and use a vagrant box to test my codebase there and see what happens. In the end the app will be deployed on a ubuntu machine, so if it works there, I will be more than happy. I'll keep you posted what happens after I try the vagrant approach.

**Comment by efigarolam** [comment]
Before trying vagrant I'm going to try the only approach I have not tried: load fonts base 64 encoded.

**Comment by efigarolam** [comment]
Also, on debug mode, icons do render/display ok.

**Comment by unixmonkey** [comment]
I'd suggest cloning the wicked_pdf_issues repo and trying that locally before spinning up a VM.

I'm also on a mac, and it works fine for me.

**Comment by efigarolam** [comment]
Hello @unixmonkey I just cloned the `wicked_pdf_issues` repo, installed the dependencies, ran the server and I'm seeing the same issue than my project. See screenshots.

<img width="1440" alt="screen shot 2016-10-31 at 23 36 28" src="https://cloud.githubusercontent.com/assets/2565682/19881440/eb47ad5c-9fc2-11e6-852d-4d3c70a08f42.png">

<img width="1440" alt="screen shot 2016-10-31 at 23 36 34" src="https://cloud.githubusercontent.com/assets/2565682/19881441/eb4d65ee-9fc2-11e6-92de-2532d753d225.png">

Any ideas? Could it be my system?

**Comment by efigarolam** [comment]
@unixmonkey ok, I think I finally get it working. I downloaded and installed the font-awesome.otf file on my Mac. After that, pdf started showing the icons.

My users will have to install the font in order to see on the PDFs or it will be enough if I install the font on the production/backend server?

**Comment by efigarolam** [comment]
@unixmonkey I think it was definitely my system. Just finished setting up a vagrant running Ubuntu 16.04 and font awesome and also bootstrap glyphicons are working as expected without installing any font on Ubuntu. Thanks for your support. 

If somebody on the future is running on a similar issue on any Mac OS, install the font on your system. I would also recommend you to start coding and trying your code on your final platform. In my case I know I'm going to deploy to a Ubuntu machine. So I decided to use a basic vagrant box to play within Ubuntu.

I'm closing the issue as it is not related to wicked_pdf gem.
