### ISSUE TITLE
save to disk with CDN styles

### ISSUE THREAD

**Issue by mmahalwy** [mileszs/wicked_pdf#596]
I am using bootstrap from CDN when rendering my PDF. Looks and works great when the server is rendering the PDF, but when the PDF is saved to disk, it does not maintain the styles.

Is it possible to have those styles included from the CDN?

**Comment by unixmonkey** [comment]
I'd like some more information about how you are doing or seeing this. Rendering through the browser should not be any different from saving it.

It is possible that there was an internet timeout reaching the CDN styles, but I would expect that to be intermittent, and not limited to one method of display.

Are you are using the `save_to_file: Rails.root.join('pdfs', "#{filename}.pdf")` option?

**Comment by mmahalwy** [comment]
I found the problem. I was doing:
```
WickedPdf.new.pdf_from_string(
      render_to_string(pdf: @title, template: 'show.pdf.erb', layout: 'pdf.html.erb')
    )
```
but without a layout option, thus no styles were being downloaded. Thanks @unixmonkey
