### ISSUE TITLE
syntax error on HTML?

### ISSUE THREAD

**Issue by Deekor** [mileszs/wicked_pdf#597]
I'm trying to convert one of my PDF generations to a background process following this wiki: https://github.com/mileszs/wicked_pdf/wiki/Background-PDF-creation-via-delayed_job-gem

When I run the line:

    pdf_html = av.render :template => "views/folder/file.pdf.erb", :layout => nil

I get a bunch of syntax errors around HTML in the `.pdf.erb` file:

    syntax error, unexpected '<', expecting ']' <div class="row">

Any ideas? This file runs fine when rendering directly from my controller.

**Comment by unixmonkey** [comment]
Can you post the HTML?

**Comment by Deekor** [comment]
Sure:
```

<%= render "dynamic_reports/report_header.html.erb", :formats => [:html]%>

<div class="row">

  <%= render partial: "dynamic_reports/income_section_pdf", locals: { title: "Revenue", image: "cash", collection: @revenue_accounts }, :formats => [:html] %>
  <%= render partial: "dynamic_reports/income_section_pdf", locals: { title: "Expenses", image: "check", collection: @expense_accounts }, :formats => [:html] %>

  <div class="rounded-block-header" id="Net Income/ (Loss)">
    <%= wicked_pdf_image_tag "reports/line-chart.png", class: 'header-icon' %>
    Net Income / (Loss)
  </div>
  <div class="rounded-block-footer">
    <table class="report-table">
      <tr class="no-border-top">
        <td class="width-60"><b>Total</b></td>
        <td><b><%= colored_amount((ReportHelpers.category_type_total(@revenue_accounts, @start_date, @end_date)) + ReportHelpers.category_type_total(@expense_accounts, @start_date, @end_date))%></b></td>
      </tr>
    </table>
  </div>

</div>
```

**Comment by unixmonkey** [comment]
That is an ERB partial, and not the rendered HTML, but it sounds like you might be having an issue with one of the helpers (or they aren't included?).

If you are on Rails 5, there's a much less hacky way to render a partial with something like this:

```ruby
html = WhateverController.render template: 'views/folder/file.pdf.erb', layout: false,
      locals: { current_user: User.first }
```

**Comment by Deekor** [comment]
We're not on Rails 5 yet. I don't think it's the partials, I removed them and it still didn't render (also the error is on a plain HTML line `<div class="row">`).

Again the partials work fine when I'm rendering this directly from a controller action. Sorry for the delayed response I've been out sick the past couple days.

**Comment by Deekor** [comment]
I've got it figured out. I was trying all of this in the console - when I built an actual sidekiq worker for it I was able to get it working. You were right I was missing some helpers apparently.
