### ISSUE TITLE
print_media_type doesn't make any difference

### ISSUE THREAD

**Issue by simmogs** [mileszs/wicked_pdf#600]
I'm trying to create a PDF using bootstrap and keep the background colours such as [.bg-danger](http://getbootstrap.com/css/#helper-classes) which are disabled by default via [bootstrap](https://github.com/twbs/bootstrap/blob/v3-dev/dist/css/bootstrap.css#L191) when using print as media. 

I would have thought that setting ''print_media_type: false'' would have sorted this, but it doesn't make any difference. I've tried various combinations using this with background and no_background it doesn't make any difference either.

**Comment by unixmonkey** [comment]
According to [wkhtmltopdf's documentation](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt):

> --print-media-type  Use print media-type instead of screen

Since it's a flag option, `wicked_pdf` expects a boolean value, so I think

```ruby
print_media_type: true
```

Will invoke the print stylesheet.

Let me know if that works or not.
If it doesn't, do you think you could add a simple example to the https://github.com/unixmonkey/wicked_pdf_issues example Rails app?

**Comment by simmogs** [comment]
Thanks for the quick response. I'm already using `print_media_type: false` the following without any luck. I'll try to put an example together as suggested.

**Comment by simmogs** [comment]
Frustratingly, I could get it working in my example, but still not in my real application.

**Comment by unixmonkey** [comment]
Are your print styles being overridden in your real application?

**Comment by simmogs** [comment]
It just doesn't seem to pick up that I don't want to use print media. Commenting out some lines (like those below) in bootstrap.scss has done the trick, but if feels messy.

    @media print {
      *,
      *:before,
      *:after {
        background: transparent !important;
        color: #000 !important;
        -webkit-box-shadow: none !important;
                box-shadow: none !important;
        text-shadow: none !important;
      }
    .............etc
