### ISSUE TITLE
Comment utiliser wkhtmltopdf sur OSX Sierra ?

### ISSUE THREAD

**Issue by Ecdys** [mileszs/wicked_pdf#611]
Bonjour, depuis que j'ai mon nouveau macbook, je ne parviens plus à utiliser wkhtmltopdf.

```
  Rendered ideas/show.pdf.slim within layouts/pdf.html (693.0ms)
"***************[\"/Users/herveleroy/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf_darwin_386\", \"-q\", \"--header-right\", \"[page] of [topage]\", \"file:///var/folders/9x/xp1rvlmn5d92tmwp1bck9p7w0000gn/T/wicked_pdf20170123-1724-17c1fz9.html\", \"/var/folders/9x/xp1rvlmn5d92tmwp1bck9p7w0000gn/T/wicked_pdf_generated_file20170123-1724-1q95mor.pdf\"]***************"
Completed 500 Internal Server Error in 834ms

RuntimeError - Error: Failed to execute:
["/Users/herveleroy/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/wkhtmltopdf-binary-0.9.9.3/bin/wkhtmltopdf_darwin_386", "-q", "--header-right", "[page] of [topage]", "file:///var/folders/9x/xp1rvlmn5d92tmwp1bck9p7w0000gn/T/wicked_pdf20170123-1724-17c1fz9.html", "/var/folders/9x/xp1rvlmn5d92tmwp1bck9p7w0000gn/T/wicked_pdf_generated_file20170123-1724-1q95mor.pdf"]
Error: PDF could not be generated!
 Command Error: :
  wicked_pdf (0.11.0) lib/wicked_pdf.rb:96:in `rescue in pdf_from_string'
  wicked_pdf (0.11.0) lib/wicked_pdf.rb:99:in `pdf_from_string'
  wicked_pdf (0.11.0) lib/wicked_pdf/pdf_helper.rb:64:in `make_pdf'
  wicked_pdf (0.11.0) lib/wicked_pdf/pdf_helper.rb:78:in `make_and_send_pdf'
```

Je ne me souviens plus ce que j'avais fait auparavant mais je soupçonne que la version du gem ne fonctionne pas ? Avez-vous un mac et si oui avez vous également ce problème ?

**Comment by unixmonkey** [comment]
Quel joyau utilisez-vous pour wkhtmltopdf (wkhtmltopdf_binary_gem, wkhtmltopdf_binary, wkhtmltopdf_binary_edge)? Si vous avez transféré votre répertoire gem installé, vous devez probablement désinstaller et réinstaller, et peut-être reconstruire binstubs si vous utilisez ceux (rbenv rehash).

Je m'attends à ce que vous auriez besoin de le faire pour les gemmes couche de base de données, aussi.

Si tout le reste échoue, je voudrais installer wkhtmltopdf nativement. Si vous utilisez Homebrew, vous pouvez `brew install wkhtmltopdf` et l'utiliser en mode de développement comme ceci:

__config/initializers/wicked_pdf.rb__
```ruby
if Rails.env.development?
  WickedPdf.config = {
    exe_path: '/usr/local/bin/wkhtmltopdf'
  }
end
```

S'il vous plaît laissez-moi savoir comment il va.


(In English)
Which gem are you using for wkhtmltopdf (wkhtmltopdf_binary_gem, wkhtmltopdf_binary, wkhtmltopdf_binary_edge)? If you transferred your installed gem directory, you probably need to uninstall and reinstall, and possibly rebuild binstubs if you use those (rbenv rehash).

I would expect you'd need to do this for database layer gems, too.

If all else fails, I'd install wkhtmltopdf natively. If you use Homebrew, you can `brew install wkhtmltopdf` and use it in  development mode like this:

Please let me know how it goes.

**Comment by Ecdys** [comment]
Thank you very much. 
I did'nt transfer my previously installed gems but i noticed that I missed to install the command line developer tools.
Uninstalling and installing again the gems does not solve my problem.
Finally i installed wkhtmltopdf natively as you suggested and added the initializer.
It works now ! ;)  i succeeded to generate a pdf file

**Comment by trusche** [comment]
Just want to point out that the standard brew install of wkhtmltopdf started failing recently because the souce code moved - see https://github.com/Homebrew/brew/issues/2031. You can fix that by using the cask version: 

    brew cask install wkhtmltopdf
