### ISSUE TITLE
Images from S3 are sometimes not fully rendered in exports

### ISSUE THREAD

**Issue by planima** [mileszs/wicked_pdf#624]
Hi!

Sorry if this already has been covered, I've tried to find info around this issue in this repo and on the web.

So, I'm exporting quite large PDF-files (around 60-100 pages), and some chapters consists of many images. The exports makes use of smaller and compressed versions of the images, which are stored on S3.

Often it works great, but sometimes when exporting the later part of the images are not showing. My first guess was memory issues, but the memory cap is not even close. It feels like the PDF has rendered _before_ the S3 pictures are fetched from S3 in an asynchronous way. Is there some way of making sure that the images are fully loaded before "completing the PDF-file"? 

Can someone point me in the right direction? Can't figure it out.

Using ruby version 2.1.5, wicked_pdf 1.1.0, wkhtmltopdf-binary 0.9.9.3.

Thanks in advance

**Comment by unixmonkey** [comment]
This might help:

```ruby
render pdf: 'my_pdf', window_status: 'finished_loading_images'
```

which waits to render through wkhtmltopdf until some JS sets window.status to the given string, so you could trigger by adding a data-attribute to your images (`data-loaded`), and  with something like this:

```html
<img src="..." data-loaded="false" onLoad="loadImage(this)"/>
<img src="..." data-loaded="false" onLoad="loadImage(this)"/>
<script>
  function loadImage(element) {
    element.setAttribute('data-loaded', 'true');
  }

  function imagesLoaded() {
    window.status = 'finished_loading_images';
    clearInterval(timer);
  });

  var timer = setInterval(function(){
    var notLoaded = document.querySelectorAll('img:not([data-loaded]');
    if (notLoaded.length === 0) {
      imagesLoaded();
    }
  }, 100000);
</script>
```

Here's a pretty fully-featured StackOverflow answer which was a basis for the code above (but not exactly the same): http://stackoverflow.com/a/29974998/23915

Let me know how it goes!

**Comment by planima** [comment]
Hi @unixmonkey! I did an implementation according to your suggestion a while back, and as far as I can tell this solves the problem. Until further notice, thanks!
