### ISSUE TITLE
build is failing according to readme

### ISSUE THREAD

**Issue by matkoniecz** [mileszs/wicked_pdf#626]
https://github.com/mileszs/wicked_pdf#wicked-pdf--

**Comment by unixmonkey** [comment]
The failures are against Edge Rails (what will soon be Rails 5.1), whose build is also failing right now.

I'd be OK with making failures on edge Rails allowable in Travis.

Would you like to help?

**Comment by unixmonkey** [comment]
Build is passing now with the past few PRs. Closing.
