### ISSUE TITLE
Wkhtmltopdf version

### ISSUE THREAD

**Issue by zainrafique** [mileszs/wicked_pdf#636]
hy, this gem is compatible with 0.12.0 or greater version of wkhtmltopdf?

**Comment by zainrafique** [comment]
I am working with wkhtmltopdf 0.12.3 and wicked_pdf gem. I am getting errors. Please give me direction.

**Comment by zainrafique** [comment]
Also getting the following error 
error while loading shared libraries: libjpeg.so.8: c$
on amazon ec2 server.

**Comment by unixmonkey** [comment]
Yes. WickedPDF is compatible with `wkhtmltopdf` versions 0.9 through current.

Sounds like the version of `wkhtmotopdf` you installed isn't fully compatible with your server build. The binaries available for download on wkhtmltopdf expect certain libraries to be installed. You may need to install a package for your distribution, or add some missing libraries.

This issue shows a list of common packages you might need to install to get everything working:
https://github.com/zakird/wkhtmltopdf_binary_gem/issues/19

Let me know how it goes!

**Comment by zainrafique** [comment]
ok thanks. I am using two different versions of wkhtmltopdf binaries in the same project(due to some requirements). Now Please tell me that both versions will use the same directory for shared libraries? Because one is working for me and the second one is throwing errors. I think both is looking different directory for libraries.

**Comment by zainrafique** [comment]
My server is amazon Linux, there is no description regarding amazon in above link.
Please correct me if I am wrong. Does Amazon use CentOS 7.0 binary?

**Comment by zainrafique** [comment]
In my gemfile I had following gems.
gem 'wicked_pdf'
gem "wkhtmltopdf-heroku"
gem 'wkhtmltopdf-binary'

**Comment by unixmonkey** [comment]
I think these two links may help:
http://www.jeremydaly.com/how-to-install-wkhtmltopdf-on-amazon-linux/
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2363

If you are using different versions of `wkhtmltopdf` in different environments, you'll want to specify a path to the binary in each environment. Something like this in your initializer:

__config/initializers/wicked_pdf.rb__
```ruby
if Rails.env.production?
  WickedPdf.config = { exe_path: '/usr/local/bin/wkhtmltopdf' }
elsif Rails.env.staging?
  WickedPdf.config = { exe_path: '/usr/bin/wkhtmltopdf' }
else
  # use default from gem
end
```

Since you have both wkhtmltopdf-heroku and wkhtmltopdf-binary installed, there isn't a good way to figure out which binary you want, so you might want to limit those to a group in your Gemfile like this:
__Gemfile__
```ruby
group :staging do
  gem 'wkhtmltopdf-heroku'
end

group :production do
  gem 'wkhtmltopdf-binary'
end
```

Let me know how it goes!

**Comment by zainrafique** [comment]
It works for me.Thanks

**Comment by zainrafique** [comment]
Wkhtmltopdf 0.12.1 is not accepting :cover, :toc and :extra => "--redirect-delay 3000". It is giving the following error.

RuntimeError (Error: Failed to execute:
["/home/zain/projects/ogra/lib/wkhtmltopdf", "-q", "--footer-html", "file:////tmp/wicked_footer_pdf20170328-18858-1wt0m5m.html", "--cover", "/tmp/wicked_cover_pdf20170328-18858-ebx22j.html", "--toc", "--toc-font-name", "Arial", "--toc-header-text", "Table of Contents", "--toc-depth", "3", "--toc-l1-font-size", "13", "--toc-l2-font-size", "13", "--toc-l3-font-size", "13", "--toc-l4-font-size", "13", "--toc-l5-font-size", "13", "--toc-l6-font-size", "13", "--toc-l7-font-size", "13", "--margin-top", "20", "--margin-bottom", "24", "--margin-left", "24", "--margin-right", "18", "--page-offset", "1", "file:///tmp/wicked_pdf20170328-18858-1uxc1oi.html", "/tmp/wicked_pdf_generated_file20170328-18858-1qz4iwx.pdf"]
Error: PDF could not be generated!
 Command Error: Unknown long argument --cover

Name:
  wkhtmltopdf 0.12.1 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
