### ISSUE TITLE
problems updating from 0.10.2

### ISSUE THREAD

**Issue by abacha** [mileszs/wicked_pdf#637]
Hi,
I've been using wicked_pdf for a long time, I had an application with rails 4.1 and I've recently updated it for 5.0. Then I had to update wicked_pdf to 1.1.0.
Now I'm testing my old pdf's generators and I'm having problems especially with header/footers, Its not working on every page anymore and I dont know where to begin to debug it.
Is there any kind of guide to work on this update?

**Comment by unixmonkey** [comment]
Closing as this issue is very stale, and several updates have been released since this. Please reopen if it's still a problem.
