### ISSUE TITLE
Support non-Rails env or add activesupport to gemspec

### ISSUE THREAD

**Issue by msa7** [mileszs/wicked_pdf#642]
I try gem in the non-Rails project.

Got 

```
/home/vagrant/.gem/ruby/2.3.1/gems/wicked_pdf-1.1.0/lib/wicked_pdf.rb:17:in
`require': cannot load such file -- active_support/core_ext/class/attribute_accessors (LoadError)
```

I think solution could be:

- Support non-Rails env
- or add activesupport to gemspec

**Comment by unixmonkey** [comment]
Closing now that https://github.com/mileszs/wicked_pdf/pull/643 is merged.
Thanks again!
