### ISSUE TITLE
Link to wkhtmltopdf-binary repo is wrong

### ISSUE THREAD

**Issue by georf** [mileszs/wicked_pdf#644]
Your links to wkhtmltopdf-binary from steerio (https://github.com/steerio/wkhtmltopdf-binary), but correct should be zakird (https://github.com/zakird/wkhtmltopdf_binary_gem)

This is the correct owner of the gem from https://rubygems.org/gems/wkhtmltopdf-binary

Please update your readme. I was really confused till i recognized this.

**Comment by unixmonkey** [comment]
Weird. I don't know how that got missed for so long. I'm a maintainer on both that project and this one. Thanks for spotting that. I've updated it!
