### ISSUE TITLE
PDF shows some random image

### ISSUE THREAD

**Issue by divyaravva** [mileszs/wicked_pdf#649]
HI, 

After opening the generated PDF in browser, I'm getting some random image and black background. Can you please help me with this, I have been trying from long time, but didn't get any solution. Attached the screenshot  that was rendered in PDF.

NOTE: If I have PDF directly I can see the data, Facing issue when try to open in the browser.
 
Thanks In advance.
![download 3](https://cloud.githubusercontent.com/assets/25108927/25457275/586dc0f2-2a9b-11e7-8be9-bf92c394fb7a.png)

**Comment by unixmonkey** [comment]
This is the icon for a crashed plugin in your web browser. How are you displaying the PDF, `disposition: 'inline'`, in an `<iframe>`, or some Flash plugin or Java applet?

Does it work in a different browser, like Chrome, IE, or Firefox?

**Comment by divyaravva** [comment]
I'm using disposition: 'attachment' and not using any Iframe or flash plugin.

**Comment by unixmonkey** [comment]
`disposition: 'attachment'` should cause a download of the file, and no change to your web browser screen. Were you on this screen before entering a PDF download URL?

Please let me know how it behaves in a different web browser, maybe you have some data corruption a reinstall of your browser could fix.

**Comment by divyaravva** [comment]
Yes, I can see it in other browsers. May be it was issue with my browser. I will try re-installing browser.

Anyways Thanks for the awesome help!!!!!!! Thanks

**Comment by unixmonkey** [comment]
Glad to help :)
