### ISSUE TITLE
HostNotFoundError in production due to [page] in footer

### ISSUE THREAD

**Issue by mboily** [mileszs/wicked_pdf#660]
As described by the documentation I am using these options for wkhtmltopdf to automatically generate page numbers.

`footer: {right: "Page [page] of [toPage]"}`

It works perfectly for local development but when deployed to a tomcat server we get this issue: 

```
["/usr/local/bin/wkhtmltopdf", "-q", "--page-size", "Letter", "--margin-top", "0.5in", "--margin-bottom", "0.5in", "--margin-left", "0.5in", "--margin-right", "0.5in", "--footer-right", "Page [page] of [topage]", "file:////tmp/tomcat6-tomcat6-tmp/wicked_pdf20170614-15812-2i2etj.html", "/tmp/tomcat6-tomcat6-tmp/wicked_pdf_generated_file20170614-15812-r3ze2l.pdf"]
Error: PDF could not be generated!
Command Error: Error: Failed loading page http://of (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
```

Other footer options work, such as [time]. It is only when the [page] option is there it seems it is trying to reach a url of "of" (taking the next string from the footer).

**Comment by unixmonkey** [comment]
Does it work if you do this?

```ruby
footer: {right: "'Page [page] of [toPage]'"}
```

(notice the single quotes inside the double quotes).
I think this may be coming out in the command as `--footer-right Page [page] of [toPage] file://`, when it should be `--footer-right 'Page [page] of [toPage]' file://`

Can you confirm this is what's happening?

**Comment by mboily** [comment]
Yes this seems to have fixed it. I thought I had tried it, but now I realize I had put the double quotes within the single.

Thanks.

**Comment by unixmonkey** [comment]
Glad to hear it. I'll try to make it so that isn't necessary in future versions.
