### ISSUE TITLE
Debug Mode not Working

### ISSUE THREAD

**Issue by Pawlarius** [mileszs/wicked_pdf#673]
I enabled show_as_html options just like example, access page with params '?debug', but still rendering pdf version.. is there any other way to enabled debug mode? @mileszs

**Comment by unixmonkey** [comment]
```
render pdf: 'mypdf', show_as_html: true
```

Will make it debug mode without any messing with params, then you can change it to `false` or remove it when done debugging.

**Comment by Pawlarius** [comment]
somehow still not working, it will render it as pdf..

**Comment by unixmonkey** [comment]
Can you share the relevant parts of your controller action?

Does it work if you ctrl+refresh or open the URL up in debug mode in an incognito browser session? I wonder if you are getting a cached response from the browser.

**Comment by Pawlarius** [comment]
`respond_to do |format|
      format.pdf do
        render  pdf: "Guidebook PDF - " + @guidebook.title,
                show_as_html: true,
                template: "guidebooks/pdf.pdf.erb"
      end
`

i tried in incognito, tried adding params debug, tried empty cache and reload..

**Comment by unixmonkey** [comment]
Are you sure your HTML mode doesn't just look a heck of a lot like the PDF version (that is the intention, after all)?

If you right-click -> Inspect, and look at the "elements" tab, does it contain your source HTML, or the chrome PDF viewer's HTML?

**Comment by Pawlarius** [comment]
The funny thing is,  i realised somehow any changes i do to my options doesnt change the request happened in log.. 
I already clear and precompile my assets again, clear cache and refresh, tried in incognito mode and no changes at all when i comment out some options for checking..  No wonder show_as_html not working.. 
M

**Comment by unixmonkey** [comment]
If you can join me in the next few minutes, I'll be available at https://appear.in/wicked_pdf and can help you debug this in person. Let me know if another time would work better.

**Comment by Victoriosu** [comment]
Any solution?

**Comment by unixmonkey** [comment]
@Victoriosu Can you provide more information about what isn't working for you?

**Comment by Victoriosu** [comment]
I'm having trouble with every option that I'm giving, none of them works. I'll paste every related file that I consider is invovled, that is.

catalogue.rb
`pdf_html = av.render 	:pdf => 'catalogue',
	    						:template => "catalogues/catalogo.pdf.erb",
	    						:margin =>  {   
	    						 	top: 0,
		                            bottom: 12,
		                            left: 0,
		                            right: 0
								},
								orientation: orientation,

	    						:locals => {
		    						:ids => ids, 
		    						:per_page => per_page,
		    						:texto_final => texto_final
	    						},
	    						footer: {
	                            	html: {
	                            		template: '/catalogues/partials/footer',
	                            		locals:  { orientation: orientation },
	                            	}
                            	}
	    catalogue_pdf = WickedPdf.new.pdf_from_string(pdf_html)
	    save_path = Rails.root.join('tmp', "catalogo.pdf"),
            show_as_html: params.key?('debug')`

applicartion.rb

`
    wicked_pdf_options = {
        margin: {top: 0, left: 0, bottom: 12, right: 0}
    }

    config.middleware.use WickedPdf::Middleware, wicked_pdf_options`

**Comment by unixmonkey** [comment]
I think the middleware is overriding your render call. Try disabling it. If that works and you still want middleware behavior, use the `except` option for the endpoint you are calling render from.

**Comment by Victoriosu** [comment]
Didn't work, any more ideas? Any more files you need?

**Comment by unixmonkey** [comment]
Any related output in your rails server log? Are PDFs being generated at all, or are customization flags just not applying? What version of wkhtmltopdf and Rails are you using?

**Comment by Victoriosu** [comment]
Sorry, my error was that I wasnt providing the options to the WickedPDF
constructor, instead of it I'was just putting them on the Action View
render object. Thanks anyway for your feedback.

**Comment by petran** [comment]
I am having problem view the file as an html too.
I user show_as_html: true and then loading the file from my controller
def pdf
    send_file('example.pdf', type: 'application/pdf', disposition: :inline)
  end
but still getting the pdf format.

**Comment by unixmonkey** [comment]
@petran The code you are showing does not use `show_as_html: true`. Can you share that? I don't quite understand what you are asking.

**Comment by petran** [comment]
@unixmonkey thanks for your response
I am creating a pdf file and saving it

pdf=WickedPdf.new.pdf_from_string(
      html,
      header: {content: html_header},
      footer: {content: html_footer},
      margin:  { top:               "0.5in", 
                 bottom:            "0.5in",
                 left:              "0.0in",
                 right:             "0.0in" },
      #page_size: 'Letter',
      page_height: '11in',
      page_width: '8.5in',
      dpi: 96,
      zoom: 8,
      show_as_html: true
    )

   save_path = Rails.root.join('example.pdf')
    File.open(save_path, 'wb') do |file|
      file << pdf
    end

Then on my controller I send the file 

def pdf
    send_file('example.pdf', type: 'application/pdf', disposition: :inline)
end

I should be able to inspect the document correct ?

**Comment by unixmonkey** [comment]
Ok, now I see. No. `show_as_html` is an argument to `render pdf: 'mypdf'`, and not usable with `pdf_from_string`. At that point, you already have a PDF, and cannot extrapolate HTML from it.

It appears you already have the `html`, which is what would be displayed, except for some exceptions where you are using the wicked asset helpers, where it shows the web version.

An example that should do what you are looking for is more like this:

```ruby
def pdf
  render pdf: 'example.pdf',
      html: html.html_safe, # better if the html is in views/x/pdf.erb than here
      header: {content: html_header},
      footer: {content: html_footer},
      margin:  { top:               "0.5in", 
                 bottom:            "0.5in",
                 left:              "0.0in",
                 right:             "0.0in" },
      page_height: '11in',
      page_width: '8.5in',
      dpi: 96,
      zoom: 8,
      save_to_file: Rails.root.join('example.pdf'), # I only added this so you can keep saving the file locally like in your example, but shouldn't be necessary
      show_as_html: true
end
```

**Comment by carltonsmith** [comment]
I'm getting a similar issue, though, it was working. I debugged a couple of errors, but now instead of showing me the HTML or an error statement it just pops up `Error: Failed to Load PDF Document` with a `Reload` button

Here is my render
```
respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'outcome_goals',
               dpi: 300,
               template: 'reports/outcome_goals.pdf.erb',
               show_as_html: params[:debug].present?,
               layout: 'report_application.pdf'
      end
      return if format.xlsx
end
```
I tried it with `show_as_html: true` as well, but the result was the same

**Comment by mmudge** [comment]
I am getting the same `Error Failed to load PDF document.` error as @carltonsmith 

my controller method looks like this

`  def resume
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "resume",
               template: "downloads/resume.html.erb",
               layout: 'pdf.html.erb',
               show_as_html: params[:debug].present?
      end
    end
  end`

views/layouts/pdf.html.erb

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF</title>
  </head>
  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>`

views/downloads/resume.html.erb

`<h1>Resume</h1>`

no errors in the rails server..

`Started GET "/downloads/resume.pdf?debug=true" for ::1 at 2021-01-02 18:47:18 -0800
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Users/mike/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.3/lib/active_record/log_subscriber.rb:98
Processing by DownloadsController#resume as PDF
  Parameters: {"debug"=>"true"}
Completed 200 OK in 9ms (Views: 0.1ms | ActiveRecord: 0.0ms)`

Can't get it to to work, any help is much appreciated.

**Comment by unixmonkey** [comment]
@mmudge Try adding `content_type: 'text/html'` to your pdf render options. I think your browser is still expecting a PDF and getting HTML, which could be part of the issue.
