### ISSUE TITLE
chinese language does not appear in pdf

### ISSUE THREAD

**Issue by hendranata** [mileszs/wicked_pdf#675]
helo

i use wicked_pdf gem to generate PDF.
we use chinese language like 產地台灣
and it does not apppear in PDF.. 
any solution for this?
thanks

**Comment by unixmonkey** [comment]
First, make sure your html has something like this in the HEAD to force it into UTF mode:

<meta charset=utf-8" />

If that doesn't help, you may need to install a font on the system, or provide one explicitly with CSS

On Apt-based systems (like Ubuntu or Debian): `sudo apt-get install fonts-wqy-zenhei`
On Yum-based systems (like Redhat): `yum install "@Chinese Support"`

[This comment](https://github.com/mileszs/wicked_pdf/issues/456#issuecomment-187489905) shows you how to install a nonstandard system font.

Let me know how it goes!

**Comment by yangjindong** [comment]
I'm also disturb by this issue. 
@unixmonkey this command line save me much time:
yum install "@Chinese Support"

**Comment by hendranata** [comment]
@unixmonkey 
working fine
thanks

**Comment by vijaychouhan-rails** [comment]
add `<meta http-equiv="content-type" content="text/html; charset=utf-8" />`
On Apt-based systems (like Ubuntu or Debian):` sudo apt-get install fonts-wqy-zenhei`
On Yum-based systems (like Redhat): `yum install "@Chinese Support"`
