### ISSUE TITLE
Urgent Issue - Missing Template

### ISSUE THREAD

**Issue by vishaltps** [mileszs/wicked_pdf#679]
I am using wicked pdf along with delayed job.
I followed this official document of wicked pdf https://github.com/mileszs/wicked_pdf/wiki/Background-PDF-creation-via-delayed_job-gem for generating pdf in background. all thigs was working fine in my local and staging . but it is not working on live site.  In live site  , i am getting this error.
`No such file or directory @ rb_sysopen - /var/www/project/lessons-matchmaker/app/views/home/group_classes_pdf.html.erb
/var/www/project/lessons-matchmaker/app/services/pdf_generator.rb:27:in `read'
/var/www/project/lessons-matchmaker/app/services/pdf_generator.rb:27:in `find_html'
/var/www/project/lessons-matchmaker/app/services/pdf_generator.rb:15:in `call'
/var/www/project/lessons-matchmaker/app/mailers/classes_pdf_mailer.rb:5:in `send_classes_details'`

here is code, i use to generate pdf , it is working fine in local and staging,
`av = ActionView::Base.new()
    av.view_paths = ActionController::Base.view_paths

    # need these in case your view constructs any links or references any helper methods.
    av.class_eval do
      include Rails.application.routes.url_helpers
      include DateHelper
      include ApplicationHelper
      include InstructorStudentsHelper
    end
    pdf = av.render :pdf => "GroupClass",
                      :template => 'instructor/home/group_classes_pdf',`

need to solve this problem urgently.

**Comment by unixmonkey** [comment]
Sorry, I'm just now seeing this. How did you resolve your issue?

**Comment by vishaltps** [comment]
Sorry, it was very silly mistake done by me. i forgot to restart delayed job service.
