### ISSUE TITLE
Default font size for pdf

### ISSUE THREAD

**Issue by huangjun604** [mileszs/wicked_pdf#685]
Dear team,

I tried to generate a simple pdf file, but the font size is too small by default. Is it normal? Should I usually set the font-size when using wicked_pdf?

This is the version I use:

- wicked_pdf (1.1.0)
- wkhtmltopdf-binary-edge (0.12.4.0)

The layout I use:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```

The body page:

```
<p>This is the test pdf file;
  This is the test pdf file;This is the test pdf file;This is the test pdf file;
  This is the test pdf file;This is the test pdf file;
  This is the test pdf file;This is the test pdf file;This is the test pdf file;
  This is the test pdf file;
  This is the test pdf file;
  This is the test pdf file;
  This is the test pdf file;
  This is the test pdf file;
  ......
  This is the test pdf file;This is the test pdf file;This is the test pdf file;
  This is the test pdf file;This is the test pdf file;This is the test pdf file;
  This is the test pdf file;This is the test pdf file;This is the test pdf file;
</p>
```

This is the file I generated: [filename.pdf](https://github.com/mileszs/wicked_pdf/files/1335730/filename.pdf)

Many Thanks!

**Comment by huangjun604** [comment]
Solved, this is caused by the dpi setting

**Comment by dcangulo** [comment]
@huangjun604 What dpi did you use? Changing the dpi doesn't seem to fix it for me.
