### ISSUE TITLE
Master is red due to rubocop failures

### ISSUE THREAD

**Issue by PragTob** [mileszs/wicked_pdf#687]
Example: https://travis-ci.org/mileszs/wicked_pdf/jobs/245821915

I think the problem is that no rubocop version is specified, so CI picks up a new rubocop version with new checks and thus the build starts failing. Solution would be to pin the version in the gemspec to a known good version and only upgrade it slowly and deliberately :)

**Comment by unixmonkey** [comment]
I partially did this on purpose, so I'd know when new rules conflict, but the frequency which rubocop gets updated, it makes more sense to pin to a version. PR's accepted, or I'll get to it in the next few days.

**Comment by unixmonkey** [comment]
Thanks @gabteles !
