### ISSUE TITLE
 wkhtmltopdf is not executable on Windows

### ISSUE THREAD

**Issue by lsarni** [mileszs/wicked_pdf#693]
I have this two gems in my Gemfile:
```
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
```
And on my ruby folder I have this:
![image](https://user-images.githubusercontent.com/15196342/31317921-e1b7f89a-ac1f-11e7-888d-7ee3b15378ab.png)
And this:
![image](https://user-images.githubusercontent.com/15196342/31317928-f9b7996e-ac1f-11e7-97f7-1931be3bd533.png)

I have tried setting the config to both folders, but I always get the  `wkhtmltopdf is not executable` error:
```
WickedPdf.config = {
    exe_path:  "C:/Ruby24/bin/wkhtmltopdf"
  }
```

Without the config I get this error `Bad wkhtmltopdf's path: /c/Ruby24/bin/wkhtmltopdf` and `which wkhtmltopdf` return `/c/Ruby24/bin/wkhtmltopdf`

I have been looking on StackOverflow but nothing seems to work.

**Comment by elisbresciani** [comment]
Download from here https://wkhtmltopdf.org/downloads.html 
unpack, and run or save in c, not in ruby, i dont remember the process, but i think is this. 

 and your wicked_pdf.rb

WickedPdf.config = {

:exe_path => 'C:\wkhtmltopdf\bin\wkhtmltopdf.exe'

}

**Comment by unixmonkey** [comment]
It looks to me like your `wkhtmltopdf` under Ruby24/bin might be either the linux binary (due to it not having a `.exe` extension, or a symlink, which Windows probably won't like (or could point to the wrong file).

The `wkhtmltopdf-binary` gem doesn't include a windows build, so you can remove it entirely, unless you also run in a production/staging environment that is linux.

Follow @elisbresciani's advice and download the Windows EXE version, and point your config at it.

Let me know how it goes!

**Comment by lsarni** [comment]
Right, I did end up doing what @elisbresciani recommended. 

I found this part of the readme confusing, since as @unixmonkey says "the wkhtmltopdf-binary gem doesn't include a windows build"

> The simplest way to install all of the binaries (Linux, OSX, Windows) is through the gem wkhtmltopdf-binary.

**Comment by unixmonkey** [comment]
Oh! Good point! I didn't realize the documentation in the README was out-of-date. The gem we used to recommend (years ago) did have the windows exe packaged in it, but this gem does not.

I've updated the README in [this commit](https://github.com/mileszs/wicked_pdf/commit/d96abcb6df4c137525d27626b9cc2d5319516ade).

Thanks so much for pointing that out!

**Comment by CristianJulio** [comment]
@elisbresciani muchas gracias!!

**Comment by MaherSaleem** [comment]
Thanks @elisbresciani  :D

**Comment by Amaljohnjoy** [comment]
How is the issue resolved? I am facing the same issue and after implimenting @elisbresciani comments I got the error like, Bad wkhtmltopdf's path.
