### ISSUE TITLE
Only renders header and footer (no body)

### ISSUE THREAD

**Issue by jasonmenayan** [mileszs/wicked_pdf#703]
I am rendering a 2-page document. 

If I include the `header` attribute, it prints the headers and footers on both pages, but nothing else (no body). 

If I remove the `header` and only leave the `footer`, then the document prints normally except no `header` (naturally).

The fact that both of the "contentless" 2 pages are being printed with the header and footer suggests that something about the header is hiding/suppressing the body below it (otherwise, presumably only a single page would be rendered).

Both the `header` and `footer` are full HTML files (with `!DOCTYPE html`, `<html>` tags, etc.), as is the body/content.

Is there something missing from my implementation?

**Comment by jasonmenayan** [comment]
I used Acrobat to inspect the resulting PDF, and there is a large bounding box that is apparently white and obscuring the content beneath it. When editing, it can be moved out of the way, exposing the content.

Does anyone know what could be creating this obscuring box? I can't see anything in the HTML or CSS that's doing this.

**Comment by jasonmenayan** [comment]
Figured it out: the issue was styles applied to the `html` selector in my stylesheet. Changed it to the `body` selector and it works just fine. 
Not sure why those styles (which specified width, font color, margin) somehow created this giant white box below the header, that obscured the document body, but there you have it.

**Comment by gotno** [comment]
👏
