### ISSUE TITLE
Different scaling on Windows and Linux

### ISSUE THREAD

**Issue by soundasleep** [mileszs/wicked_pdf#714]
I was having an issue where rendering PDFs on Windows and on Linux would render with different sizes, even though the underlying version of wkhtmltopdf was the same.

Upon further investigation this issue [seems to lie with wkhtmltopdf and its interaction with Linux/Windows](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2184): 

> on Linux it prints at 75 dpi (native for WebKit) while on Windows it uses the desktop's DPI (which is normally 96 dpi). You can use --zoom 0.78125 (75/96) to get the same effect on Linux.

Would it be worth adding this caveat to the README? Alternatively (my preference), to scale the 'zoom' factor provided to wkhtmltopdf by (1.0/0.78125) if the user is on Windows?

**Comment by unixmonkey** [comment]
I think an addition to the README is more appropriate. That behavior is different not only by OS, but what resolution of monitor you have, and changing a default is bound to break for a great number of users.

**Comment by soundasleep** [comment]
How's this? https://github.com/mileszs/wicked_pdf/pull/715

**Comment by unixmonkey** [comment]
Merged. Thanks!
