### ISSUE TITLE
wicked_pdf_NNN_tag for non-Rails apps

### ISSUE THREAD

**Issue by GildedHonour** [mileszs/wicked_pdf#720]
How can I use `wicked_pdf_(image | javascript | stylesheet)_tag` for non-Rails but Rack apps? Does anything exist at all?

**Comment by unixmonkey** [comment]
Unfortunately, the current asset helpers are specifically built for Rails.

However, they are fairly simple and you could purpose build one for Rack or other frameworks, or even use fully-qualified URIs with host and path, which should also work in most configurations.

The `wicked_pdf_asset_base64` helper especially should be easily portable.

Here's the source for all the asset helpers:
https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/wicked_pdf_helper/assets.rb

If you come up with something good, or have issues, please come back and update this issue or create a PR!
