### ISSUE TITLE
On a remote VPS --> "    qt.qpa.screen: QXcbConnection: Could not connect to display "

### ISSUE THREAD

**Issue by GildedHonour** [mileszs/wicked_pdf#723]
Since it's built on top on wkhtmltopdf and therefore headless as the description of wkhtmltopdf claims -- "These run entirely "headless" and do not require a display or display service." --, why do I have the following error on a remote VPS server and how to fix it?

    $ wkhtmltopdf --version
    wkhtmltopdf 0.12.4

    $ /usr/bin/wkhtmltopdf http://www.google.com output.pdf
    qt.qpa.screen: QXcbConnection: Could not connect to display 
    Could not connect to any X display.

I've tried many things 

     xhost +
     xhost +my_user
     xhost +localhost

    ==> xhost:  unable to open display ""

to no avail

**Comment by unixmonkey** [comment]
To run `wkhtmltopdf` headless, requires a patched QT installation, which is not included when you install from system packages on some (e.g. Debian) systems.

This thread has more information:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037

Let me know how it goes!

**Comment by GildedHonour** [comment]
I'm using Arch Linux and installed it via pacman.  

this comment says https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-344423993 

that even 0.12.3 is a pached one, whereas I have 0.12.4

**Comment by unixmonkey** [comment]
When you run the command:
```shell
wkhtmltopdf --version
```
Does it say "(with patched qt)" in the version response like this?

`wkhtmltopdf 0.12.3 (with patched qt)`

**Comment by GildedHonour** [comment]
it doesn't

**Comment by GildedHonour** [comment]
I've installed it and run:

```
$ wkhtmltopdf http://www.google.com output.pdf         
Loading pages (1/6)
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_library_init
Warning: Failed to load https://ssl.gstatic.com/gb/images/b_8d5afc09.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

```

Are these warnings normal?

**Comment by GildedHonour** [comment]
It's working but not completely properly. I'm printing a pdf out of an html. Now Instead of text it's printing squares. any idea why?

![_2018-02-28_09-11-08](https://user-images.githubusercontent.com/2032888/36764412-7772ceca-1c67-11e8-8866-2907ae8059ef.png)

**Comment by GildedHonour** [comment]
Locally on my computer it's working properly

**Comment by unixmonkey** [comment]
Looks like SSL or SSL-dev packages need to be installed to handle SSL content, and the black squares look like you may need to install a font package on your Arch system (or maybe the font is being loaded over SSL?).

[This comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3045#issuecomment-234759959) seems to have some insight.

**Comment by GildedHonour** [comment]
Yeah, thx

**Comment by lobermann** [comment]
In case somebody is looking for a solution on ubuntu 18, as above did not work for me
https://gist.github.com/lobermann/ca0e7bb2558b3b08923c6ae2c37a26ce
