### ISSUE TITLE
Problem loading javascript in attached mail

### ISSUE THREAD

**Issue by DamienCompere** [mileszs/wicked_pdf#726]
Hello, 
I'm using wicked pdf to generate pdf with highchart graphs and send it to some users. My problem is that it seems that the pdf is send before all the javascript is loaded, I can see only 2 graphs out of 6 in my attached file. Here is the set up of my controller : 

```ruby
attachments["rapport.pdf"] = WickedPdf.new.pdf_from_string(
  render_to_string(
    :pdf => "rapport_pdf",
    :viewport_size => '1280x1024',
    :template => 'template_pdf.pdf.erb',
    :layout => 'rapport_pdf.html.erb',
     :window_status => "FLAG_FOR_PDF", # Wait until window.status is equal to this string before rendering page
  )
)
```

Any idea what's wrong there ? 
Thank you for your help !

**Comment by boboroshi** [comment]
Have you tried using `javascript_delay: {num}` (where `{num}` is an integer) on your render call or config?

**Comment by DamienCompere** [comment]
Thanks for answering boboroshi !
I tried the javascript_delay but it did'nt work

**Comment by unixmonkey** [comment]
@DamienCompere Is the javascript that generates the charts setting the `window.status` only after everything is done rendering?

**Comment by DamienCompere** [comment]
@unixmonkey Thanks for your answer ! 

The window.status is set after every graphs are rendered (it works on a simple render to pdf call but not on the attachment). It looks like window.status or javascript_delay is not taken into account by the render_to_string call. Indeed, I have tried to remove the window.status in the javascript file that generate the template, the pdf is still rendered (but still without any graphs).

**Comment by unixmonkey** [comment]
@DamienCompere `pdf_from_string` takes wicked_pdf options as the second argument, whereas `render_to_string` passes them through Rails' `render` but supplanting with wicked_pdf options if the `pdf` key is present.

It appears to me that you could either remove the `pdf_from_string` part, or move the `window_status` and `viewport_size` options out.

Sorry I don't have time to check right now, but one or either of these should get you closer:
```ruby
attachments["rapport.pdf"] = render_to_string(
  :pdf => "rapport_pdf",
  :viewport_size => '1280x1024',
  :template => 'template_pdf.pdf.erb',
  :layout => 'rapport_pdf.html.erb',
  :window_status => "FLAG_FOR_PDF",
)
```

```ruby
attachments["rapport.pdf"] = WickedPdf.new.pdf_from_string(
  render_to_string(
    :template => 'template_pdf.pdf.erb',
    :layout => 'rapport_pdf.html.erb',
  ),
  {
    :viewport_size => '1280x1024',
    :window_status => "FLAG_FOR_PDF",
  }
)
```

Let me know how it goes!

**Comment by DamienCompere** [comment]
@unixmonkey you are right ! 
By moving the options :viewport_size and window.status the pdf is completed ! 
Also I can see the viewport_size and window.status in my terminal as options that we not before
Thanks again for your time !
