### ISSUE TITLE
Help needed - PDF rendering fails in production (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by panpsonis** [mileszs/wicked_pdf#737]
This may not be the most appropriate place to post this. If not, please point me to right direction. I couldn't find much relevant info and can't figure this out by myself.

PDF rendering works in development but not in production environment. The following error gets logged in "log/production.log"

```
Failed to execute:
["/app_path/vendor/bundle/ruby/2.4.0/bin/wkhtmltopdf", "-q", "file:////tmp/wicked_pdf20180430-447-t8pv0n.html", "/tmp/wicked_pdf_generated_file20180430-447-17t8bd.pdf"]
Error: PDF could not be generated!
Command Error: /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in 'block in materialize': Could not find rake-12.3.0 in any of the sources (Bundler::GemNotFound)
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in 'map!'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in 'materialize'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in 'specs'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in 'specs_for'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in 'requested_specs'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in 'block in definition_method'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in 'setup'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:107:in 'setup'
        from /home_path/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in '<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
)
```

wicked_pdf 1.1.0
wkhtmltopdf-binary-edge 0.12.4 (Same with wkhtmltopdf-binary 0.12.3.1)

I am using rbenv to manage Rubies and currently there is just one rbenv Ruby (2.4.3p205) which is associated with this app. This Ruby has rake-12.3.0 installed.

However, there is also a system wide installation of Ruby (2.3.0) which was added as a dependency of Passenger (while installing libapache2-mod-passenger). This Ruby does not have rake-12.3.0 installed.

From the error above, it looks as if there is some mixing of Rubies going on but I can't figure out why and how to fix it. I don't have any similar issues with the rest of the application.

I'd appreciate any help.

**Comment by panpsonis** [comment]
No change. Actually, if you look at the error, all the paths are correct (2.4) except for the last two lines (2.3). This could be normal since the installed Passenger depends on Ruby 2.3, I really don't know.

Could it be a situation where wkhtmltopdf is executed under a different user compared to the application and therefore has a different gem environment?

**Comment by unixmonkey** [comment]
`wkhtmltopdf` doesn't need Ruby at all on a server, however I bet your rbenv binstub tries to load it that way, so that when you shell out to `wkhtmltopdf`, it actually runs the binstub, which has a shebang for Ruby at the top, and likely has some bundler invocations in it.

I'd cat the `wkhtmltopdf` it's trying to invoke and see what Ruby code is being loaded that is causing the issue. If editing the binstub isn't doable, then you can use this trick to get at the binstub that wkhtmltopdf-binary-gem provides (which should run fine in your environment, since it doesn't load bundler/rake):

```ruby
WickedPdf.config = {
  exe_path: "#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-edge-#{Gem.loaded_specs['wkhtmltopdf-binary-edge'].version}/bin/wkhtmltopdf"
}
```

Or this to get at the actual platform-specific binary itself:

```ruby
WickedPdf.config = {
  exe_path: "#{ENV['GEM_HOME']}/gems/wkhtmltopdf-binary-edge-#{Gem.loaded_specs['wkhtmltopdf-binary-edge'].version}/libexec/wkhtmltopdf-linux-amd64"
}
```

Let me know how it goes!

**Comment by panpsonis** [comment]
Thanks for your reply, helped me learn a couple of things plus some vocabulary.

To the point... **find_wkhtmltopdf_binary_path** ends up pointing to a **RubyGems** binstub. Changing to the **wkhtmltopdf-binary-edge** binstub (through your code) produces the same error. Only when pointing to the actual binary (again through your code) does it work.

What seems weird to me is that:

- neither binstub appears to have any  bundler/rake references,

- when executing the binstubs through the shell, they work fine.

Any chance this has to do with the way Wicked PDF makes the call? I had a look at the code but I'm not familiar with Open3 or in general executing external commands.

For reference:

**RubyGems** binstub
```
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'wkhtmltopdf-binary-edge' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('wkhtmltopdf-binary-edge', 'wkhtmltopdf', version)
else
gem "wkhtmltopdf-binary-edge", version
load Gem.bin_path("wkhtmltopdf-binary-edge", "wkhtmltopdf", version)
end
```

**wkhtmltopdf-binary-edge** binstub
```
#!/usr/bin/env ruby

arch = case RUBY_PLATFORM
  when /64.*linux/
    'linux-amd64'
  when /linux/
    'linux-x86'
  when /darwin/
    'darwin-x86_64'
  else
    raise "Invalid platform. Must be running linux or intel-based Mac OS."
end

args = $*.map { |x| x.include?(' ') ? "'" + x + "'" : x }
cmd = File.expand_path "#{File.dirname(__FILE__)}/../libexec/wkhtmltopdf-#{arch}"

exec "#{cmd} #{args.join(' ')}"
```

**Comment by unixmonkey** [comment]
I'm not 100% sure, but I think the `require 'rubygems'` line may be trying to load `rake` as a dependency.

Open3 should not be interfering with the environment, including the version of Ruby it gets executed under if it shells out.

Are you certain when running the binstubs from the command-line, you are doing so as the user that your app runs as?

**Comment by panpsonis** [comment]
I'm getting the same error with the **wkhtmltopdf-binary-edge** binstub that doesn't have the `require 'rubygems' ` so that shouldn't be the issue. I also double checked the correct user by having the app print it out.

I'm considering that this may be associated to Passenger but I've run out of ideas on what to check, so I'll get back to it later on unless you have any test to propose.

In any case, I have a way to make it work (by pointing directly to the binary) and this doesn't seem to have anything to do with Wicked PDF so feel free to close this one if you like.

**Comment by unixmonkey** [comment]
I'm glad I could help, but I'm sorry you have a less-than ideal config issue.

Let me know if you ever find out what's up with your setup. I'm sure it would help someone else.
