### ISSUE TITLE
wkhtmltopdf 0.12.1(with patched qt) is giving error on redirect delay and javascript delay

### ISSUE THREAD

**Issue by zainrafique** [mileszs/wicked_pdf#757]
hy,
Here is description

respond_to do |format|

        format.pdf do
          render  :pdf => "file",
                  :layout   => 'wta/pdf.html.haml',
                  :wkhtmltopdf => Rails.root.join('lib', 'wkhtmltopdf').to_s,
                  :lowquality => false    ,
                  :template => 'wta/reports/graph_report.html.haml',
                  :disable_javascript => false ,
                  :orientation => 'Landscape',
                  :redirect_delay => 3000,
                  :javascript_delay => 3000,
                  # :viewport_size => '1280x1024',
                  # :window_status => 'FLAG_FOR_PDF',

                  :margin   => {:top    => 10, # default 10 (mm)
                                :bottom => 18,
                                :left   => 0,
                                :right  => 0
                  },
                  :footer => {:html =>
                                  { :template => 'wta/reports/pdf_footer.html.haml' }
                  }
        end
        format.html
      end
I am getting the following error.
Error: Failed to execute: ["/usr/local/bin/wkhtmltopdf", "-q", "--footer-html", "file:////tmp/wicked_footer_pdf20180801-4122-1i1h8rs.html", "--margin-top", "10", "--margin-bottom", "18", "--margin-left", "0", "--margin-right", "0", "--orientation", "Landscape", "--redirect-delay", "3000", "file:///tmp/wicked_pdf20180801-4122-1k52i20.html", "/tmp/wicked_pdf_generated_file20180801-4122-1y7qi4q.pdf"] Error: PDF could not be generated! Command Error: Unknown long argument --redirect-delay Name: wkhtmltopdf 0.12.2.1 (with patched qt) Synopsis: wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... Document objects: wkhtmltopdf is able to put several objects into the output file, an object is either a single webpage, a cover webpage or a table of content. The objects are put into the output document in the order they are specified on the command line, options can be specified on a per object basis or in the global options area. Options from the Global Options section can only be placed in the global options area A page objects puts the content of a singe webpage into the output document. (page)? [PAGE OPTION]...

**Comment by unixmonkey** [comment]
`redirect_delay` is a legacy option for older versions of `wkhtmltopdf` (< 0.10.x), and is not supported on recent versions.

Its functionality has been renamed and slightly reworked as `javascript-delay`, so you can remove the `redirect_delay` option from your code and forget it exists :)

Please reopen or create a new issue if you continue to have trouble!
