### ISSUE TITLE
The problem with the zoom

### ISSUE THREAD

**Issue by afuno** [mileszs/wicked_pdf#759]
I'm using this code in the action:

```ruby
respond_to do |format|
  format.pdf do
    render pdf: 'print',
           layout: 'print',
           page_size: 'A4',
           zoom: 5.0,
           show_as_html: params.key?('debug')
  end
end
```

And this layer:

```slim
doctype html
html
  head
    meta charset="utf-8"
    = wicked_pdf_stylesheet_link_tag 'pdf'
    scss:
      body { background-color: #ffffff; }
    = wicked_pdf_javascript_include_tag "number_pages"

  body onload='number_pages'
    #header
      / ...
    #content
      = yield
```

In the development environment in all browsers I have everything well rendered.

In the production environment in Chrome (at the same time in Safari everything is fine), I get a clipped piece of the table:

<img width="1440" alt="2018-08-10 12 41 31" src="https://user-images.githubusercontent.com/2853419/43951067-c7720f72-9c9a-11e8-8247-628710ef16bc.png">

What is the problem?

**Comment by QuintinAdam** [comment]
I am also having development/production inconsistency issues with the zoom. 

I have mine zoom set to `zoom: 0.78125` as that is what was recommend here: https://github.com/mileszs/wicked_pdf#gotchas

In development everything is super tiny but production the size is perfect. 

```
wicked_pdf (1.1.0)
wkhtmltopdf-binary (0.12.4)
```

**Comment by unixmonkey** [comment]
I believe this is the same issue as described in #756 

Please check out that thread and it's suggestions and links.

Let me know what you try and how it goes!

**Comment by QuintinAdam** [comment]
`lowquality: true,` fixed the problem  for me! Thanks that was driving me crazy.

**Comment by afuno** [comment]
I confirm. This is the solution:

```ruby
lowquality: true,
zoom: 1,
dpi: 75,
```

Thanks.
