### ISSUE TITLE
Slow initial pdf generation on docker

### ISSUE THREAD

**Issue by alvinj01** [mileszs/wicked_pdf#761]
Hello, we have encountered what appeared to be a caching issue on AWS ECS tasks.

The first pdf generation after a new deployment will take 30+ seconds, but any pdf generation afterwards would take ~1 second only. This happens on every task.

We cannot reproduce this locally, only on production. 

The layout file doesn't have much, except these:
```
<%= javascript_include_tag "rollbar" %>
<%= wicked_pdf_stylesheet_link_tag "pdf" %>
<%= wicked_pdf_javascript_include_tag 'jquery',
  'jquery.cookie',
  'i18n',
  'i18n/translations',
  'files/utils' %>
```

Any help is appreciated. Thanks!

**Comment by unixmonkey** [comment]
I notice you are referencing `i18n/translations`, which makes me think you might be using [i18n-js](https://github.com/fnando/i18n-js).

If you are using it's [middleware](https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/middleware.rb), the first time it is accessed it will compile then cache the result, which may explain the difference.

You can test this theory by not including i18n or translations (or all JS) and see if that speeds things up dramatically or not.

You may want to only enable the middleware in dev/test environments (or not at all). I think it should work without it the way you are using it.

Let me know how it goes, or if I've jumped to the wrong conclusion. Good luck!

**Comment by alvinj01** [comment]
So, it wasn’t anything in the layout file. It takes just as long rendering an empty file. So, it must be initializing the wkhtmltopdf binary itself. As a workaround, we simply trigger wkhtmltopdf to render an empty file right after deployment for the time being.
