### ISSUE TITLE
Endless rendering if image is included

### ISSUE THREAD

**Issue by c2ofh** [mileszs/wicked_pdf#774]
I've created a form without an image. Everything is working great.
When I want to insert a small image 100x100px the render is loading endlessly.

I've tried `<%= wicked_pdf_image_tag @object.image.url('medium') %>`. Also `<%= image_tag @object.image.url('medium') %>` is not working.

I have to kill the server to make it stop.
In /tmp the temporary html file is available. The pdf file is also there with 0 bytes.

After killing, this interrupt error apears. I think it's not very helpful, but just for information.
```
Error: PDF could not be generated!
 Command Error: /usr/share/rvm/gems/ruby-2.5.1/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf:21:in `system': Interrupt
        from /usr/share/rvm/gems/ruby-2.5.1/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf:21:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-2.5.1/bin/wkhtmltopdf:23:in `load'
        from /usr/share/rvm/gems/ruby-2.5.1/bin/wkhtmltopdf:23:in `<main>'
        from /usr/share/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/share/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

Gem Versions: 
- wicked_pdf (1.1.0)
- wkhtmltopdf-binary (0.12.4)

Ruby Version:
- ruby 2.5.1p57

**Comment by unixmonkey** [comment]
If you are only running on a single-threaded web server, and reaching out to that same server to request an asset that needs to be loaded by Rails, that can cause a deadlock because it must serve a second request when it hasn't finished your first PDF request, resulting in a hung process.

You can refer to the image directly from disk with a `file://` reference, or request it from a separate asset host or base64 encode it with the `wicked_asset_base64` helper.

That can also be fixed by using a multithreaded rails server like Puma in development.

Good luck! Let me know how it goes!

**Comment by c2ofh** [comment]
@unixmonkey 
Seems legit. I've tried yout base64 helper but the image cannot be found.

```status=500 error='ActionView::Template::Error: Could not find asset '/system/pms/guests/signatures/000/000/005/medium/signature.jpg?1540389915'
status=500 error='ActionView::Template::Error: Could not find asset '/system/pms/guests/signatures/000/000/005/medium/signature.jpg?1540389915'
status=500 error='ActionView::Template::Error: Could not find asset '/srv/project/public/system/pms/guests/signatures/000/000/005/medium/signature.jpg'
status=500 error='ActionView::Template::Error: Could not find asset 'http://localhost:3000/system/pms/guests/signatures/000/000/005/medium/signature.jpg?1540389915'
```
http://localhost:3000/system/pms/guests/signatures/000/000/005/medium/signature.jpg?1540389915 is available in browser.

**Comment by unixmonkey** [comment]
It sounds like you might be using PaperClip or ActiveStorage, which I think allows you to get the file path like:
```erb
<%= wicked_pdf_image_tag @object.image.path('medium') %>
```

**Comment by c2ofh** [comment]
@unixmonkey
thank you for your help. But non of these combination works... :/
```erb
<%= wicked_pdf_image_tag @object.image.path('medium') %>
<%= wicked_pdf_image_tag @object.image.url('medium') %>
<%= wicked_pdf_image_tag @object.image('medium') %>
```

**Comment by c2ofh** [comment]
I was able to find a solution with another workaround.
Just a quick fix, I will optimize it.

```ruby
@signature = 'data:image/jpg;base64, ' + Base64.encode64(open(@guest.signature.path(:medium), 'rb').read).delete!("\n")
```
view

```erb
<%= image_tag(@signaure) %>
```
