### ISSUE TITLE
Failed without error message: wkhtmltopdf 

### ISSUE THREAD

**Issue by pzanwar03** [mileszs/wicked_pdf#789]
PDF not save my folder in localhost.
I'm getting an error : Failed without error message: wkhtmltopdf "C:\Users\Fujitsu\AppData\Local\Temp\tmp1470.tmp.html" "C:\Users\Fujitsu\AppData\Local\Temp\tmp1480.tmp.pdf"

My code id: 
`$pdf_html = view('frontend.pdf.pdf_template', $data)->render();
        $pdf = new Pdf;
        $pdf->addPage($pdf_html);

    
        if (!$pdf->saveAs(public_path() . '/assets/invoices_pdf/invoice_' . $tran_id . '.pdf')) {
            $error = $pdf->getError();
            print '<pre>'; print_r($error); print('</pre>'); die();
        }`

I'm using Windows 10

**Comment by unixmonkey** [comment]
I think you are using a different project to create your PDFs.

This appears to be code from https://github.com/mikehaertl/phpwkhtmltopdf
I would suggest you post your issue on that project's tracker.
