### ISSUE TITLE
PDF rendering fails on Heroku 16 Stack

### ISSUE THREAD

**Issue by chughes** [mileszs/wicked_pdf#794]
Heroku released an update to its Heroku 16 stack on December 18. Since that update to our Heroku instances, pdf rendering will only temporarily work on a new branch deploy. After ~5 mins pdf rendering silently fails (ie. no information presented in log file).

Final log entry is:
2019-02-01T17:37:56.044912+00:00 app[web.1]: ***************WICKED***************

That is followed by a series of rack-timeout notifications until we reach the Heroku limit and the call fails.
2019-02-01T17:37:58.588912+00:00 app[web.1]: source=rack-timeout id=511db688-876f-4b5d-bb58-2a52f749509f wait=3ms timeout=28000ms service=3000ms state=active
2019-02-01T17:37:59.588844+00:00 app[web.1]: source=rack-timeout id=511db688-876f-4b5d-bb58-2a52f749509f wait=3ms timeout=28000ms service=4000ms state=active
...

rails 4.2.11
ruby 2.2.7
wicked_pdf 1.1.0
wkhtmltopdf-heroku 2.12.2.4
(we have also tried using dscout/wkhtmltopdf-buildpack but have the same result)

**Comment by unixmonkey** [comment]
@chughes Why did you close this? Did something change with Heroku, or did you find another solution?

**Comment by chughes** [comment]
no solution, no response. We are moving to a different solution

**Comment by unixmonkey** [comment]
Have you checked out [this fork of wkhtmltopdf-heroku](https://github.com/gregnavis/wkhtmltopdf-heroku)?

It claims to support the Heroku 18 stack.

**Comment by vjdavid** [comment]
I am using Heroku 18 stack and I tried using that gem and works fine, thank you @unixmonkey
