### ISSUE TITLE
Output on Production Sidekiq are hieroglyphics

### ISSUE THREAD

**Issue by c2ofh** [mileszs/wicked_pdf#826]
## Issue description

**Local:**
When I create the file directly I get a nice looking PDF-File.
When I create the file in a Sidekiq Backgroundworker I get a nice looking PDF-File

**Production:**
When I create the file directly I get a nice looking PDF-File.
When I create the file in a Sidekiq Backgroundworker I get a sheet with hieroglyphics

`%PDF-1.4 1 0 obj << /Title (þÿ) /Creator (þÿwkhtmltopdf 0.12.4) /Producer (þÿQt 4.8.7) /CreationDate (D:20190417115230+02'00') >> endobj 3 0 obj << /Type
/ExtGState /SA true /SM 0.02 /ca 1.0 /CA 1.0 /AIS false /SMask /None>> endobj 4 0 obj [/Pattern /DeviceRGB] endobj 8 0 obj [0 /XYZ 57 813.500000 0] endobj 9 0 obj
[0 /XYZ 57 776 0] endobj 10 0 obj << /__WKANCHOR_2 8 0 R /__WKANCHOR_4 9 0 R >> endobj 13 0 obj <> endobj 12 0 obj <> endobj 11 0 obj <> endobj 14 0 obj
<< /Type /Catalog /Pages 2 0 R /Outlines 11 0 R /PageMode /UseOutlines /Dests 10 0 R >> endobj 5 0 obj << /Type /Page /Parent 2 0 R /Contents 15 0 R /Resources
17 0 R /Annots 18 0 R /MediaBox [0 0 595 842] >> endobj 17 0 obj << /ColorSpace << /PCSp 4 0 R /CSp /DeviceRGB /CSpg /DeviceGray >> /ExtGState << /GSa 3 0
R >> /Pattern << >> /Font << /F6 6 0 R /F7 7 0 R >> /XObject << >> >> endobj 18 0 obj [ ] endobj 15 0 obj << /Length 16 0 R /Filter /FlateDecode >> stream xoeí]
[ Ü¶ ~Ÿ_¡ç k‹¤®@QÀ»ö èC … ô!èCáÄ-‚8¨“‡þýJ# F{>‘ E jwÛM€8#Ï žû ÔÛ? üGñÏß‹·w ÿ]|žÿ¼ûx*ß´u9ýSOEÿÞ¬ ÔmÑ ÷fú\|
þzúV|;=oe †ÿŽ ~;] M¿ýýó¯§·Ó:§éÉÇ»¿ ÿ÷ŸÂ >ý\üð÷á g ã ¾žšÊ¼9Ão† ¿¬?š²«ß ×ÕÝð¼” Ç/ÿëô·? ¿ x”oº²´Ußôõ„‹ø< žOEjh—Q+—...` and so on.

## System specifications

**wicked_pdf** 1.1.0
**wkhtmltopdf-binary** 0.12.4

On an **Ubuntu 18.04** Server.

## Code

```ruby
signature = user.base64_signature
filename = "form_#{user.id}"
pdf = WickedPdf.new.pdf_from_string(
  ApplicationController.new.render_to_string(pdf: filename, template: 'backend/shared/tasks/attachment/registration_form.pdf.erb',
                                             disposition: 'attachment', layout: 'application.print', lowquality: false,
                                             locals: { user: user, signature: signature })
)
save_path = Rails.root.join('tmp', "#{filename}.pdf")
File.open(save_path, 'wb') do |file|
    file << pdf
end
```

The Template includes: `<meta charset="utf-8">`

**Comment by unixmonkey** [comment]
Those "heiroglyphics" are the contents of the PDF when viewed as text instead of binary or without mime `application/pdf`.

It sounds to me like the PDF is generating correctly, but how it is being displayed or served needs correcting. If you have a controller endpoint that is displaying a specified file written to PDF, make sure it is being served with `Content-Type: application/pdf`.

**Comment by unixmonkey** [comment]
Closing this since it's a pretty old issue, and very likely not related to any code in `wicked_pdf`, but feel free to comment on this thread, and I'll try to help out, or post what solution you went with, if you worked around this yourself.
