### ISSUE TITLE
Missing 1.4.0 Tag

### ISSUE THREAD

**Issue by tlb-yatsushi** [mileszs/wicked_pdf#839]
I was interested in looking at the source for the current version of wicked_pdf, but noticed that latest version from rubygems.org (1.4.0) isn't stored as tag on this repo

![image](https://user-images.githubusercontent.com/51306415/59240263-c3105800-8c3e-11e9-92ae-8a3ebf764d43.png)

![image](https://user-images.githubusercontent.com/51306415/59240255-ba1f8680-8c3e-11e9-802d-0485d3f59d03.png)

**Comment by unixmonkey** [comment]
Thanks for the tip. I've pushed that tag.
