### ISSUE TITLE
Does it work with Alpine?

### ISSUE THREAD

**Issue by olegsobchuk** [mileszs/wicked_pdf#841]
I want to build Docker on Alpine image with Rails 5.2 + Ruby 2.6.
But seems like `wkhtmltopdf-binary` isn't compatible with linux Alpine, I installed `wkhtmltopdf` from Alpine sources, and it builds PDF, but without styles.

Is there any approach to use `wicked_pdf` on linux Alpine?

**Comment by unixmonkey** [comment]
In another issue, someone reported [this wkhtmltopdf Alpine Docker container](https://github.com/alloylab/Docker-Alpine-wkhtmltopdf)

And there are several [posts on StackOverflow about it](https://stackoverflow.com/search?q=%5Bwkhtmltopdf%5D+alpine&mixed=0)

Please come back and let us know what works for you!

**Comment by olegsobchuk** [comment]
@unixmonkey  I've tried almost all suggestions and it doesn't work for me... Unfortunately... I'm going to spend some time to find fix for my issue but seems like I'll migrate to Ubuntu

**Comment by tareksamni** [comment]
I'm running it on `Alpine3.8` and I guess it will work for any Alpine as follows:

```
FROM madnight/docker-alpine-wkhtmltopdf as wkhtmltopdf_image

FROM ruby:2.3.8-alpine3.8
# I do some staff here and then
COPY --from=wkhtmltopdf_image /bin/wkhtmltopdf /bin/
```

**Comment by kam1kaze** [comment]
If you do not see some fonts in generated PDF, you just need to install them. `apk --update add ttf-ubuntu-font-family` should be enough in most cases. More fonts here  https://wiki.alpinelinux.org/wiki/Fonts

**Comment by mileszs** [comment]
It works on Alpine for us, as well. We've been running this in a production app for a few months. The top of our Dockerfile looks like this:

```
# stage 1
FROM madnight/docker-alpine-wkhtmltopdf:alpine-3.8 as base

# stage 2
FROM our-private-thing/ruby:2.6.2-alpine3.8.4

# copy over wkhtmltopdf apline binary
COPY --from=base /bin/wkhtmltopdf /usr/bin/wkhtmltopdf

# ... a bunch of other stuff, none of it wkhtmltopdf related I promise :-)
```

**Comment by kam1kaze** [comment]
We've migrated to new ruby docker version and started to use wkhtmltopdf from Alpine upstream. So our `Dockefile` looks like that:

```
FROM ruby:2.6.3-alpine

RUN apk --update add ttf-ubuntu-font-family wkhtmltopdf

...
```

and it works fine :)

**Comment by tareksamni** [comment]
It's irrelevant to `ruby` version. `ruby:2.6.3-alpine` is basically an alias to `ruby:2.6.3-alpine3.10` which means you are running `alpine3.10`.

As per https://pkgs.alpinelinux.org/packages you can see that starting from [`3.9`](https://pkgs.alpinelinux.org/packages?name=wkhtmltopdf&branch=v3.9) a new package is available and called `wkhtmltopdf`. while it was not available from [`3.8`](https://pkgs.alpinelinux.org/packages?name=wkhtmltopdf&branch=v3.8) downwards.

**Comment by unixmonkey** [comment]
Closing this, as it appears to have been answered. Yes, it works with Alpine.
Thank you all who responded 🙇

**Comment by bo-oz** [comment]
I followed instructions here to incorporate WickedPDF in a docker image, but I keep getting this strange error from time to time. Sometimes the PDF is generated, other times it exits with:

```
Command Error: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```

Any ideas how to overcome?

**Comment by unixmonkey** [comment]
@bo-oz `wkhtmltopdf` uses QT to render sometimes, and that appears to sometimes need to write to a temporary directory. Is `/tmp` not writable by the user your app runs as in your image?

I think you might fix this by either granting write permission to `/tmp`, or setting the `$XDG_RUNTIME_DIR` environment variable to somewhere it can write.

I'm not sure this is the reason the command errors though. This sounds like just a warning, unless it can't write to `/tmp`. Is there more to those messages than you pasted here?

**Comment by bo-oz** [comment]
I think this error had to do with the font pack that wasn’t installed. But the issue still persists, it seems that the call that lets WickedPDF write a string to a HTML file to the tmp folder seems to fail from time to time. The error is than coming from wkhtmltopdf that isn’t able to access the file or it is missing entirely. Trying to do some more debugging tomorrow.

**Comment by bo-oz** [comment]
After debugging some more, I found that the command that addresses wkhtmltopdf, seems to fail from time to time with signal 11. Any ideas what that could mean? Could it be a rights issue accessing the file in the temp dir?

This is the line that sometimes raises the error: `Open3.popen3(*command)` on line 68 in `wicked_pdf.rb`

**Comment by bo-oz** [comment]
Ok, finally found the issue. When calling `pdf_from_string` before the actual pdf is rendered, there's an intermittent call to `pdf_from_html_file` to add `file:///` before the temporary filename. When using this gem inside my Alpine, this results in an error: `Failed to load file:///tmp/wicked_pdf20200224-11365-1k7clri.html, with network status code 203 and http status code 0`

When I "monkeypatch" the  method to the following, it does work like a charm:
```
  def pdf_from_html_file(filepath, options = {})
    pdf_from_url(filepath, options)
  end
```

Is there a reason that you are adding this `file:///` to the path? Would you consider a PR in which I add an option to skip this call?

**Comment by bo-oz** [comment]
Created PR #889 to have a way to solve the issue above.

**Comment by thisismydesign** [comment]
Simply installing `wkhtmltopdf` and pointing the gem to the binary didn't work for me.

```
Command Error: The switch --footer-left, is not support using unpatched qt, and will be ignored.The switch --footer-right, is not support using unpatched qt, and will be ignored.The switch --footer-font-size, is not support using unpatched qt, and will be ignored.The switch --footer-spacing, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```

Instead, I needed to copy from `madnight/docker-alpine-wkhtmltopdf` as also proposed before.
