### ISSUE TITLE
Can not understand Basic usage

### ISSUE THREAD

**Issue by ZAJDAN** [mileszs/wicked_pdf#844]
**This Is not a issue**
-------------------------------------------------
Ruby 2.3.3
wicked_pdf (1.4.0) activesupport
wkhtmltopdf-binary (0.12.4)
Debian 8
-------------------------------------------------
Even when I read Your manual, I am confuse how to generate the PDF. 
I have one main view where is:
 <%= button_tag "PDF" , name: "button_KW_block2_PDF", id: "pdf", class: "prod-stat-button" %>

In my Controller I have method and my goal is, when one of the condition in the method will be fulfilled, should render PDF and open the PDF as new tab in Browser. Actually the condition looks:
```
def prod
.....
.....shortened

if params.include?(:button_KW_block2_PDF)
      puts "button_KW_block2_PDF has been triggered"
      
      respond_to do |format|
	format.html
	format.pdf do
	  render pdf: "Commissions for KW-#{@kw2}",
	  page_size: 'A4',
	  template: "layouts/prod.html.erb",
	  dpi: 100
	end
      end
  
    end
```
here is the view which I want to render to PDF:
_/view/layouts/prod.pdf.erb_
```
<!DOCTYPE html>
<html>
<head>
<title>PDF-Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "KW" %>
</head>
<body>
    <table> 
   <thead>
      <tr>
      <th colspan="3" class="list">LIST</th>
      </tr>
	<tr>
        <th>A</th>
        <th>B</th>
        <th>C</th>
        </tr>
    </thead>
   <tbody>
   <% Array(@commission2).each do |week| %>
         <tr>
	    <td><%= week.a%> </td>
            <td><%= week.b %></td>
            <td><%= week.c%></td>
   <%- end %>
</tr>
    <%end%>
</tbody>
</table>
</body>
</html>
```
but nothing going on, in server console I see also nothing.
Thank You for any hint.

**Comment by cesc1989** [comment]
Hi @ZAJDAN I think the layout should be named `/view/layouts/prod.html.erb` instead of `/view/layouts/prod.pdf.erb`

In your controller you specify it with `.html` extension.

Also, use `layout` key instead of `template`:

```ruby
respond_to do |format|
  format.html
  format.pdf do
	   render pdf: "Commissions for KW-#{@kw2}",
	   page_size: 'A4',
	   layout: "layouts/prod.html",
	   dpi: 100
  end
end
```

**Comment by unixmonkey** [comment]
Closing this as inactive and very out-of-date.
If you are still having trouble, let me know and I can re-open and try to help.
