### ISSUE TITLE
Can't get Wicked to render svg originating from javascript

### ISSUE THREAD

**Issue by sohara** [mileszs/wicked_pdf#85]
I am trying to get wicked pdf to render a google chart that uses their javascript api. I have successfully rendered the chart using the wkhtmltopdf binary but when I try to render it using the wicked_pdf_gem through rails I'm not having any luck. Are there features of  wkhtmltopdf that are not available through wicked_pdf?

In my layout I have the following:

``` erb
<%= content_for :head do %>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>

<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Year');
    data.addColumn('number', 'Sales');
    data.addColumn('number', 'Expenses');
    data.addRows([
      ['2004', 1000, 400],
      ['2005', 1170, 460],
      ['2006', 660, 1120],
      ['2007', 1030, 540]
    ]);

    var options = {
      width: 600, height: 400,
      title: 'Company Performance',
      hAxis: {title: 'Year', titleTextStyle: {color: 'red'}}
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>
<% end -%>
<h1>Testing PDFs w/ Javascript</h1>
<div id="chart_div" class="chart_div"></div>
```

And in my controller I have:

``` ruby
  def index
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "file_name",
          :template => "index/index.html.erb"
      end
    end
  end
```

When I issue the command:

``` bash
bundle exec wkhtmltopdf 'http://localhost:3000/index' - > test.pdf
```

The output is a pdf with the javascript-based chart properly rendered. But when I visit the url in my browser wicked_pdf doesn't render the chart. I am guessing that this should work. Is there something I'm missing?

Thanks,
Sean

**Comment by anushamummina** [comment]
Guys can anyone can help me on this. I am also facing the same issue in my local environment. Staging environment it is working again in production it is not working as expected. when I am rendering as "show_as_html => true" everything is working as expected but in PDF it is loading properly.

Can anyone please help what could be the issue?

**Comment by unixmonkey** [comment]
Is the javascript file that kicks this off in the precompile list something like this: `config.assets.precompile += ['svg_renderer.js']`?

**Comment by anushamummina** [comment]
@unixmonkey sorry unix but I didnt understand what you are trying to say
