### ISSUE TITLE
Cannot render cover page like the rest of the document?

### ISSUE THREAD

**Issue by altjx** [mileszs/wicked_pdf#851]
## Issue description

I am simply trying to render a cover page with a full background with some text displayed on it that will be from ActiveRecord. However, I'm not sure why I cannot figure this out. Here's what my `render` code looks like from the controller:

```
          format.pdf do
            render pdf: "file_name", 
            template: 'clients/reports/generate_technical.html.erb',   # Excluding ".pdf" extension.
            cover: render_to_string('clients/reports/cover_page.pdf.html.erb'),
            show_as_html: params.key?('debug'),
            margin:  {  top:               25,                     # default 10 (mm)
                        bottom:            17,
                        left:              10,
                        right:             10 },
            header:  {   html: { template: 'layouts/report_header.html.erb'}},
            footer:  {   html: { template: 'layouts/report_footer.html.erb'}}
          end
```

## Expected or desired behavior

I expect to be able to render the cover page just as dynamically as I can with the other pages. I'm not quite sure why it's any different of a process.

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): wicked_pdf (1.4.0)

wkhtmltopdf version (output of `wkhtmltopdf --version`): wkhtmltopdf 0.12.4 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu

**Comment by altjx** [comment]
Anyone know how to get an HTML page for a cover page? With the ability to dynamically change some of the text on it?

**Comment by altjx** [comment]
Assuming this gem is no longer maintained.

Figured this out by creating separate PDFs for the title/cover page and just merged them with `pdfunite`.

**Comment by unixmonkey** [comment]
@altjx This gem is maintained, but I've been quite busy this past month and can only do so much.

I'm not sure why your cover example isn't working for you as-is (maybe you need to supply locals or instance variables), but I think you may be able to use the class-level `render` method in Rails 5+ something like this:

```ruby
cover: ActionController::Base.render(
  template: 'clients/reports/cover_page',
  layout: false,
  locals: { }
)
```

**Comment by altjx** [comment]
Hi @unixmonkey,

Gotcha. Thanks man. I sincerely appreciate this gem -- is there any way I can donate for the support?

The only problem I have right now is that, when calling a view from a worker, anytime `asset_url` is within the view, it gets turned into `/path/to/asset` rather than `http://server/path/to/asset`. It works fine when using wicked pdf from within a controller -- the `asset_url` gets converted to the proper `http://server/path/to/asset`. Not sure why Rails is not loading the same `asset_url` helper from the worker that is used within the controller.

Going to close this out since this is resolved. I just have to figure out what's up with rails now.

Thanks a lot and looking forward to donating!

**Comment by unixmonkey** [comment]
@altjx IIRC, mailers have their own host config separate from the rest of your app, so it's helpful to set them both up something like this:
```ruby
host = 'https://mysite.com'
config.action_controller.asset_host = host
config.action_mailer.asset_host = host
config.action_mailer.default_url_options = { host: host }
```

I appreciate the sentiment, but I personally don't want any donations. I already have a lot of responsibilities outside of this project, and I feel that exchanging money muddles the relationship equation. I'm donating some of my time at my leisure to help others.

However, I would greatly appreciate some of your time if you can spare it. If you could use your experience and ability to debug to help out others in this project (or any other one, really), it would be very much appreciated. Many maintainers of popular open source projects like this one have far more issues than any one person can handle without making it part of their job. I don't have time to answer all of these issues, or track down exactly what's happening in every setup.

If you can, please consider paying it forward a bit. If you can help resolve one other issue, you've paid me back, and helped someone else out in the process, and likely many others, as most problems aren't unique.

**Comment by altjx** [comment]
Perfect! Thanks @unixmonkey. I really appreciate that. Unfortunately that didn't seem to do the trick for me, but what I did for the sake of time was use gsub to convert "non-full" URLs to full ones and that should be OK for now. 

Will definitely pay it forward helping out as well. Many thanks.
