### ISSUE TITLE
Error while loading shared libraries: libpng12.so.0 (on dokku)

### ISSUE THREAD

**Issue by Lucasvn** [mileszs/wicked_pdf#853]
## Issue description
I'm having some trouble while trying to generate an pdf through the `pdf_from_url method` on production.
The error is the following:
```
Error: PDF could not be generated!
 Command Error: /app/vendor/bundle/ruby/2.5.0/gems/wkhtmltopdf-binary-edge-0.12.5.0/libexec/wkhtmltopdf-linux-amd64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```
The error only occurs on production. Everything works normaly on development.

One thing to notice is that my application server runs on a dokku container, which i'm inexperienced in. So, probably the error occurs due to the way of how dokku's file architeture works. 

What i have already tried:
- Changed wkhtmltopdf's gem from `wkhtmltopdf-binary` to `wkhtmltopdf-binary-edge`
- Installed libpng12 manualy on the server (not on dokku container)

## Expected or desired behavior
The application should be able to generate an pdf file from an url and save it locally.

## System specifications

wicked_pdf gem version: `1.1.0`

whtmltopdf [provider gem]: `wkhtmltopdf-binary-edge ~> 0.12.5`

platform/distribution and version: Dokku container running on Ubuntu 18.04

**Comment by unixmonkey** [comment]
@Lucasvn I am unfamiliar with Dokku, but it looks like you need to have `libpng` installed inside the docker container that your application runs inside of.

From a little bit of googling, it seems you should be able to add it to the `Dockerfile` if you have one with something like `apt-get install -y libping`.

Please post back if you figure it out so others can benefit from the knowledge.

**Comment by Lucasvn** [comment]
I was able to solve the problem by using [dokku-apt](https://github.com/F4-Group/dokku-apt) to install the libpng inside my dokku container.
