### ISSUE TITLE
Feature Request: Add rubygems metadata

### ISSUE THREAD

**Issue by olleolleolle** [mileszs/wicked_pdf#855]
## Issue description

When browsing RubyGems.org, it's cool to be able to see CHANGELOG.md. Without a [RubyGems metadata section](https://guides.rubygems.org/specification-reference/#metadata) linking directly to it, it's less easy to find.

## Expected or desired behavior

When I navigate to this gem's page on RubyGems.org, I see the changelog_uri listed as a changelog link in the side panel.

## System specifications

n/a

**Comment by olleolleolle** [comment]
(Perhaps this Issue can be labeled hacktoberfest or good first issue?)

**Comment by unixmonkey** [comment]
@olleolleolle Sounds great. PRs welcome. Are you planning to do this, or just pointing it out for others?

**Comment by olleolleolle** [comment]
@unixmonkey I'm pointing it out, for hacktober-fest hunters of Issues to fix.

**Comment by unixmonkey** [comment]
@olleolleolle Thanks for the tip. Someone has already picked this up and run with it. It'll show up on RubyGems next time I cut a release, which I'm planning to do pretty soon.
