### ISSUE TITLE
problem with webpack to generate a PDF

### ISSUE THREAD

**Issue by arabakevin** [mileszs/wicked_pdf#858]
## Issue description
I use Rails and webpack with docker. But when i try to generate a PDF i have this issue.
I have already try the #857, but the issue is unchanged.

![Capture_decran_2019-10-07_a_18 09 34](https://user-images.githubusercontent.com/16837548/66388684-f4b7e680-e9c6-11e9-8be8-54219de5272a.png)

wicked_pdf file config 

```ruby
WickedPdf.config = {
  #Path to the wkhtmltopdf executable: This usually isn't needed if using
  # one of the wkhtmltopdf-binary family of gems.
  #exe_path: "/usr/local/bin/wkhtmltopdf"
  #or
  #exe_path: Gem.bin_path("wkhtmltopdf-binary', 'wkhtmltopdf")
  #Layout file to be used for all PDFs
  #(but can be overridden in render :pdf calls)
  #layout: "pdf.html",
}
```

Rails controller to generate PDF:
```ruby
render pdf: I18n.t('packs.administrative.attendance_sheet'),
  title: I18n.t('packs.administrative.attendance_sheet'),
  disposition: 'inline',
  template: pdf_template,
  layout: pdf_layout,
  orientation: 'Landscape',
  show_as_html: params[:debug].present?
```
with the methods

```ruby
def pdf_layout
  'layouts/pdf.html.slim'
end
```
```ruby
def pdf_template
  'ideas/export.pdf.slim'
end
```

**layouts/pdf.html.slim**
```slim
doctype html
html
  head
    title= t('.title')
    meta charset='UTF-8'
    = wicked_pdf_stylesheet_pack_tag("stylesheets.css")
    = wicked_pdf_javascript_pack_tag("export")
  body
    br
    = yield
```

**ideas/export.pdf.slim**
```slim
p#p2 Hello World!
p The paragraph above was changed by a script
```

## System specifications

wicked_pdf (1.4.0)
wkhtmltopdf-binary (0.12.4)

platform/distribution :
**docker**

**Comment by EdisonArango** [comment]
Please test if my workaround works for you:

https://github.com/mileszs/wicked_pdf/issues/857#issuecomment-538790534

And be aware for now this will only work when you have webpack dev server not running.

**Comment by arabakevin** [comment]
when i try your workaround i have an other issue when i launch the application.

![Capture d’écran 2019-10-10 à 06 38 26](https://user-images.githubusercontent.com/16837548/66539542-97d44180-eb28-11e9-8d8f-8036b1cb92c9.png)

i don't understand your last sentence, `this will only work when you have webpack dev server not running` can you be more precise please ?
Thanks a lot for your help.

**Comment by EdisonArango** [comment]
The thing is the assets configuration is added when you have `require "sprockets/railtie"` in your `application.rb` file, but when you use webpacker then you don't need it, but wicked still tries to get the assets config even when using webpacker, maybe you can just try adding sprockets. And the webpack dev server is a binary that you can start using `bin/webpack-dev-server` and you use on development to watch for assets changes and regenerate the bundles.

**Comment by arabakevin** [comment]
sorry but i have the same issue again.
i share with you my `application.rb`
<img width="721" alt="Capture d’écran 2019-10-10 à 21 21 32" src="https://user-images.githubusercontent.com/16837548/66599627-f985c180-eba3-11e9-9604-ceee5b5a5570.png">
Thanks for your help.

**Comment by EdisonArango** [comment]
Then just try removing my workaround and uncommenting `require "sprockets/railtie"`

**Comment by arabakevin** [comment]
not working too. I will check with an other library.
Thanks.
Kevin
