### ISSUE TITLE
When text is too long, PDF gets very tiny

### ISSUE THREAD

**Issue by altjx** [mileszs/wicked_pdf#862]
Hi there,

I noticed that if I am trying to render a piece of text on the screen and it doesn't have any space breaks in it, the entire PDF gets extremely tiny. For example, if you try to just simply add something like "`<p>HELLOWORLD</p>`" (like repeating HELLOWORLD 800 times) and then generate the PDF, the text in the PDF seems to get very tiny as if it's trying to read it all on one line. It doesn't seem to be wrapping the long text onto the next line.

Any thoughts on this?

**Comment by unixmonkey** [comment]
It's doing what your web browser would do if it were rendered that way and printed using the browser print option.

You can control this with CSS by setting `word-break: break-word;` on the containing element.

**Comment by altjx** [comment]
Gotcha. Thanks @unixmonkey!!!!

**Comment by altjx** [comment]
Hey @unixmonkey,

Do you mean something like this? 

`<td><pre><code style="word-break: break-word;"><%= evidence.evidence_data.html_safe %></code></pre></td>`

or like this maybe? 

`<td><pre style="word-break: break-word;"><code><%= evidence.evidence_data.html_safe %></code></pre></td>`

I tried both but no luck. What I found what worked was just trimming the data if it exceeds 1500 characters to insert a new line or page break every 150 characters.
