### ISSUE TITLE
open-uri is a security issue

### ISSUE THREAD

**Issue by shaicoleman** [mileszs/wicked_pdf#863]
OpenURI is a security issue, please avoid using it
https://sakurity.com/blog/2015/02/28/openuri.html

It is currently used in https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/wicked_pdf_helper/assets.rb

As it monkey-patches `Kernel.open` it opens up security vulnerabilities in the entire app, not just in the gem itself

**Comment by unixmonkey** [comment]
Thank you for pointing this out. If you can help replace it's current usage with a more secure alternative, that would be very much appreciated. If not, I'll try to get to it in the next few days.

**Comment by shaicoleman** [comment]
I've opened a PR

**Comment by shaicoleman** [comment]
@unixmonkey, any chance of looking into the PR?

**Comment by shaicoleman** [comment]
With Ruby 2.7, the existing code trigger a deprecation warning:
`warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`

**Comment by unixmonkey** [comment]
This is now in version 2.0.1.

Thank you so much for putting this together!
