### ISSUE TITLE
Timeout error with single threaded server

### ISSUE THREAD

**Issue by shaicoleman** [mileszs/wicked_pdf#865]
When rails is started in single threaded mode, and using wicked pdf, e.g.
`<%= wicked_pdf_stylesheet_pack_tag 'stylesheets/example' %>`

The rails server hangs, and I'm getting the following error:
`ActionView::Template::Error (Net::ReadTimeout with #<TCPSocket:(closed)>):`

This is because the current implementation makes an an extra HTTP call to fetch the CSS. This is also very inefficient, and it needs to go through the full request stack.

version: `wicked_pdf (1.4.0)`

**Comment by unixmonkey** [comment]
This is not the fault of WickedPDF, but that your stylesheet is being served from the same server in the same thread, so when your render requests the stylesheet, that request gets queued until the PDF request is done, which results in a deadlock, each waiting for the other to finish.

If that resource were compiled, inline, or on another host, it would be fine.

In development mode, `wicked_pdf_stylesheet_pack_tag` merely proxies to `stylesheet_pack_tag`. In non-development environments, it inlines the CSS from a compiled stylesheet.

I would suggest you run in development with a similar setup as production, with multiple threads, or optimize your external CSS and JS to be inline or precompiled.

If you have an idea on how to improve on this behavior, I'd love to hear it.

**Comment by shaicoleman** [comment]
Webpack is compiled in my development environment, it should just read it from the filesystem instead of doing an HTTP request

**Comment by shaicoleman** [comment]
For now I've managed to work around the issue by putting the following in the ERB template:
`<style><%= File.read(File.join(Rails.public_path, Webpacker.manifest.lookup('stylesheets/pdf/org-chart.css'))).html_safe %></style>`

**Comment by unixmonkey** [comment]
Thank you for this detail on your workaround. I should be by now, but am not yet very well versed on how the webpacker asset management works. This gives me something to try, although I think that the public path may not always be the right place to look. Perhaps some combination of the `asset_host` and `public_output_path` from the webpacker configuration?

**Comment by shaicoleman** [comment]
Haven't used webpacker before myself, here's the workaround without inlining::
```
  <link rel="stylesheet" href="<%= Webpacker.manifest.lookup('stylesheets/example.css') %>">
```
