### ISSUE TITLE
PDF is generated without screen-reader-friendly PDF Tags

### ISSUE THREAD

**Issue by RaymondFallon** [mileszs/wicked_pdf#866]
## Issue description

Generated PDFs contains no "tags."

Users who access PDFs using screen readers or other assistive technology rely on tags to access the PDF's content. Tools like Adobe Acrobat DC Pro are able to generate tags based on the PDF's content... but this a flawed process. It would be ideal if `wicked_pdf`--which has access to the original HTML tags--was able to generate the related PDF tags.

## Expected or desired behavior

PDF tags are generated, correspond to the original HTML tags, and are included in the PDF document.

## System specifications

wicked_pdf version: `1.1.0`
Rails version: `5.0.7.2`

**Comment by unixmonkey** [comment]
This project doesn't build the PDFs, only helps you gather your HTML into a format that `wkhtmltopdf` can consume, and I don't think it can do this.

I suggest you bring this up on [the wkhtmltopdf issue tracker](https://github.com/wkhtmltopdf/wkhtmltopdf/issues).

**Comment by RaymondFallon** [comment]
Got it. Thanks for the prompt response!
