### ISSUE TITLE
How can I get the current page number in wicked_pdf?

### ISSUE THREAD

**Issue by thaivankhoa** [mileszs/wicked_pdf#867]
Hi everyone,

My current problem is I need to get current page number and use it to perform some other functions. But is there any feature in wicked_pdf, provide the solution for it? (return page number directly) Inspire of query DOM element of `<div class="page"></div>`

I haven't found any solutions yet. So Thanks for reading. And I hope ur guys can give me some advises.

**Comment by unixmonkey** [comment]
@thaivankhoa Please see the [part of the README on Page numbering](https://github.com/mileszs/wicked_pdf#page-numbering).

One caveat is that this only works in headers and footers, since the entire body is rendered in one go, then the headers and footers are applied to each page of the resulting PDF before being saved.

Let me know how it goes!

**Comment by thaivankhoa** [comment]
Thanks you so much for this helpful information @unixmonkey,

I will try to collect the information by JS, after the "number_pages()" function executed.

**Comment by bartimaeus** [comment]
@unixmonkey I am struggling to get headers or footers showing. I'm running in docker `ruby:2.6.3-alpine3.10` with wkhtmltopdf `0.12.5`

**Initializer**
```ruby
WickedPdf.config = {
 WickedPdf.config = {
  exe_path: "/usr/bin/wkhtmltopdf"
}
```

**Controller**
```ruby
send_data(
  WickedPdf.new.pdf_from_string(
    render_to_string(
      template: 'v1/users/user_summary',
      layout: "layouts/pdf.html",
      encoding: 'UTF-8'
    ),
    header: {
      right: '[page] of [topage]'
    },
    footer: {
      html: {
        template: 'shared/_footer.pdf',
        layout: 'layouts/pdf',
        formats: :html,
        locals: {
          user: @user,
          document_title: 'User Summary'
        }
      }
    }
  ),
  filename: "#{@user.full_name}: User Summary.pdf",
  type: 'application/pdf',
  disposition: :inline, # debugging/development
)
```

**layouts/pdf.html.erb**
```ruby
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <style>
      body, html {
        background-color: blue;
        margin: 0;
        padding: 0;
      }
      div.alwaysbreak { page-break-before: always; }
      div.nobreak:before { clear:both; }
      div.nobreak { page-break-inside: avoid; }
      ul {
        margin: 0;
        padding-left: 20px;
      }
      li {
        font-size: 11px;
        line-height: 16px;
      }
      table.bordered {
        border-collapse: collapse;
        page-break-inside: auto;
      }
      table.bordered th {
        background-color: #ddd;
        font-weight: normal;
      }
      table.bordered tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
      table.bordered td {
        padding: 5px 10px;
      }
      table.bordered, table.bordered th, table.bordered td {
        border: 1px solid #ddd;
        font-size: 11px;
        cell-spacing: 0;
        cell-padding: 0;
      }
      thead { display: table-header-group; }
      h5.wellness-heading {
        margin-bottom: 5px;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```

**views/shared/_footer.pdf.erb**
```ruby
<% @user = local_assigns[:user] %>
<% @document_title = local_assigns[:document_title] %>

<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <style>
      body, html {
        margin: 0;
        padding: 0;
      }
      .page-information {
        float: left;
        font-size: 12px;
        padding-top: 10px;
        width: 75%;
      }
      .page-count {
        float: right;
        font-size: 12px;
      }
    </style>
    <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>
  </head>
  <body onload="number_pages()">
    <div class="page-information"><%= @user.full_name %>&nbsp;<span style="font-size:10px;">(ID: <%= @user.external_id %>)</span>&nbsp;&bull;&nbsp;<%= @document_title %></div>
    <div class="page-count"><span class="page"></span> of <span class="topage"></span></div>
  </body>
</html>

```

I am trying a basic header with page numbers as well as a

**Comment by unixmonkey** [comment]
I'm not sure if this is the problem or not, but It looks like the footer is being rendered both as a full HTML document, but also has a layout applied, so it would be an invalid HTML document with two DOCTYPES and 2 `<html>` elements.

**Comment by bartimaeus** [comment]
Thanks for the suggestion. I updated the footer to use `layout: nil`. Still no go. Even trying `footer: { center: 'Testing' } ` doesn't seem to include the footer.

I'm looking at the [Advanced usage](https://github.com/mileszs/wicked_pdf) and will go back to a very basic example to see if I can get headers and footers working.

**Comment by bartimaeus** [comment]
Yeah, even a basic example is missing the header and footer:

```ruby
send_data(
  WickedPdf.new.pdf_from_string(
    '<h1>Hello world!</h1>',
    header: { right: '[page] of [topage]'},
    footer: { center: 'TEST' }
  )
)
```

**Comment by unixmonkey** [comment]
Ah, I think the header and footer are likely rendering, but might be covered up by your body content, you may need to add some margin-top and margin-bottom on `<body>` with CSS. While debugging, it can help to set your header and footer body background color to something different than your main PDF body so you can see it's boundaries.

**Comment by bartimaeus** [comment]
All great suggestions. I thought I did try playing with the Wicked PDF margin options but I will try again. Thanks!

I'm wondering if this might be related to the version of `wkhtmltopdf`. I just tried the following in docker:

**pdf.html**
```html
<!doctype html>
<html>
    <body>
           <h1>Hello World!</h1>
    </body>
</html>
```

`wkhtmltopdf --footer-right "Hello!" pdf.html test.pdf`

No footer was added by **wkhtmltopdf**. I'll try another version of **wkhtmltopdf** and see if that also makes a difference.

**Comment by unixmonkey** [comment]
Great debugging technique. IIRC `wkhtmltopdf` needs to be compiled with QT support for a lot of things to work. I don't remember if headers and footers are included in that or not, but that sounds like a good place to check. Are you installing `wkhtmltopdf` from a package, or one of the binary provider gems like https://github.com/zakird/wkhtmltopdf_binary_gem ?

**Comment by bartimaeus** [comment]
Thanks! I'll try a test with your docker binaries. Could be a missing library in alpine linux.

**Comment by bartimaeus** [comment]
Okay, I ended up mirroring https://github.com/madnight/docker-alpine-wkhtmltopdf/blob/master/Dockerfile and that made **wkhtmltopdf** work with alpine linux. Sorry for the false alarm.

**Comment by unixmonkey** [comment]
Glad you got it worked out. I'm certain it will help others in the future, and gives me a good reference to point people too. Thanks!
