### ISSUE TITLE
Rails 3.2 :handlers and :formats support

### ISSUE THREAD

**Issue by kylejginavan** [mileszs/wicked_pdf#87]
It is no longer valid to pass the format "pdf" or handler "erb" in the template name.  Therefore, two more parameters are needed to handle :handlers and :formats.

render :pdf                            => 'file_name',
    :template                       => 'things/show.pdf.erb',
end

It was just deprecated in 3.2 and will be out in Rails 4, therefore, now is a good time to add this.  Please get back to me.

Thanks,
KG

**Comment by joshuapinter** [comment]
Just to help others, I had to remove the `.pdf.erb` from the header and footer template references to remove this deprecation warning.

So, this: 

```ruby
# Deprecation Warning generated.
footer: { html: { template: 'application/_footer.pdf.erb' } },        
header: { html: { template: 'application/_header.pdf.erb' } }
```

Became:

```ruby
# No Deprecation Warning.
footer: { html: { template: 'application/_footer' } },
header: { html: { template: 'application/_header' } }
```

The files and filenames themselves stayed the exact same, though.

**Comment by azhaganandhan** [comment]
Just to help others, I had to remove the .pdf.erb from the header and footer template references to remove this deprecation warning.

So, this:

# Deprecation Warning generated.
footer: { html: { template: 'application/_footer.pdf.erb' } },        
header: { html: { template: 'application/_header.pdf.erb' } }
Became:

# No Deprecation Warning.
footer: { html: { template: 'application/_footer' } },
header: { html: { template: 'application/_header' } }
The files and filenames themselves stayed the exact same, though.

**Comment by unixmonkey** [comment]
I removed most of the explicit references to template/file extensions in the README in [this commit](https://github.com/mileszs/wicked_pdf/commit/6203cd190d17fba745a92c8c924cbb840da819b1), since they shouldn't be necessary now that those handlers are specified in modern versions of Rails.

Let me know if I've missed anything.
