### ISSUE TITLE
cannot allocate memory - /app/vendor/ruby/2.3.0/bin/wkhtmltopdf

### ISSUE THREAD

**Issue by jadamdipak** [mileszs/wicked_pdf#873]
I'm getting the error when on production when I create the PDF

## System specifications

wicked_pdf gem version (1.1.0):

wkhtmltopdf version (0.12.3):

**Comment by unixmonkey** [comment]
Sounds like you need more memory or swap space on your server to load everything needed to generate some PDFs.

**Comment by jadamdipak** [comment]
@unixmonkey but I have already a sufficient memory 16GB(RAM) on my server
