### ISSUE TITLE
ActionView::Template::Error: undefined method `_app_views_premium_plan_mailer_receipt_html_slim___1442315054042332787_47012634005320' for #<#<Class:0x00005583f40f3110>:0x00005583f40f2620>

### ISSUE THREAD

**Issue by jji-fieldwire** [mileszs/wicked_pdf#878]
## Issue description
Upgrading to Rails 6, my Rspec tests involving wicked_pdf suddenly fail.

## Expected or desired behavior
PDF generated without hiccups

## System specifications
macOS 10.14.6, Sprockets 4.0.0, Rails 6.0.2.1
Also being run in CircleCI

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
1.4.0

wkhtmltopdf version (output of `wkhtmltopdf --version`):
w/e version is automatically installed (0.12.5 I believe)

Here's the culprit code:
```ruby
view = ActionView::Base.with_empty_template_cache.new(ActionView::Base.build_lookup_context(ActionController::Base.view_paths), locals)
view.class_eval do
  include WickedPdf::WickedPdfHelper
end
template = S3File.template(file_kind)
html_string = view.render(template: 'premium_plan_mailer/receipt')
```

Error output:
```
     Failure/Error: html_string = view.render(template: 'premium_plan_mailer/receipt')
     
     ActionView::Template::Error:
       undefined method `_app_views_premium_plan_mailer_receipt_html_slim___3157936894315145092_47295460519140' for #<#<Class:0x00005607b1c45bf8>:0x00005607b1c45888>
     # ./app/workers/generate_pdf_upload_to_s3_worker.rb:115:in `generate_html'
     # ./spec/workers/generate_pdf_upload_to_s3_worker_spec.rb:206:in `block (3 levels) in <top (required)>'
     # ./spec/isolation_from_db_enforcer.rb:23:in `enforce_if_required'
     # ./spec/spec_helper.rb:173:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:157:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `_app_views_premium_plan_mailer_receipt_html_slim___3157936894315145092_47295460519140' for #<#<Class:0x00005607b1c45bf8>:0x00005607b1c45888>
     #   ./app/workers/generate_pdf_upload_to_s3_worker.rb:115:in `generate_html'
```

Template:
```slim
.container class=('pdf-padding' if @is_pdf)
  #receipt
    #block.center
      - if @is_pdf
        = wicked_pdf_image_tag 'Icon6WithText-500.png', class: 'logo'
```

**Comment by unixmonkey** [comment]
This isn't really a problem with `wicked_pdf`, but how you are rendering this template outside of a controller. This is kind of a hack to create render a view without a controller action.

The rendering engine changed in Rails 6, causing this hack to stop working.

There's an official way to render outside a controller now, that should look a lot more like this now:
```ruby
html_string = ApplicationController.render(
  template: 'premium_plan_mailer/receipt',
  locals: locals
)
```

Let me know how it goes!

**Comment by jji-fieldwire** [comment]
For whatever reason, accessing locals via `@local1` works when I'm rendering from a Mailer and locals are instance variables. When I try to insert them via `locals: locals`, they are accessed in the template without the '@', i.e. `local1`

Unfortunately, we're using the same template for both the Mailer and the PDF generator, so unless I want to copy/paste `defined?(@local1) ? @local1 : local1`, I'm out of luck.

Here's what I ended up doing:
```Ruby
    lookupcontext = ActionView::LookupContext.new( [Rails.root.join('app/views')] )
    view = ActionView::Base.with_empty_template_cache.new(lookupcontext, locals)

    view.class_eval do
      include WickedPdf::WickedPdfHelper
    end
    html_string = view.render(template: 'mytemplate')
```

It seems calling `ActionController::Base.view_paths` yields:
```Ruby
#<ActionView::PathSet:0x000055687b9b8320 
@paths=[#<ActionView::OptimizedFileSystemResolver:0x000055687b9b82d0 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", 
@unbound_templates=#<Concurrent::Map:0x000055687b9b82a8 entries=0 default_proc=nil>, 
@cache=#<ActionView::Resolver::Cache:0x55687b9b8230 keys=0 queries=0>, 
@path="/ruby-app/app/views">]>
```
while calling `ActionView::LookupContext.new( [Rails.root.join('app/views')])` spits out:
```Ruby
#<ActionView::LookupContext:0x000055687b975db8 
@details_key=nil, 
@digest_cache=nil, 
@cache=true, 
@prefixes=[], 
@details={:locale=>[:"en-US", :en], 
:formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :vtt, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :mp3, :ogg, :m4a, :webm, :mp4, :otf, :ttf, :woff, :woff2, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], 
:variants=>[], 
:handlers=>[:raw, :erb, :html, :builder, :ruby, :slim]}, 
@view_paths=#<ActionView::PathSet:0x000055687b974d50 @paths=[#<ActionView::OptimizedFileSystemResolver:0x000055687b974cb0 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", 
@unbound_templates=#<Concurrent::Map:0x000055687b974c38 entries=0 default_proc=nil>, 
@cache=#<ActionView::Resolver::Cache:0x55687b974b48 keys=0 queries=0>, 
@path="/ruby-app/app/views">]>>
```
Maybe the lookup context returned by `view_paths` just doesn't pick up my template, while the new one does? Not sure if my reasoning makes any sense, I've only been working with Ruby/Rails for 2 months now and am still a complete noob.

**Comment by unixmonkey** [comment]
I think you can specify instance variable locals with something like:
```ruby
html_string = ApplicationController.render(
  template: 'premium_plan_mailer/receipt',
  locals: { '@local1' => 'something', '@pdf' => true }
)
```

I’m on my phone so I can’t check right now, but let me know if that works or not.

I’d really recommend moving away from using lookup context and class_eval if you can.

**Comment by jji-fieldwire** [comment]
Like I said previously, for some reason if the template is rendered through the mailer, then accessing it using `@local1` works fine. But if rendering in my pdf generator class, it has to be accessed via `local1` without "@" for some reason.

```Slim
.container class=('pdf-padding' if defined?(@local1) && @local1 || local1)
```

This is legacy code not written by me, so I guess my concern is just getting it working again with Rails 6, not so much rewriting it without lookup context and class_eval 😐

**Comment by unixmonkey** [comment]
I was wrong above, but only by a little bit. Use `assigns` to make instance variables, use `locals` to define local methods:
```ruby
html_string = ApplicationController.render(
  template: 'premium_plan_mailer/receipt',
  locals:  { local1: 'something', pdf: true },
  assigns: { local1: 'something', pdf: true }
)
```

This will make those variables available as either instance or locals. This is part of Rails, not `wicked_pdf`.
If you want to adapt your existing view context hack, it should work there, too:
```ruby
lookupcontext = ActionView::LookupContext.new( [Rails.root.join('app/views')] )
view = ActionView::Base.with_empty_template_cache.new(lookupcontext, locals)

view.class_eval do
  include WickedPdf::WickedPdfHelper
end
html_string = view.render(template: 'mytemplate', assigns: { local1: 'something' })
```

**Comment by jji-fieldwire** [comment]
`assigns` isn't a parameter in `.render`,[ it's a parameter in `ActionView::Base.new`](https://apidock.com/rails/ActionView/Base/new/class), which I'm already setting.

For future readers:

- [`ApplicationController` docs](https://edgeapi.rubyonrails.org/classes/ActionController/Renderer.html)

**Comment by jji-fieldwire** [comment]
I think I figured out what's going on.

Precursor [(rails/rails issue 37528):](https://github.com/rails/rails/issues/37528)

> I suspect the root cause lies in #35036 where, as I understand, all subclasses of ActionView::Base shared a common module for compiled templates. Now that each subclass has a different module for compiled templates, it seems as if the template gets marked as compiled so when it's rendered in a different context that method isn't available.

Reply:
> It works in that order because the subclass-instance can lookup the compiled template-method on the ActionView::Base but not the other way around.
> 
> In the case above, the details cache points the resolver towards the compiled method on the subclass, but when the ActionView::Base-class tries to execute said method, it naturally won't be dispatched to the subclass.

Previously, I was reusing a lookup context (or at least creating a lookup context using the old `ActionController::Base.view_paths`). When I went to render the template, it would look for the template method `_app_views_premium_plan_mailer_receipt_html_slim___3157936894315145092_47295460519140`, and then throw `ActionView::Template::Error: undefined method` because it's not in the same module as the one where that method exists.

[`ActionView::Base.with_empty_template_cache` builds a generic `ActionView::Base` subclass instance, not an actual `ActionView::Base` instance](https://github.com/rails/rails/blob/bc5d9567be44e6241a049c01605ad6cfefe42e10/actionview/lib/action_view/base.rb#L183-L191) which explains the mismatched modules.
