### ISSUE TITLE
JavaScript is not executed at all with PDF format

### ISSUE THREAD

**Issue by arabakevin** [mileszs/wicked_pdf#884]
Given the following simple HTML code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  </head>
  <body>
    <p id="first-line">This is a line.</p>

    <script>
      let newDiv = document.createElement('div')
      newDiv.innerHTML = "Inserted line by JavaScript."
      document.body.insertBefore(newDiv, document.getElementById('first-line'))
    </script>
  </body>
</html>
```
Opening this page in my web browser. I can see the following.

<img width="321" alt="Capture d’écran 2020-02-05 à 07 21 06" src="https://user-images.githubusercontent.com/16837548/73816138-28294700-47e8-11ea-8a1c-735960106787.png">

When i'm running the following command:

```
wkhtmltopdf ./test.html ./test.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

[test.pdf](https://github.com/mileszs/wicked_pdf/files/4157753/test.pdf)

So everything looks fine, but please see the attach PDF file.
Can you please help me to solve this issue ?

**Comment by arabakevin** [comment]
Hi,
Do you have any news/ideas or can i help you to help me ?
Missing details or informations ?
Thanks.

**Comment by unixmonkey** [comment]
@arabakevin Change `let` to `var`.

The version of Webkit `wkhtmltopdf` uses under-the-hood is too old for a lot of modern JS and CSS features.

There's also a potential for the PDF to generate before the JS finishes if your JS takes a long time. To get around that you can pass the `javascript_delay: 1000` option to make it wait 1 second before converting to PDF.

Please let me know if that works for you or not.

**Comment by arabakevin** [comment]
Hi,
When i use your solution, it's working.
Thanks a lot.
Best.
