### ISSUE TITLE
Linux mint integration for gem. 

### ISSUE THREAD

**Issue by FranCoFeliz** [mileszs/wicked_pdf#885]
## Issue description
The gem asks for linux mint while in linux mint.

## Expected or desired behavior
The gem asks for ubuntu binary in mint
## System specifications

wicked_pdf gem version: 1.4.0

wkhtmltopdf version: 0.12.5

and version if one is used: 

platform/distribution and: Linux Mint 19.1

I was getting this issue: 
![image](https://user-images.githubusercontent.com/52421533/73963529-10c88780-48d6-11ea-80a9-47738cec34a6.png)

I was able to fix this by changing the name of the file wkhtmltopdf_ubuntu_18.04_amd64.gz to the one reported in the error: wkhtmltopdf_linuxmint_19.1_amd64.gz

**Comment by unixmonkey** [comment]
Thank you for the report, but this is not a problem with `wicked_pdf`, but an issue with `wkhtmltopdf-binary`.

There is a PR to add Linux Mint support here you may want to watch: https://github.com/zakird/wkhtmltopdf_binary_gem/pull/56
