### ISSUE TITLE
is it possible to create a non editable pdf or I can only save screenshots of html in pdf so that it contains some safety.

### ISSUE THREAD

**Issue by jawadakram20** [mileszs/wicked_pdf#888]
## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by unixmonkey** [comment]
You can use `wkhtmltoimage` to create an image "screenshot" of an HTML document in very much the same way as `wkhtmltopdf`, but this gem does not natively support that. You may be able to hack it in by replacing `WickedPdf.config = { exe_path: '/path/to/wkhtmltoimage' }`, but I'm not sure what would be compatible, and what wouldn't. You'd certainly need to change your return content-type.

Alternately, you can shell out to it to generate the image, then bring that into your app somehow.

Let me know how it goes!
