### ISSUE TITLE
wickedpdf with font from github

### ISSUE THREAD

**Issue by jeanmarcgraufogel** [mileszs/wicked_pdf#898]
I tried to use font from github repo within file pdf.erb and it doesn't work

app/assets/stylesheets/fonts.scss.erb:
@font-face {
    font-family: 'rawline';
    src: url('https://raw.githubusercontent.com/misuchiru03/font-times-new-roman.git');
    src: url(asset-path('https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/font/rawline-100.eot?#iefix') format('embedded-opentype')),
         url(asset-path('https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/font/rawline-100.woff2') format('woff2')),
         url(asset-path('https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/font/rawline-100.woff') format('woff')),
         url(asset-path('https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/font/rawline-100.ttf') format('truetype')),
         url(asset-path('https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/font/rawline-100.svg') format('svg'));
    font-weight: 100;
    font-style: normal;
}

in config/aplication.erb
 config.assets.paths << Rails.root.join("app", "assets", "stylesheets", "fonts")

app/views/prestations/tva_reduce.pdf.erb
<head>
  <meta charset="UTF-8">
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
  <%= wicked_pdf_stylesheet_link_tag "pdf.css" -%>
<link href="https://raw.githubusercontent.com/misuchiru03/font-times-new-roman.git" rel="stylesheet">
</head>
<body>
  <div style="color: black; font-family: 'rawline'">
    <%= render "tva_reduce_content.html" %>
  </div>

**Comment by unixmonkey** [comment]
Did you figure out what the issue was?
Could you please post a summary to help me and others?
