### ISSUE TITLE
Issue in Ubuntu 19.04 doesn't support

### ISSUE THREAD

**Issue by saleh-alhaddad** [mileszs/wicked_pdf#900]
## Issue description
when export to pdf it gave the issue 
PDF could not be generated!
     #    Command Error: /.rvm/gems/ruby-2.6.5@test/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf:40:in `<top (required)>': Invalid platform, must be running on Ubuntu 14.04/16.04/18.04 CentOS 6/7, Debian 8/9, or intel-based macOS (missing binary: /home/saleh/.rvm/gems/ruby-2.6.5@test/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_ubuntu_19.04_amd64). (RuntimeError)
     #   	from /.rvm/gems/ruby-2.6.5@test/bin/wkhtmltopdf:23:in `load'
     #   	from /.rvm/gems/ruby-2.6.5@test/bin/wkhtmltopdf:23:in `<main>'
     #   /.rvm/gems/ruby-2.6.5@test/gems/wicked_pdf-2.0.2/lib/wicked_pdf.rb:81:in `pdf_from_url'

## System specifications
Ubuntu 19.04

wicked_pdf gem version:
wicked_pdf (1.4.0)

**Comment by calrrox** [comment]
Hello @saleh-alhaddad, the problem is with the binary in `wkhtmltopdf_binary_gem` look at this issue: 

https://github.com/zakird/wkhtmltopdf_binary_gem/issues/62
