### ISSUE TITLE
H1 text does not breaks

### ISSUE THREAD

**Issue by rafaeldev** [mileszs/wicked_pdf#904]
## Issue description
The title on page sometimes broken like that:
![image](https://user-images.githubusercontent.com/4596160/79466165-994c5e00-7fd2-11ea-9682-ac8cee2ba3b0.png)

## Expected or desired behavior
I expected if the title does not have space for be write, "jump" for the next page.

I'm tried put "nobreak" class on H1 element, like this:
```erb
<div class="row outline">
  <div class="col">
    <h2 class="nobreak"><%= t_attr(Proposal, :activities).titleize %></h2>

    <p><%= sanitize @proposal.activities, attributes: %w(style href) %></p>
  </div>
</div>
```
**I'm wrong on any point?**

A disclaimer: I'm import bootstrap 4.

## System specifications
wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
```
wicked_pdf (1.4.0)
  wicked_pdf
```

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version:
Linux Deepin (debian based)

Thanks!

**Comment by unixmonkey** [comment]
Does the `nobreak` class have a CSS definition that would apply, like this?

```css
.nobreak:before { clear:both; }
.nobreak { page-break-inside: avoid; }
```
If it does, and still isn't working, all I can do is suggest trying to place the nobreak class on the surrounding col or row, or wrap your H1 with another element like a table row that has that class applied.

From what you posted, it might also be a good idea to force it to start on a new page with CSS like this:
```css
.alwaysbreak { page-break-before: always; }
```

Try a few things and let me know how it goes!

**Comment by rafaeldev** [comment]
Sorry, I forget add this detail... Yes, I put this classes on my `pdf.scss`. 

The `nobreak` class works very well when a add it on div which wrapper h1 and paragraph. Thanks for your suggestion:

```erb
<div class="container alwaysbreak">
  <div class="row outline nobreak">
    <div class="col">
      <h2><%= t_attr(Proposal, :diagnostic).titleize %></h2>

      <p><%= sanitize @proposal.diagnostic, attributes: %w(style href) %></p>
    </div>
  </div>
</div>
```

**Comment by unixmonkey** [comment]
Great! Thanks for letting me know. I'm closing this for now, but if you have any further questions on this topic, please let me know.

**Comment by rafaeldev** [comment]
Thanks for support!

I'm make some tests and the problem does not happens when the html "are raw" (no css applied):
```erb
<% 20.times do  %>
  <h1>TEST</h1>
<% end %>
```
I'm tested with h1 until h6. Works well.

I force height with a sibling container:
```erb
<div class="" style="margin-top: 90px; display: inline-block">
  <p>dummy</p>
</div>
<% 20.times do  %>
  <h1>TEST</h1>
<% end %>
```
...and its works too.

I think which the H1 error happens by any behavior with my css rules.

Well, almost you can add any disclaimer on README project saying _"You have bad format using own css-position-styles"_... I don't know...

PS.: All these test are import latest bootstrap css
