### ISSUE TITLE
Included JS not executing.

### ISSUE THREAD

**Issue by veeKewl** [mileszs/wicked_pdf#906]
I have a javascript that generates the HEADER and FOOTER of my PDF, it works perfectly fine when rendered in browser but when i generate it `from_url` it's not executing some of my css, and all js that i included, and YES i used tried using all the helpers on available on including javascript, nothing seems to work. 

I tried delaying the javascript also not working.

Im using Ruby On Rails, my assets are precompiled, it's just not executing my js. :) 

uhh help ?

**Comment by veeKewl** [comment]
![image](https://user-images.githubusercontent.com/35055551/79639397-299ac680-81be-11ea-8d6e-030d0d6fdf8d.png)
This is the JS it generated using `wicked_pdf_javascript_include_tag` if you noticed there are 2 `window.status` the other one is from the jsfile i included and the other one is i inserted directly in `wicked_pdf_javascript_include_tag` Helper, the one that i inserted directly is the only one that got executed but the rest that i included didn't.

**Comment by veeKewl** [comment]
![image](https://user-images.githubusercontent.com/35055551/79639492-c78e9100-81be-11ea-8c3e-9656cc3d9686.png)
this is where i tried to insert the `window.status` that's getting executed.

**Comment by rafaeldev** [comment]
Hi @veeKewl 

Days ago I can do this. See my implementation:
`#views/model_name/show.pdf.erb`
```erb
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Title</title>

    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_stylesheet_link_tag asset_path('logo.ico') %>
  </head>
  <body>
    <%= render partial: "show_content", formats: [:html] %>

    <%= wicked_pdf_javascript_include_tag "pdf" %>
  </body>
</html>
```

`# app/assets/javascripts/pdf.js`
```js
//= require jquery
//= require jquery.mask

$(".cnpj").mask('##.###.###/####-##');
```

How as old internet development, I import the javascript at the end of body tag.

**Comment by veeKewl** [comment]
> Hi @veeKewl
> 
> Days ago I can do this. See my implementation:
> `#views/model_name/show.pdf.erb`
> 
> ```
> <!DOCTYPE html>
> <html lang="pt-BR" dir="ltr">
>   <head>
>     <meta charset="utf-8">
> 
>     <title>Title</title>
> 
>     <%= wicked_pdf_stylesheet_link_tag "pdf" %>
>     <%= wicked_pdf_stylesheet_link_tag asset_path('logo.ico') %>
>   </head>
>   <body>
>     <%= render partial: "show_content", formats: [:html] %>
> 
>     <%= wicked_pdf_javascript_include_tag "pdf" %>
>   </body>
> </html>
> ```
> 
> `# app/assets/javascripts/pdf.js`
> 
> ```js
> //= require jquery
> //= require jquery.mask
> 
> $(".cnpj").mask('##.###.###/####-##');
> ```
> 
> How as old internet development, I import the javascript at the end of body tag.

Yes i am importing the javascript at the end of my body tag. :)

**Comment by veeKewl** [comment]
> Hi @veeKewl
> 
> Days ago I can do this. See my implementation:
> `#views/model_name/show.pdf.erb`
> 
> ```
> <!DOCTYPE html>
> <html lang="pt-BR" dir="ltr">
>   <head>
>     <meta charset="utf-8">
> 
>     <title>Title</title>
> 
>     <%= wicked_pdf_stylesheet_link_tag "pdf" %>
>     <%= wicked_pdf_stylesheet_link_tag asset_path('logo.ico') %>
>   </head>
>   <body>
>     <%= render partial: "show_content", formats: [:html] %>
> 
>     <%= wicked_pdf_javascript_include_tag "pdf" %>
>   </body>
> </html>
> ```
> 
> `# app/assets/javascripts/pdf.js`
> 
> ```js
> //= require jquery
> //= require jquery.mask
> 
> $(".cnpj").mask('##.###.###/####-##');
> ```
> 
> How as old internet development, I import the javascript at the end of body tag.

`<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <meta charset="utf-8">

  <%= render 'layouts/meta' %>

  <%= wicked_pdf_stylesheet_link_tag 'print/document', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<%= yield %>

<%= wicked_pdf_javascript_include_tag 'jquery3.min' %>
<%= wicked_pdf_javascript_include_tag 'pdf' %>


</body>
</html>
`

**Comment by veeKewl** [comment]
It's weir because it's executing the `script` that i inserted directly in the helper but not the other script from `read_asset(source)`.
