### ISSUE TITLE
Unable display Graph in Pdf view But display fine when show as html

### ISSUE THREAD

**Issue by moeezsaiyam** [mileszs/wicked_pdf#914]
Hi, 

I have created the pdf file using a wicked_pdf gem in rails. I'm creating graphs using graphs.js library and rendering those graphs in the show.pdf.erb file (pdf view). But no charts are being rendered. I have tried different versions of chart.js but nothing works. Displaying the pdf as html works perfectly. Also, I tried to set responsive: false in the chart.js and used javascript_delay for wicked pdf but it did not work as well.

In my controller:

render template: 'qmcontrols/show',:type => 'application/pdf', pdf: "#{@project.identifier}qmcontrol#{@qmcontrol.id}",
margin: {left: 15, right: 15 },
:footer => {:center => "#{@project.name} / #{@location_details[0]['location_company']} / #{@qmcontrol.checkitem_location}", :right => '[page] / [topage]' },window_status: "FLAG_FOR_PDF"

show.pdf.erb:

head tag:
<%= wicked_pdf_javascript_include_tag "plugin_assets/rtcharts/javascripts/chart.min.js" %>
<%= wicked_pdf_javascript_include_tag "plugin_assets/rtcharts/javascripts/chart.helper.js" %>
<%= wicked_pdf_stylesheet_link_tag "plugin_assets/rtcharts/stylesheets/rtdashboard.css" %>

body:

<div class="current-situation-chart">
  <p style ="text-align: center;">Current Situation Chart Will be displayed here</p>
  <% charts = controlchart %>
  <div class="rtdashboard grid-container grid-cols-2">
    <% if charts.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
    <% else %>
        <% charts.each do |graph| %>
      <div>
        <%=  render partial: 'rtcharts/bar.html.erb',
                      formats: [:html],
                      locals: graph %>

      </div>
      <div id="base64">

      </div>
      <p id="p1">Hello World!</p>

        <% end %>
    <% end %>
  </div>

  <script type="text/javascript">
    setTimeout((function () {
      window.status = "FLAG_FOR_PDF";
      var canvas = document.getElementById('dashboard_bar_chart_actual_situation_control');
      var dataUrl = canvas.toDataURL();
      var image = document.createElement('img');
      image.src = dataUrl;
      document.getElementById("p1").innerHTML = "SHOW Base 64 in p tag "+dataUrl;
      // append to the DIV element
      document.getElementById("base64").appendChild(image);
    }), 10000);
  </script></div>

It's working well when i do show_as_html:true and even show base 64 of canvas in a paragraph but when view in pdf It's not showing any graph nor any base64.
Please find the following attachments:

PDF VIEW:
![Screenshot from 2020-05-22 15-52-39](https://user-images.githubusercontent.com/42515773/82662215-e614fb80-9c46-11ea-84ea-ec6970c1b72d.png)

VIEW_AS_HTML: true

![Screenshot from 2020-05-22 15-51-47](https://user-images.githubusercontent.com/42515773/82662218-e7462880-9c46-11ea-8d42-486ef445eab4.png)

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 'wicked_pdf', '~> 2.0', '>= 2.0.2'

wkhtmltopdf version (output of `wkhtmltopdf --version`): 'wkhtmltopdf-binary', '~> 0.12.5.3'

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu

**Comment by moeezsaiyam** [comment]
Is there anyone to help?

**Comment by Wmeng98** [comment]
Hi @moeezsaiyam ,

Can you check the debug footnotes in the html view to confirm whether the expected View, Partials, Stylesheets, and Javascript files are included?

Similar issue opened here without resolution yet: https://github.com/mileszs/wicked_pdf/issues/817

**Comment by cesc1989** [comment]
Hi @moeezsaiyam Is it `chart.js`? I can't find `graph.js` on Google. Either way, I think you won't be able to render charts as they use canvas and some other advanced features `wkhtmltopdf` cannot work with as it's main dependency `Qt`, uses a very old version of Chromium/Webkit something like that.

I might be wrong, of course, but last time I tried rendering `chart.js` charts using this gem, I couldn't.

**Comment by moeezsaiyam** [comment]
Hi,

I did that by converting the graph (chart.js) to an image first and then embedding it in my PDF using quickchart.io.

You can see the following URL for converting chart.js to images using quickchart.io:

https://stackoverflow.com/questions/55352930/how-to-put-dynamic-graph-as-image-using-chart-js-in-image-tag-while-sending-emai
