### ISSUE TITLE
Noisy output: "QPainter::end: Painter ended with 2 saved states"

### ISSUE THREAD

**Issue by tonyc** [mileszs/wicked_pdf#92]
Not exactly sure what is causing this, but after upgrading to 0.7.5 our test output has become quite a bit noisier.  QT is logging the following message multiple times during our test runs:

QPainter::end: Painter ended with 2 saved states

**Comment by Tazmain** [comment]
I am seeing the same error but not sure what the cause is, I don't have wicked_pdf installed. So I would guess this is more of a QT issue.
