### ISSUE TITLE
wicked_pdf_image_tag helper does not render the picture with the release 0.12.6.2.

### ISSUE THREAD

**Issue by chaudard** [mileszs/wicked_pdf#927]
## Issue description
wicked_pdf_image_tag helper does not render the picture with the release 0.12.6.2.
Need to downgrade to release 0.12.4 to get the expected behavior (the picture appears)

## Expected or desired behavior
wicked_pdf_image_tag helper is working well with the very last release

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 2.1.0

wkhtmltopdf version (output of `wkhtmltopdf --version`): 0.12.6.2

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu 18.04.4 LTS

**Comment by unixmonkey** [comment]
That does not sound like a problem with wicked_pdf, but with `wkhtmltopdf`. The reason you picture likely isn't loading with the newer version for you, is that the system it is installed on must have the right supporting libraries (namely OpenSSL), otherwise it won't display images served open HTTPS.

It appears your system doesn't have what's needed to properly run the new version of `wkhtmltopdf`.

Please try installing one of the official packages from https://wkhtmltopdf.org/downloads.html, or use your package manager, which should be able to work out those dependencies.

**Comment by mayordwells** [comment]
@unixmonkey please help. I am also having this issue, even though I am using the latest version of every package, 

wkhtmltopdf version (output of `wkhtmltopdf --version`): wkhtmltopdf 0.12.6 (with patched qt)

wkhtmltopdf-binary (0.12.6.2)

wicked_pdf (2.1.0)

It's not working on Mac localhost, Linux Ubuntu on an AWS Cloud9 environment, as well as in our production environment running on Amazon Linux 2, all these OSes have OpenSSL installed.

**Comment by mayordwells** [comment]
Update: I downgraded `wicked_pdf` and `wkhtmltopdf-binary`

gem 'wicked_pdf', '~> 2.0.2'
gem 'wkhtmltopdf-binary', '~> 0.12.5.4'

using it together with the latest version of the software - wkhtmltopdf 0.12.6 (with patched qt)

and I can confirm that `image_tag` worked with this combination

**Comment by blazeblazeblaze** [comment]
Just came across the very same issue, which I suspect might have been introduced as part of the 0.12.6 upgrade of wkhtmltopdf ("https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4536: BREAKING CHANGE: block local filesystem access by default")

Following the advanced usage instructions from here: https://github.com/mileszs/wicked_pdf#advanced-usage-with-all-available-options, I explicitly set `enable_local_file_access: true`, which solved my issues locally and I was able to use the most recent version of both gems. 👍 Hope this helps anyone.

**Comment by martijn10kb** [comment]
With this option enabled it still renders no images for me. 
I use just normal `image_tag` though. If I use `wicked_pdf_image_tag` i get the error: `/tmp/signature20200826-92-1pia1fw.png is no longer under a load path: /app/app/assets/fonts, /app/app/assets/images ....`.

I'm running
`    wicked_pdf (2.1.0)
    wkhtmltopdf-binary (0.12.6.2)`

And when I use `wkhtmltopdf-binary (0.12.5.x)`n it works fine.
