### ISSUE TITLE
Rails and Ruby app is crashed after launch if i use wicked_pdf gem

### ISSUE THREAD

**Issue by PraisyA** [mileszs/wicked_pdf#929]
## Issue description
 Hello there ,
 I am new to Rails & Ruby as well as Wicked_Pdf , i have create a Rails project and added wicked_pdf gem .  I can able to generate the pdf from html as we expected , later i added Rails admin after add this and try to launch the project but it  crashed .
I removed the Wicked_pdf and its related data then able to launch the project , i am unable to solve this .
Did i miss anything ?  please help me ...

## Expected or desired behavior
![Wickedpdf](https://user-images.githubusercontent.com/30825040/87151819-25b8a500-c2d2-11ea-9023-019662198141.PNG)

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by kanchan-bluebash** [comment]
I am facing same issue, do we have any solution or work around for it?

**Comment by PraisyA** [comment]
Hello Kanchan,
Issue was solved after installed wkhtmltopdf (as i am using windows 10 machine ) , 
create a ruby file called wicked_pdf.rb under  **config/initializers** folder and it has below data 

**`
# frozen_string_literal: true

# WickedPDF Global Configuration
#
# Use this to set up shared configuration options for your entire application.
# Any of the configuration options shown here can also be applied to single
# models by passing arguments to the `render :pdf` call.
#
# To learn more, check out the README:
#
# https://github.com/mileszs/wicked_pdf/blob/master/README.md

WickedPdf.config = if Rails.env.production?
    {
      exe_path: Gem.bin_path('wkhtmltopdf-heroku', 'wkhtmltopdf-linux-amd64'),
      layout: 'application.pdf.html', # use 'pdf.html' for a pfd.html.erb file
      orientation: 'Portrait', # default , Landscape
      page_size: 'Letter',
      dpi: '300',
      print_media_type: true,
      margin: { top: 0, # default 10 (mm)
                bottom: 0,
                left: 0,
                right: 0 }
    }
  else
    {
      exe_path: 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe',
      layout: 'application.pdf.html', # use 'pdf.html' for a pfd.html.erb file
      orientation: 'Portrait', # default , Landscape
      page_size: 'Letter',
      dpi: '300',
      print_media_type: true,
      margin: { top: 0, # default 10 (mm)
                bottom: 0,
                left: 0,
                right: 0 }
    }
  end
`**


hope this will help to you.


Thanks

**Comment by mathieujobin** [comment]
This issue can be closed
