### ISSUE TITLE
Ubuntu 20.04 Rails 6 - Error: PDF could not be generated! - Error: Failed to load about:blank - after dev env upgrade

### ISSUE THREAD

**Issue by Xavoski** [mileszs/wicked_pdf#934]
PDFs were working fine in Rails 5.2. After i upgrade my dev env to a virtual machine (Virtualbox) with Rails 6, I am receiving the same error for any pdf that i have in my project. Because of that i think it is some problem with my OS or project configuration.

> RuntimeError - Failed to execute:
> ["/home/junior/.rbenv/versions/2.7.1/bin/wkhtmltopdf", "--encoding", "UTF-8", "--page-size", "A4", "--margin-top", "30", "--margin-bottom", "10", "--margin-left", "10", "--margin-right", "10", "--header-html", "file:////tmp/wicked_header_pdf20200803-3488-1r9k38l.html", "--footer-html", "file:////tmp/wicked_footer_pdf20200803-3488-th9rj2.html", "file:////tmp/wicked_pdf20200803-3488-13s183v.html", "/tmp/wicked_pdf_generated_file20200803-3488-ycry0o.pdf"]
> Error: PDF could not be generated!
>  Command Error: Loading pages (1/6)
> Warning: Blocked access to file                                   
> Warning: Blocked access to file 
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> :
>   app/controllers/pessoas_controller.rb:57:in `block (2 levels) in show'
>   app/controllers/pessoas_controller.rb:54:in `show'

 Older version works fine in prod like it used to in dev. I tried lot of suggestions from web and nothing.
Tried to remove header and footer, same:

> RuntimeError - Failed to execute:
> ["/home/junior/.rbenv/versions/2.7.1/bin/wkhtmltopdf", "--encoding", "UTF-8", "--page-size", "A4", "file:////tmp/wicked_pdf20200803-3488-1v39m6b.html", "/tmp/wicked_pdf_generated_file20200803-3488-fij18f.pdf"]
> Error: PDF could not be generated!
>  Command Error: Loading pages (1/6)
> Warning: Blocked access to file                                   
> Warning: Blocked access to file 
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown

```
respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'pessoa',
               # layout:'pdf.html',
               page_size: 'A4',
               template: 'pessoas/show',
               encoding: 'UTF-8',
               header: {
                 html: {
                   template: 'reports/report_header',
                   locals: { doc_title: 'Dados da Pessoa',
                             doc_sub_title: '',
                             doc_sub_sub_title: '' }
                 }
               },
               footer: {
                 html: {
                   template: 'reports/report_footer'
                 }
               },
               margin: { top: 30, bottom: 10, left: 10, right: 10 }
      end
```

## Expected or desired behavior
Generate a PDF file in browser.

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
wicked_pdf (2.1.0)
wicked_pdf

wkhtmltopdf version (output of `wkhtmltopdf --version`):
wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
Ubuntu 20.04 on a virtual machine (virtualbox) 
Running in development environment
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
Rails 6.0.3.2

Thanks for any help.

**Comment by unixmonkey** [comment]
Can you please try with the option `enable_local_file_access: true` and let me know if that helps or changes the errors any?

**Comment by Xavoski** [comment]
Well, some new information now.

> RuntimeError - Failed to execute:
> ["/home/junior/.rbenv/versions/2.7.1/bin/wkhtmltopdf", "--encoding", "UTF-8", "--enable-local-file-access", "--page-size", "A4", "--margin-top", "30", "--margin-bottom", "10", "--margin-left", "10", "--margin-right", "10", "--header-html", "file:////tmp/wicked_header_pdf20200803-4157-jrpdgt.html", "--footer-html", "file:////tmp/wicked_footer_pdf20200803-4157-swjqb3.html", "file:////tmp/wicked_pdf20200803-4157-xvne2y.html", "/tmp/wicked_pdf_generated_file20200803-4157-1pijzg3.pdf"]
> Error: PDF could not be generated!
>  Command Error: Loading pages (1/6)
> Error: Failed to load file:///assets/application.debug-0624b4d2b71dede78c449b0f711a9b50111d366e8d5dd3bb354fd2997f70fdb2.css, with network status code 203 and http status code 0 - Error opening /assets/application.debug-0624b4d2b71dede78c449b0f711a9b50111d366e8d5dd3bb354fd2997f70fdb2.css: No such file or directory
> Error: Failed to load file:///assets/application.debug-7e89fde401f8eec5d00422c02cf828966ef6075c6ebf43a80102f4910545e2ea.js, with network status code 203 and http status code 0 - Error opening /assets/application.debug-7e89fde401f8eec5d00422c02cf828966ef6075c6ebf43a80102f4910545e2ea.js: No such file or directory

**Comment by unixmonkey** [comment]
This part:

> Error: Failed to load file:///assets/application.debug-<SHA>.js

Tells me that the webpage is trying to load a relative-specified asset like `<script src="/assets/application.debug-<SHA>.js"></script>` directly from disk...

instead of either a file-based reference: `<script src="file://tmp/<tempdir>/application.debug-<SHA>.js"></script>`

or a full URL reference: `<script src="https://example.com/assets/application.debug-<SHA>.js"></script>`

Are you using the `wicked_pdf_javascript_include_tag` helper, which should make this work transparently?

Do you have application.js and css in your asset precompile path, or have some other means of copying the assets to `/public` or a CDN?

**Comment by Xavoski** [comment]
What is weird is that i didn't work on pdf related files from the time they were working. I saw the last error and was looking where those files are loaded, but can't find it.

My layout file (pdf.html.erb):
```
<!DOCTYPE html>
<html>
<head>
  <title>Report title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" charset="utf-8">

  <%= wicked_pdf_stylesheet_link_tag "report_styles/styles" -%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>
```
Header file:
```
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" charset="utf-8">
<%= wicked_pdf_stylesheet_link_tag "stylesheets/report_styles/header" -%>
</head>
<body>
  <div id="header-container">
      <div id="header-left">
        <%= wicked_pdf_image_tag 'logo_25_transparente.png', width: 140%>
      </div>
      <div id="header-center">
        <h2 class="doc-title"> <%= doc_title %> </h2>
        <p><%= doc_sub_title %></p>
        <p><%= doc_sub_sub_title %></p>
      </div>
      <div id="header-right">
        <p></p>
      </div>
  </div>
</body>
</html>
```
Footer file:
```
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= wicked_pdf_stylesheet_link_tag "report_styles/footer" -%>
  <script>
      function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
          var y = document.getElementsByClassName(x[i]);
          for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
      }
    </script>
</head>

<body onload="number_pages()">
  <div class="container-fluid">
    <div class="row d-table-row">
      <div class="col w-33 d-table-cell">
        <p>Ola</p>
      </div>
      <div class="col w-33 d-table-cell text-center">
        <p> <%= Time.now.to_formatted_s(:data_HM) %> </p>
      </div>
      <div class="col w-33 d-table-cell text-right">
        <p>Pg <span class="page"></span> / <span class="topage"></span></p>
      </div>
    </div>
  </div>
</body>
</html>
```
The assets precompile is on Rails standard configuration (i believe). Since the project was created, in development i just run `rails s` and hope Sprockets does everything.
The only lines related to assets i found in development.rb:
```
  # Debug mode disables concatenation and preprocessing of assets.
  # This option may cause significant delays in view rendering with a large
  # number of complex assets.
  config.assets.debug = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true
```

So, to make my answer short, i have no idea why it is loading the wrong file.

**Comment by Xavoski** [comment]
In my journey googling this, i turned `config.assets.debug` to false. It didn't fix the problem, but the last two lines changed to Warning. PDF could not be generated yet.

> Failed to execute:
> ["/home/junior/.rbenv/versions/2.7.1/bin/wkhtmltopdf", "--encoding", "UTF-8", "--enable-local-file-access", "--page-size", "A4", "--margin-top", "30", "--margin-bottom", "10", "--margin-left", "10", "--margin-right", "10", "--header-html", "file:////tmp/wicked_header_pdf20200803-4257-1f4o7x1.html", "--footer-html", "file:////tmp/wicked_footer_pdf20200803-4257-1nnv5z8.html", "file:////tmp/wicked_pdf20200803-4257-ur85gn.html", "/tmp/wicked_pdf_generated_file20200803-4257-fn240q.pdf"]
> Error: PDF could not be generated!
>  Command Error: Loading pages (1/6)
> [>                                                           ] 0%
> [======>                                                     ] 10%
> [============================>                               ] 47%
> Warning: Failed to load file:///assets/application-8a83895fe0e35a18531d1535b0720885744152eca3fd82ed2e893bc6624743f8.css (ignore)
> Warning: Failed to load file:///assets/application-34b926c555c25c2f28b7ca29704489386fed62e4c225a5ac866f46b62ab6400d.js (ignore)

**Comment by Xavoski** [comment]
Some relative good news.
The problem appears to be at layout file. I changed the `wicked_pdf_stylesheet_link_tag`:
From:
`<%= wicked_pdf_stylesheet_link_tag "report_styles/styles" -%>`
To:
`<%= wicked_pdf_stylesheet_link_tag "stylesheets/report_styles/styles" -%>`
My directory structure to that scss file is:

> App
>   assets
>     stylesheets
>       report_styles
>         styles.scss
Relative good because it is generating de PDF but not applying the css style. Header and footer have separated scss files at the same directory and it is being applied. At least part of it, they look weird.

**Comment by Xavoski** [comment]
Sorry for being wordy, but i hope newbie readers like me understand each step i took.

The problem is in styles.scss imports. After i removed bootstrap imports:
```
@import 'bootstrap/functions';
@import 'bootstrap/variables';
$sizes: map-merge((10: 10%, 20: 20%, 30: 30%, 33: 33%, 40: 40%, 45: 45%, 60: 60%), $sizes);
@import 'bootstrap';
```
My layout file:
```
<!DOCTYPE html>
<html>
<head>
  <title>Report title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" charset="utf-8">

  <%= wicked_pdf_stylesheet_link_tag "report_styles/styles" -%>
  <%= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>
```

The styles.scss was applied to my PDF. I don't know why it was working with Bootstrap imports and now it stopped. 
At least the problem was never in Wicked_pdf, congratulations and thank you.

**Comment by Xavoski** [comment]
Why it return that weird error when importing `@import 'bootstrap';` and when import the wrong file `@import 'bootstrapQWE';` it return a more clear error?

> ActionView::Template::Error - Error: File to import not found or unreadable: bootstrapQWE.
>         on line 1:1 of app/assets/stylesheets/report_styles/styles.scss
> >> @import 'bootstrapQWE';
>

**Comment by satrapal** [comment]
Hi @Xavoski . I had same issue today. Error: PDF could not be generated! Command Error: Loading pages (1/6). And problem appears only when I use @import 'bootstrap'. I'm on newer Ubuntu than before (when it works).

My setup:

Gemfile
`gem 'bootstrap', '~> 4.3.1'`

app/assets/stylesheets/pdf.scss
```
@import 'bootstrap';

thead { display: table-header-group; }
tfoot { display: table-row-group; }
tr { page-break-inside: avoid; }
```

app/views/layouts/application.pdf.erb
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= wicked_pdf_stylesheet_link_tag('pdf') %>
    <script>
      function number_pages() {
        ...
      }
    </script>
  </head>
  <body onload="number_pages()">
    <%= yield %>
  </body>
</html>
```

After some investigation I tried update Bootstrap gem to version 4.6.0 and everything is OK now without any other change in code. So I just change code in Gemfile to:
`gem 'bootstrap', '~> 4.6.0'`

Hope It will work for you too.

**Comment by Xavoski** [comment]
> Hi @Xavoski . I had same issue today. Error: PDF could not be generated! Command Error: Loading pages (1/6). And problem appears only when I use @import 'bootstrap'. I'm on newer Ubuntu than before (when it works).
> 
> My setup:
> 
> Gemfile
> `gem 'bootstrap', '~> 4.3.1'`
> 
> app/assets/stylesheets/pdf.scss
> 
> ```
> @import 'bootstrap';
> 
> thead { display: table-header-group; }
> tfoot { display: table-row-group; }
> tr { page-break-inside: avoid; }
> ```
> 
> app/views/layouts/application.pdf.erb
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <%= wicked_pdf_stylesheet_link_tag('pdf') %>
>     <script>
>       function number_pages() {
>         ...
>       }
>     </script>
>   </head>
>   <body onload="number_pages()">
>     <%= yield %>
>   </body>
> </html>
> ```
> 
> After some investigation I tried update Bootstrap gem to version 4.6.0 and everything is OK now without any other change in code. So I just change code in Gemfile to:
> `gem 'bootstrap', '~> 4.6.0'`
> 
> Hope It will work for you too.
