### ISSUE TITLE
ERB fields not getting evaluated after upgrading to Rails 5.2 from 4

### ISSUE THREAD

**Issue by jeffchuber** [mileszs/wicked_pdf#941]
## Issue description
ERB is not getting evaluated when generating a PDF. This broke when upgrading from Rails 4 to 5. 

Current code (but tried a lot of other things
```ruby
def order_form_details_pdf
    # DEV: We break down our render options so we can disable PDF rendering for easy testing
    #   Ideally we would stub out `render` but Rails is being finnicky
    render_options = {:template => 'fabrication/part_orders/order_form_details_pdf.pdf.erb'}
    render_options[:pdf] = "file_name" if Rails.configuration.render_pdf
    render(render_options)
  end
```

<img width="856" alt="Screen Shot 2020-08-27 at 2 16 14 PM" src="https://user-images.githubusercontent.com/891664/91497368-bfccb080-e872-11ea-9993-d617226ad592.png">

I'm completely stumped! 

## Expected or desired behavior
The fields are filled out. 

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 1.2.2

wkhtmltopdf version (output of `wkhtmltopdf --version`): 0.12.6.3

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Mac local dev

**Comment by unixmonkey** [comment]
Does it work if you specify `handlers` and/or `formats`, something like this?

```ruby
render_options = {
  :template => 'fabrication/part_orders/order_form_details_pdf.pdf.erb',
  :formats => [Rails.configuration.render_pdf ? :pdf : :html],
  :handlers => [:erb]
}
```

I could be remembering wrong, but I think between 4 and 5, templates are no longer assumed to be html or erb, but treated as plain text by default.

**Comment by jeffchuber** [comment]
Strange, the solution was tinkering with the filename extensios. This comment helped me know what to google for, so thank you very much @unixmonkey ! 

New file name is `order_form_details_pdf.html.pdf.erb` and new minimally altered block is 

```ruby
def order_form_details_pdf
    # DEV: We break down our render options so we can disable PDF rendering for easy testing
    #   Ideally we would stub out `render` but Rails is being finnicky
    # render_options = {:template => 'fabrication/part_orders/order_form_details_pdf.pdf.erb'}
    # render_options[:pdf] = "file_name" if Rails.configuration.render_pdf
      :template => 'fabrication/part_orders/order_form_details_pdf.html.pdf.erb',
    }
    render_options[:pdf] = "file_name"
    render(render_options)
  end
```

Closing - hope this breadcrumb helps someone else someday.
