### ISSUE TITLE
Not working on AWS

### ISSUE THREAD

**Issue by belarba** [mileszs/wicked_pdf#942]
Hello

On my local machine it works perfectly.

But when I commit to AWS, I get an generic 'Could not Generate PDF' error

Seems that the problem is with the `wkhtmltopdf` but maybe someone could help me?

**Comment by unixmonkey** [comment]
Please provide some more information do diagnose the issue.

Is `wkhtmltopdf` installed on the server?
Is it through a provider gem, or a system package?
What version is it?

In your server logs or console when generating a PDF, what is the full command being run?
Is that command running the correct binary path for `wkhtmltopdf`?

**Comment by belarba** [comment]
> Is `wkhtmltopdf` installed on the server?

We tried two ways: as `gem 'wkhtmltopdf-binary'` and installing it. But when we run `apt-get install -y wkhtmltopdf` it is installed the version 0.12.1 of it. Seems that our server configuration is not able to get the newest one.

> In your server logs or console when generating a PDF, what is the full command being run?

`html = render_to_string(:action => :contract, :layout => "contract", :orientation => "Portrait") 
    pdf = WickedPdf.new.pdf_from_string(html, {:encoding => 'utf8', :orientation => 'Landscape'}) `

The log of the error:

```
RuntimeError (Failed to execute:
["/usr/bin/xvfb-run", "/usr/local/bundle/bin/wkhtmltopdf", "--encoding", "utf8", "--orientation", "Landscape", "file:////tmp/wicked_pdf20200903-1019-6s8weh.html", "/tmp/wicked_pdf_generated_file20200903-1019-g38lyv.pdf"]
Error: PDF could not be generated!
Command Error: ):
```
I've tried with and without the `xvfb-run: true` on the wicked config file.
When we installed the `wkhtmltopdf`on server, we needed to run it as `xvfb-run wkhtmltopdf http://google.com google.pdf` so the PDF could be generated by command line

Thanks in advance!

**Comment by belarba** [comment]
The newest gem that works on my AWS is `gem 'wkhtmltopdf-binary', '~> 0.12.5.4'`

But I can't generate the PDF. It gives me a generic 500 error. I can't download the PDf by send_data nor send as attachment on e-mail.

**Comment by belarba** [comment]
Well, now its working. Well, I can save the PDF or use save_data to save it.

But I'm not able to attach it on an email...

Is there maybe any kind of encoding?

**Comment by belarba** [comment]
solved.
had to use `gem 'wkhtmltopdf-binary', '~> 0.12.5.4'`
when create the pdf, I had to save it in some location and to use `File.binread(path)` to attach on email

**Comment by unixmonkey** [comment]
I'm curious why you needed to save the file and read it back in to attach to an email. Does something like this in the mailer not work for you?

```ruby
class BookingMailer < ApplicationMailer
  def booking_contract(booking, pdf)
    attachments['my_pdf.pdf'] = pdf
    mail(to: user.email, subject: 'new booking')
  end
end
```

Or generating it directly inside the mailer like this:
```ruby
class BookingMailer < ApplicationMailer
  def booking_contract(booking)
    html = render_to_string(:action => :contract, :layout => "contract", :orientation => "Portrait") 
    pdf = WickedPdf.new.pdf_from_string(html, {:encoding => 'utf8', :orientation => 'Landscape'})
    attachments['my_pdf.pdf'] = pdf
    mail(to: user.email, subject: 'new booking')
  end
end
```

**Comment by belarba** [comment]
The first way I've tried and it does not work. I get and strange error, that looks like something about encoding.
The second way I can try latter.
