### ISSUE TITLE
Enabling local file access for wkhtmltopdf

### ISSUE THREAD

**Issue by turgs** [mileszs/wicked_pdf#944]
Is there a way to set an initializer to enable the `--enable-local-file-access` flag on `wkhtmltopdf`:  
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4408#issuecomment-683819255

My images stopped rendering within PDFs.

As a workaround, I'm not Base64 encoding the image data to the src attribute, which is working:  
https://github.com/mileszs/wicked_pdf/issues/36#issuecomment-91027880

However, it reads to me like enabling local file access is now required, and would resolve the issue properly too.

**Comment by unixmonkey** [comment]
Yes, you can add it to your initializer like this:

__config/initializers/wicked_pdf.rb__
```ruby
WickedPdf.config = {
  enable_local_file_access: true
}
```

And it will automatically get added to all calls.

**Comment by yulyanovikova** [comment]
@unixmonkey I think it's worth adding to the documentation

**Comment by unixmonkey** [comment]
@yulyanovikova It's already in the generated initializer, and mentioned on the README, but I've also just added an extra note [here](https://github.com/mileszs/wicked_pdf/commit/2dc96dde2e0fd7362395064f2480cac1edcc1f48).

If you had something different in mind, PRs are welcome.

**Comment by VictorGaribay** [comment]
@unixmonkey  thanks it worked for me
