### ISSUE TITLE
b & w image appears faint - like at 30% opacity

### ISSUE THREAD

**Issue by partitura** [mileszs/wicked_pdf#958]
I have a black and white logo image that is stored as a rails active storage attachment to a model.  It displays perfectly when loaded into an html page.  The image seems to be loading into WickedPdf correctly, but when the generated pdf is displayed, the image looks like it is getting close to being transparent.

I have tried changing the jpg file to png and gif, and tried changing it from RGB to grayscale.  I've also tried turning on and off the transparency on the png image, and also changing the color space, and embedding the sRGB color space.  Nothing that I have done fixes the problem.

I've included a screenshot of part of the rendered pdf file.  

Thanks for your help!

## System specifications
wicked_pdf gem version: 2.1.0
wkhtmltopdf version: 0.12.6 (with patched qt)
whtmltopdf [provider gem]: wkhtmltopdf-heroku- '2.12.6.0'
platform/distribution and version: Heroku-20 stack

<img width="952" alt="Screen Shot 2021-01-01 at 6 51 32 PM" src="https://user-images.githubusercontent.com/76573546/103448675-84981f00-4c62-11eb-9eaf-e60d90d14a90.png">

**Comment by partitura** [comment]
I found a thread in the wkhtmltopdf repository regarding a similar problem.  User henryavila suggested this hack:

     <span style="color: #FFFFFF">.</span>

I placed this immediately before my image link, and it solved the problem!  Thank you henryavila!!!

**Comment by unixmonkey** [comment]
This is a `wkhtmltopdf` issue, but thank you for posting it, and the suggested work-around.
