### ISSUE TITLE
Image not showing in the file attached to action mailer

### ISSUE THREAD

**Issue by eugesma** [mileszs/wicked_pdf#960]
## Issue description
When i download the pdf directly, the images works fine, but when i attach the pdf to a mail, the image its in blank.

In the pdf file i put:

estimation_pdf.html.erb
`<%= image_tag(wicked_pdf_asset_pack_path("media/images/header_lighuen.png"), width: "600", height: "120") %>`

estimation_mailer.rb
```
class EstimationMailer < ApplicationMailer
  helper ApplicationHelper

  def new_estimation_email
    @estimation = params[:estimation]
    
    # Attach the Lighuen logo
    attachments.inline["encabezado_email.jpg"] = File.read("#{Rails.root}/app/assets/images/encabezado_email.jpg")

    
    attachments["Presupuesto "+@estimation.created_at.strftime("%d/%m/%Y")+".pdf"] = WickedPdf.new.pdf_from_string(
      render_to_string(
        :template => 'shared/estimation_pdf.html.erb',
        page_size: 'A4',
        layout: 'light_pdf.html',
        encoding: 'UTF-8',
        disable_smart_shrinking: true,
        viewport_size: '1920x1080',
        margin:  {   
          top:               10,                     # default 10 (mm)
          bottom:            10,
          left:              5,
          right:             5
        }
      )
    )

    mail(to: "#{@estimation.client_email}", subject: "Presupuesto "+@estimation.code+" "+@estimation.created_at.strftime("%d/%m/%Y"))
  end
end

```
The attached pdf file
![image](https://user-images.githubusercontent.com/18295285/105647314-803adc80-5e83-11eb-9954-a265dbb7e837.png)

## Expected or desired behavior
Show the header logo the same way as when i download the file
![image](https://user-images.githubusercontent.com/18295285/105647383-06efb980-5e84-11eb-8f56-d097ccbda01d.png)

## System specifications
I'm using Rails 6, Ruby 3.0.0 and webpacker. 
wicked_pdf gem version (2.1.0)
wkhtmltopdf version (0.12.6.5)
Ubuntu 18.04

**Comment by eugesma** [comment]
I moved the following to the EstimationController, so i render it before send to the MailerController. 
```
          @pdf = WickedPdf.new.pdf_from_string(
            render_to_string(
              :template => 'shared/estimation_pdf.html.erb',
              page_size: 'A4',
              layout: 'light_pdf.html',
              encoding: 'UTF-8',
              disable_smart_shrinking:        true,
              viewport_size: '1920x1080',
              margin:  {   
                top:               10,                     # default 10 (mm)
                bottom:            10,
                left:              5,
                right:             5
              }
            )
          )
          EstimationMailer.with(estimation: @estimation, pdf: @pdf).new_estimation_email.deliver_now
```

**Comment by unixmonkey** [comment]
For reference, here's the StackOverflow post where this got cross-posted and answered: https://stackoverflow.com/questions/65876570/wicked-pdf-not-showing-images-in-action-mailer
