### ISSUE TITLE
Can't find documentation on rendering images outside of the views for rails 6.1.2.1

### ISSUE THREAD

**Issue by madelynrr** [mileszs/wicked_pdf#965]
## Issue description
We are getting a `WARN: ArgumentError: wrong number of arguments (given 1, expected 3)` using `ActionView::Base.new` with rails 6.1.2.1.

We are using Wicked PDF here:
`pdf = WickedPdf.new.pdf_from_string(pdf_html(selected_users), page_size: 'Letter', encoding: 'UTF-8')`

pdf_html is passing in this:
```
@view.render(
      template: 'pdfs/insights.html.haml',
      layout: 'layouts/pdf.html.haml',
      locals: { current_user: User.find(user_id) }
    )
```
And the @view is from `ActionView::Base.new`:
@view = ActionView::Base.new(ActionView::LookupContext.new(ActionView::ViewPaths.all_view_paths))

## Expected or desired behavior
We're trying to render the PDF outside of the controller. TIA!

## System specifications
Rails: 6.1.2.1

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 2.1.0

wkhtmltopdf version (output of `wkhtmltopdf --version`): 0.12.5

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used: n/a

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu for development, deploying to heroku

**Comment by brendon** [comment]
@madelynrr, did you ever find a solution?
