### ISSUE TITLE
CSS not applying to pseudo selectors (`::marker`)

### ISSUE THREAD

**Issue by dannyk3941** [mileszs/wicked_pdf#970]
## Issue description
Trying to style pseudo classes in css (`::marker`) does not work using the gem. 

## Expected or desired behavior
Styling should apply to pseudo classes, it looks like pseudo selectors such as `:hover` works but the styles for other pseudo selectors don't seem to work. 

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): wicked_pdf (2.1.0)
wkhtmltopdf version (output of `wkhtmltopdf --version`): wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:
'wkhtmltopdf-binary'

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Mac OSX

**Comment by unixmonkey** [comment]
This is entirely on `wkhtmltopdf`
