### ISSUE TITLE
page_site, page_width, page_height, nothing is working

### ISSUE THREAD

**Issue by c2ofh** [mileszs/wicked_pdf#979]
## Issue description

I want to convert a square image to a PDF. The image is quite small, but I alway get A4 size rendered.  
I've tried several options.

```ruby
pdf = WickedPdf.new.pdf_from_string(
  ApplicationController.new.render_to_string(template: 'templates/pms/qr_code', disposition: 'attachment', layout: 'application.print', lowquality: false, image_quality: 100, page_size: nil, book: false, locals: { image: img })
);
```

```ruby
pdf = WickedPdf.new.pdf_from_string(
  ApplicationController.new.render_to_string(template: 'templates/pms/qr_code', disposition: 'attachment', layout: 'application.print', lowquality: false, image_quality: 100, page_size: nil, page_height: '5in', page_width: '5in', book: false, locals: { image: img })
);
```

```ruby
pdf = WickedPdf.new.pdf_from_string(
  ApplicationController.new.render_to_string(template: 'templates/pms/qr_code', disposition: 'attachment', layout: 'application.print', lowquality: false, image_quality: 100, page_size: 'A6', book: false, locals: { image: img })
);
```
,...

## Expected or desired behavior

If I set `page_width` and `page_height`, the pdf should be this size.

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`): 2.0.2

wkhtmltopdf version (output of `wkhtmltopdf --version`): 0.12.5 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used: wkhtmltopdf-binary (0.12.5.4)

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar): Ubuntu 16.04

**Comment by unixmonkey** [comment]
In a project that has WickedPdf loaded, calls to `render` or `render_to_string` that also include a `:pdf` symbol in the options (important!), those pdf options are stripped out and passed to WickedPdf (and wkhtmltopdf) in the PDF writing phase.

Either of the below following should work for you:

```ruby
pdf = ApplicationController.new.render_to_string(pdf: 'mypdf', template: 'templates/pms/qr_code', disposition: 'attachment', layout: 'application.print', lowquality: false, image_quality: 100, page_size: nil, page_height: '5in', page_width: '5in', book: false, locals: { image: img })
```

```ruby
html = ApplicationController.new.render_to_string(template: 'templates/pms/qr_code', layout: 'application.print', locals: { image: img })
pdf_options =  { lowquality: false, image_quality: 100, page_size: nil, page_height: '5in', page_width: '5in', book: false }
pdf = WickedPdf.new.pdf_from_string(html, pdf_options)
```

Let me know how it goes!

**Comment by c2ofh** [comment]
@unixmonkey Thank you very much :) It's working
