### ISSUE TITLE
<%= wicked_pdf_image_tag 'https://aaa.com' %> not working

### ISSUE THREAD

**Issue by shiralwz** [mileszs/wicked_pdf#980]
I have a picture link, for example, 'https://aaa.com'

<%= wicked_pdf_image_tag 'https://aaa.com' %> not working on Heroku, Rails 4.

Then I tried 
<%= image_tag 'https://aaa.com' %>
and 
<%= javascript_include_tag 'https://aaa.com' %>

None of them works. Would you mind give me some suggestions on how to use the image URLs properly?
Thank you.

**Comment by unixmonkey** [comment]
What does the `<img src="">` tag look like if you inspect the source?

**Comment by shiralwz** [comment]
![image](https://user-images.githubusercontent.com/6162142/127596207-62ff478d-9ca4-46e9-a772-91d8815815d5.png)


![image](https://user-images.githubusercontent.com/6162142/127596253-e3dd2952-0a03-4e8d-8dd7-c40f86233b5c.png)

Oh, it's because the width and height changed to 0.
but even I assigned the style, still can't show up.

**Comment by shiralwz** [comment]
Found the issue: we used to use static file in our project. so there is no css to define width and height for it.
but after we changed the static file path "/logo" to a URL. the css changed.
All the width and height changed to 0. After set up css properly. it shows up on the page.

thank you
