### ISSUE TITLE
In About section link to wicked pdf block is not working

### ISSUE THREAD

**Issue by abnair1982** [mileszs/wicked_pdf#984]
## Issue description
Following link in about section is not working. It is returning 404.
http://mileszs.com/blog/2009/06/17/wicked-pdf-plugin.html
## Expected or desired behavior
Load wicked-pdf-plugin.html correctly.
## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by unixmonkey** [comment]
The correct link is now http://www.mileszs.com/wicked-pdf-plugin.

However, I can't see where you found this in the project.
Can you point me to exactly where you found this, or submit a pull request?

**Comment by abnair1982** [comment]
It is just below the about section in wicked_pdf home page. Please check the screenshot in the attachment

![Untitled](https://user-images.githubusercontent.com/59200388/129022927-81f64839-c7a9-40ee-82bd-4354146d5078.jpg)

**Comment by RanX12** [comment]
hi, I also encountered the same problem. It is normal to click the link on the html, but after exporting the PDF, it will change the `%` in the URL to `%25`, which will return a 404 Not Found

**Comment by mileszs** [comment]
Fixed.
