### ISSUE TITLE
The ‘%’ in the URL became ‘%25’, causes to return 404 after clicking

### ISSUE THREAD

**Issue by RanX12** [mileszs/wicked_pdf#985]
Hi

There is a link in the PDF file I exported to download the file, and the link on the Web html can be downloaded normally, but after the PDF is exported, the% in the URL will be changed to %25, return 404 Not Found（Chinese will be included in the link）

## Expected or desired behavior

I hope to be able to click the link in the pdf to download additional files

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
`wicked_pdf (2.1.0)`
wkhtmltopdf version (output of `wkhtmltopdf --version`):
`wkhtmltopdf-binary (0.12.6.5)`

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

`macOs Catalina 10.15.6 and Ubuntu 16.04.1`

**Comment by AdanAlonso** [comment]
This happened to me as well, it seems like setting the `wkhtmltopdf-binary` gem version to `0.12.4` in the Gemfile fixed it:

`
gem 'wkhtmltopdf-binary', '0.12.4'
`
