### ISSUE TITLE
When saving a PDF, smart apostrophes get converted into weird text

### ISSUE THREAD

**Issue by 96StanleyLee** [mileszs/wicked_pdf#991]
## Issue description
After saving a PDF all smart apostrophes get converted into weird text.

## Expected or desired behavior
When rendering it as a PDF in the browser the smart apostrophe shows up correctly.
![image](https://user-images.githubusercontent.com/45775140/139722119-9ee0ee61-79bf-4f50-8b97-42a22c8b21e0.png)

When saved as a PDF file it gets converted into weird text.
![image](https://user-images.githubusercontent.com/45775140/139722198-2ac222ce-3a6d-4636-999e-15f1292d5b80.png)

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wicked_pdf (2.1.0)

wkhtmltopdf version (output of `wkhtmltopdf --version`):

wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

macOS Big Sur 11.6

**Comment by 96StanleyLee** [comment]
Adding charset='utf-8' to my meta tag worked. Originally it didn't so odd that it worked randomly

**Comment by unixmonkey** [comment]
Please make sure your PDF layout has this meta tag `<meta charset='utf-8' />` to allow `wkhtmltopdf` to render UTF-8 characters.

Also, ensure you have the necessary fonts to render those characters installed at the system level, or explicitly provided in the HTML/CSS.
